# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx690tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/hotbm_log.cache/wt [current_project]
set_property parent.project_path C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/hotbm_log.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc709:part0:1.8 [current_project]
set_property ip_output_repo c:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/hotbm_log.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/logd_mac_muladd_4ncg.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/logd_mul_mul_9ns_ocq.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red_invtable0.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red_logtablbkb.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red_logtablcud.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red_logtabldEe.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red_logtable6.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red_logtable7.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red_logtable8.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red_logtableOg.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red_logtablfYi.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red_logtablg8j.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red_logtablhbi.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red_logtablibs.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red_logtabljbC.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red_logtablkbM.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red_logtabllbW.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/range_red_logtablmb6.v
  C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/logd.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/hotbm_log.srcs/constrs_1/new/ap_clk.xdc
set_property used_in_implementation false [get_files C:/Users/caner/OneDrive/Documents/GitHub/DSDM-Project/Vivado/hotbm_log/hotbm_log.srcs/constrs_1/new/ap_clk.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top logd -part xc7vx690tffg1761-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef logd.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file logd_utilization_synth.rpt -pb logd_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
