// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="logd,hls_ip_2018_3,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx690tffg1761-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.572857,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=11,HLS_SYN_FF=3787,HLS_SYN_LUT=9689,HLS_VERSION=2018_3}" *)

module logd (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        ap_return
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] x;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] FirstBit_fu_498_p3;
reg   [0:0] FirstBit_reg_3668;
wire   [53:0] Y0_fu_536_p3;
reg   [53:0] Y0_reg_3673;
wire   [0:0] sR_fu_607_p2;
reg   [0:0] sR_reg_3678;
wire   [10:0] absE_fu_619_p3;
reg   [10:0] absE_reg_3687;
wire   [0:0] tmp_122_fu_627_p2;
reg   [0:0] tmp_122_reg_3693;
wire   [0:0] tmp_123_fu_633_p2;
reg   [0:0] tmp_123_reg_3697;
wire   [0:0] tmp_124_fu_639_p2;
reg   [0:0] tmp_124_reg_3701;
wire   [0:0] tmp_125_fu_645_p2;
reg   [0:0] tmp_125_reg_3705;
wire   [0:0] tmp_138_fu_651_p3;
reg   [0:0] tmp_138_reg_3709;
wire   [0:0] tmp_128_fu_659_p2;
reg   [0:0] tmp_128_reg_3713;
wire   [0:0] p_result_5_fu_699_p2;
reg   [0:0] p_result_5_reg_3717;
wire   [0:0] p_result_5_1_fu_715_p2;
reg   [0:0] p_result_5_1_reg_3722;
wire   [0:0] p_result_4_fu_757_p2;
reg   [0:0] p_result_4_reg_3727;
wire   [0:0] p_result_4_1_fu_799_p2;
reg   [0:0] p_result_4_1_reg_3732;
wire   [0:0] p_result_3_fu_917_p2;
reg   [0:0] p_result_3_reg_3737;
wire   [0:0] p_result_3_1_fu_971_p2;
reg   [0:0] p_result_3_1_reg_3742;
wire   [0:0] p_result_2_fu_1151_p2;
reg   [0:0] p_result_2_reg_3747;
wire   [0:0] p_result_2_1_fu_1305_p2;
reg   [0:0] p_result_2_1_reg_3753;
wire   [7:0] p_val8_fu_1375_p3;
reg   [7:0] p_val8_reg_3759;
reg   [3:0] tmp_159_reg_3764;
wire   [7:0] p_val8_2_fu_1445_p3;
reg   [7:0] p_val8_2_reg_3769;
reg   [3:0] tmp_171_reg_3774;
wire   [0:0] tmp_178_fu_1463_p2;
reg   [0:0] tmp_178_reg_3779;
wire   [25:0] tmp_223_fu_1469_p1;
reg   [25:0] tmp_223_reg_3784;
reg   [4:0] A_reg_3790;
wire   [63:0] tmp_127_fu_1490_p1;
wire   [5:0] lzo_fu_1623_p2;
reg   [5:0] lzo_reg_3800;
wire    ap_CS_fsm_state2;
wire    grp_range_red_fu_448_ap_ready;
wire    grp_range_red_fu_448_ap_done;
wire  signed [6:0] shiftval_fu_1633_p2;
reg  signed [6:0] shiftval_reg_3805;
wire   [0:0] small_fu_1661_p2;
reg   [0:0] small_reg_3811;
reg   [63:0] almostLog_H_reg_3817;
reg   [63:0] almostLog_L_reg_3822;
wire   [24:0] absZ0s_fu_1703_p1;
reg   [24:0] absZ0s_reg_3827;
wire   [26:0] squarerIn_fu_1729_p3;
reg   [26:0] squarerIn_reg_3833;
wire   [54:0] tmp_250_fu_1737_p1;
reg   [54:0] tmp_250_reg_3838;
wire   [59:0] tmp_251_fu_1741_p1;
reg   [59:0] tmp_251_reg_3843;
wire   [22:0] tmp_257_fu_1745_p1;
reg   [22:0] tmp_257_reg_3848;
wire   [59:0] LogF_normal_L_2_fu_1800_p2;
reg   [59:0] LogF_normal_L_2_reg_3853;
wire    ap_CS_fsm_state3;
reg   [0:0] tmp_256_reg_3858;
wire   [30:0] Z2o2_small_fu_1835_p3;
reg   [30:0] Z2o2_small_reg_3864;
reg   [7:0] tmp_231_cast_reg_3870;
wire    ap_CS_fsm_state4;
reg   [0:0] tmp_140_reg_3875;
reg   [25:0] tmp_347_cast_reg_3880;
wire   [63:0] LogF_normal_H_2_fu_1956_p3;
reg   [63:0] LogF_normal_H_2_reg_3885;
wire   [60:0] tmp_194_fu_1964_p2;
reg   [60:0] tmp_194_reg_3891;
wire   [60:0] tmp_196_fu_1970_p2;
reg   [60:0] tmp_196_reg_3896;
wire  signed [61:0] Log_normal_L_fu_2005_p3;
reg  signed [61:0] Log_normal_L_reg_3901;
wire    ap_CS_fsm_state5;
wire   [59:0] Log_normal_L_1_fu_2012_p1;
reg   [59:0] Log_normal_L_1_reg_3915;
wire   [63:0] tmp_200_fu_2046_p2;
reg   [63:0] tmp_200_reg_3921;
wire   [63:0] tmp_201_fu_2056_p2;
reg   [63:0] tmp_201_reg_3926;
wire   [0:0] p_result_5_2_fu_2080_p2;
reg   [0:0] p_result_5_2_reg_3931;
wire   [0:0] p_result_4_2_fu_2130_p2;
reg   [0:0] p_result_4_2_reg_3940;
wire   [0:0] sel_tmp27_fu_2152_p2;
reg   [0:0] sel_tmp27_reg_3947;
wire   [0:0] p_result_3_2_fu_2208_p2;
reg   [0:0] p_result_3_2_reg_3952;
wire   [3:0] tmp_224_fu_2280_p3;
reg   [3:0] tmp_224_reg_3960;
wire   [7:0] tmp_234_fu_2324_p3;
reg   [7:0] tmp_234_reg_3965;
wire   [63:0] Log_normal_H_fu_2332_p3;
reg   [63:0] Log_normal_H_reg_3970;
wire    ap_CS_fsm_state6;
wire   [0:0] p_result_5_3_fu_2670_p2;
reg   [0:0] p_result_5_3_reg_3975;
wire   [0:0] p_result_4_3_fu_2708_p2;
reg   [0:0] p_result_4_3_reg_3980;
wire   [0:0] p_result_3_3_fu_2842_p2;
reg   [0:0] p_result_3_3_reg_3985;
wire   [0:0] sel_tmp44_fu_2930_p2;
reg   [0:0] sel_tmp44_reg_3990;
wire   [0:0] sel_tmp47_fu_2948_p2;
reg   [0:0] sel_tmp47_reg_3995;
wire   [0:0] or_cond3_fu_3004_p2;
reg   [0:0] or_cond3_reg_4000;
wire   [3:0] tmp_284_fu_3060_p3;
reg   [3:0] tmp_284_reg_4005;
wire   [3:0] newSel4_fu_3068_p3;
reg   [3:0] newSel4_reg_4010;
wire   [7:0] p_val8_6_fu_3144_p3;
reg   [7:0] p_val8_6_reg_4015;
reg   [3:0] tmp_294_reg_4020;
wire   [6:0] tmp_302_fu_3162_p2;
reg   [6:0] tmp_302_reg_4025;
wire   [6:0] E_normal_H_2_fu_3271_p3;
reg   [6:0] E_normal_H_2_reg_4030;
wire    ap_CS_fsm_state7;
wire   [56:0] tmp_332_fu_3350_p3;
reg   [56:0] tmp_332_reg_4035;
wire    grp_range_red_fu_448_ap_start;
wire    grp_range_red_fu_448_ap_idle;
wire   [63:0] grp_range_red_fu_448_ap_return_0;
wire   [63:0] grp_range_red_fu_448_ap_return_1;
wire   [63:0] grp_range_red_fu_448_ap_return_2;
reg   [63:0] ap_phi_mux_p_0_phi_fu_427_p14;
reg   [63:0] p_0_reg_420;
wire   [63:0] tmp_341_fu_3655_p1;
wire    ap_CS_fsm_state8;
reg    grp_range_red_fu_448_ap_start_reg;
wire   [63:0] fpX_fu_486_p1;
wire   [51:0] tmp_130_fu_494_p1;
wire   [52:0] tmp_117_fu_524_p3;
wire   [0:0] tmp_135_fu_506_p3;
wire   [53:0] tmp_203_cast_fu_532_p1;
wire   [53:0] tmp_s_fu_514_p4;
wire   [0:0] tmp_118_fu_545_p2;
wire   [9:0] tmp_119_fu_551_p3;
wire   [10:0] tmp_208_cast_fu_563_p4;
wire   [10:0] tmp_207_cast_fu_559_p1;
wire   [0:0] tmp_137_fu_587_p3;
wire   [62:0] tmp_120_fu_579_p3;
wire   [0:0] not_tmp_s_fu_601_p2;
wire   [0:0] phitmp_fu_595_p2;
wire   [10:0] E_fu_573_p2;
wire   [10:0] tmp_121_fu_613_p2;
wire   [62:0] tmp_fu_490_p1;
wire   [51:0] tmp_132_fu_665_p4;
wire   [63:0] MAN_IN_1_fu_675_p3;
wire   [63:0] MAN_IN_fu_683_p2;
wire   [31:0] tmp_141_fu_689_p4;
wire   [31:0] tmp_151_fu_705_p4;
wire   [15:0] tmp_158_fu_731_p4;
wire   [47:0] st1_fu_721_p4;
wire   [47:0] tmp_138_cast_fu_741_p1;
wire   [47:0] p_v_fu_745_p3;
wire   [15:0] tmp_164_fu_753_p1;
wire   [16:0] tmp_165_fu_773_p4;
wire   [48:0] st2_fu_763_p4;
wire   [48:0] tmp_141_cast_fu_783_p1;
wire   [48:0] p_in_fu_787_p3;
wire   [15:0] tmp_176_fu_795_p1;
wire   [7:0] tmp_133_fu_805_p4;
wire   [7:0] tmp_134_fu_815_p4;
wire   [3:0] tmp_142_fu_833_p4;
wire   [7:0] tmp_246_cast_fu_843_p3;
wire   [7:0] tmp_247_cast_fu_851_p4;
wire   [7:0] tmp_136_fu_825_p3;
wire   [7:0] tmp_250_cast_fu_879_p4;
wire   [0:0] sel_tmp1_fu_897_p2;
wire   [0:0] sel_tmp2_fu_903_p2;
wire   [7:0] tmp_248_cast_fu_869_p4;
wire   [7:0] sel_tmp_fu_889_p3;
wire   [7:0] tmp_143_fu_909_p3;
wire   [7:0] p_in2_fu_861_p3;
wire   [7:0] tmp_144_fu_923_p4;
wire   [0:0] sel_tmp3_fu_941_p2;
wire   [0:0] sel_tmp4_fu_947_p2;
wire   [7:0] tmp_146_fu_953_p4;
wire   [7:0] tmp_145_fu_933_p3;
wire   [7:0] tmp_147_fu_963_p3;
wire   [3:0] tmp_258_cast_fu_993_p4;
wire   [5:0] p_in79_v_fu_977_p3;
wire   [5:0] p_in78_v_fu_985_p3;
wire   [0:0] sel_tmp5_fu_1069_p2;
wire   [0:0] sel_tmp30_demorgan_fu_1081_p2;
wire   [0:0] sel_tmp7_fu_1087_p2;
wire   [0:0] sel_tmp8_fu_1093_p2;
wire   [5:0] p_in4_v_cast_fu_1099_p3;
wire   [0:0] sel_tmp6_fu_1075_p2;
wire   [5:0] p_in79_v_pn_fu_1011_p3;
wire   [0:0] or_cond_fu_1115_p2;
wire   [5:0] newSel_v_v_fu_1107_p3;
wire   [5:0] newSel236_v_v_fu_1121_p3;
wire   [5:0] newSel238_v_v_fu_1129_p3;
wire   [63:0] newSel238_v_v_cast_fu_1137_p1;
wire   [63:0] newSel238_v_fu_1141_p2;
wire   [3:0] tmp_177_fu_1147_p1;
wire   [7:0] tmp_183_fu_1157_p1;
wire   [7:0] tmp_149_fu_1167_p4;
wire   [7:0] tmp_148_fu_1161_p2;
wire   [15:0] tmp_150_fu_1177_p3;
wire   [0:0] tmp_152_fu_1185_p2;
wire   [3:0] p_in5_fu_1003_p3;
wire   [3:0] tmp_271_cast_fu_1059_p4;
wire   [0:0] sel_tmp10_fu_1199_p2;
wire   [0:0] sel_tmp11_fu_1205_p2;
wire   [3:0] tmp_264_cast_fu_1019_p4;
wire   [3:0] sel_tmp9_fu_1191_p3;
wire   [0:0] sel_tmp13_fu_1219_p2;
wire   [0:0] sel_tmp14_fu_1225_p2;
wire   [3:0] tmp_265_cast_fu_1029_p4;
wire   [3:0] sel_tmp12_fu_1211_p3;
wire   [0:0] sel_tmp16_fu_1239_p2;
wire   [0:0] sel_tmp17_fu_1245_p2;
wire   [0:0] sel_tmp18_fu_1251_p2;
wire   [3:0] sel_tmp15_fu_1231_p3;
wire   [0:0] sel_tmp20_fu_1265_p2;
wire   [3:0] tmp_268_cast_fu_1039_p4;
wire   [3:0] sel_tmp19_fu_1257_p3;
wire   [0:0] sel_tmp55_demorgan_fu_1279_p2;
wire   [0:0] sel_tmp22_fu_1285_p2;
wire   [0:0] sel_tmp23_fu_1291_p2;
wire   [3:0] tmp_269_cast_fu_1049_p4;
wire   [3:0] sel_tmp21_fu_1271_p3;
wire   [3:0] p_in8_fu_1297_p3;
wire   [7:0] tmp_153_fu_1311_p4;
wire   [7:0] tmp_155_fu_1333_p4;
wire   [7:0] tmp_154_fu_1321_p3;
wire   [7:0] tmp_188_fu_1329_p1;
wire   [7:0] tmp_157_fu_1351_p3;
wire   [7:0] sel_tmp24_fu_1359_p3;
wire   [7:0] sel_tmp25_fu_1367_p3;
wire   [7:0] tmp_156_fu_1343_p3;
wire   [7:0] tmp_166_fu_1401_p4;
wire   [7:0] tmp_163_fu_1393_p3;
wire   [7:0] tmp_168_fu_1419_p4;
wire   [7:0] tmp_167_fu_1411_p3;
wire   [7:0] tmp_169_fu_1429_p3;
wire   [7:0] tmp_170_fu_1437_p3;
wire   [63:0] tmp_126_fu_1484_p2;
wire   [7:0] tmp_160_fu_1494_p1;
wire   [7:0] p_val8_1_fu_1497_p3;
wire   [1:0] tmp_191_fu_1503_p4;
wire   [0:0] p_result_1_fu_1513_p2;
wire   [0:0] tmp_193_fu_1519_p3;
wire   [0:0] tmp_195_fu_1527_p3;
wire   [0:0] tmp_161_fu_1535_p3;
wire   [7:0] tmp_172_fu_1555_p1;
wire   [7:0] p_val8_3_fu_1558_p3;
wire   [1:0] tmp_197_fu_1564_p4;
wire   [0:0] p_result_1_1_fu_1574_p2;
wire   [0:0] tmp_198_fu_1580_p3;
wire   [0:0] tmp_213_fu_1588_p3;
wire   [0:0] tmp_173_fu_1596_p3;
wire   [5:0] tmp_162_fu_1543_p7;
wire   [5:0] tmp_174_fu_1604_p7;
wire   [5:0] lzo_1_in_fu_1616_p3;
wire   [6:0] lzo_cast1_fu_1629_p1;
wire  signed [15:0] shiftval_cast_fu_1639_p1;
wire   [31:0] tmp_175_fu_1643_p1;
wire   [0:0] doRR_fu_1647_p3;
wire   [0:0] tmp_179_fu_1655_p2;
wire   [25:0] tmp_180_fu_1666_p2;
wire   [25:0] absZ0_fu_1671_p3;
wire   [63:0] tmp_181_fu_1689_p1;
wire   [63:0] tmp_182_fu_1693_p1;
wire   [63:0] tmp_184_fu_1697_p2;
wire   [25:0] tmp_185_fu_1717_p3;
wire   [26:0] tmp_338_cast_fu_1707_p4;
wire   [26:0] tmp_341_cast_fu_1725_p1;
wire   [26:0] Z2o2_full_fu_1752_p0;
wire   [53:0] squarerIn_1_cast_fu_1749_p1;
wire   [26:0] Z2o2_full_fu_1752_p1;
wire   [53:0] Z2o2_full_fu_1752_p2;
wire   [25:0] tmp_186_fu_1768_p4;
wire   [54:0] tmp_187_fu_1778_p1;
wire   [54:0] Log1p_normal_fu_1782_p2;
wire   [63:0] Log1p_normal_1_cast_fu_1787_p1;
wire   [59:0] tmp_189_fu_1791_p1;
wire   [63:0] LogF_normal_L_fu_1795_p2;
wire   [27:0] Z2o2_cast_fu_1758_p4;
wire   [27:0] tmp_482_cast_fu_1818_p1;
wire   [27:0] tmp_312_fu_1821_p2;
wire   [0:0] tmp_311_fu_1813_p2;
wire   [30:0] phitmp1_fu_1827_p3;
wire   [10:0] tmp_129_fu_1849_p1;
wire   [58:0] tmp_129_fu_1849_p2;
wire   [19:0] m1_fu_3660_p2;
wire   [10:0] tmp_139_fu_1859_p1;
wire   [59:0] tmp_131_fu_1862_p3;
wire   [60:0] tmp_230_cast_fu_1870_p1;
wire   [60:0] tmp_227_cast_fu_1855_p1;
wire   [60:0] m0_fu_1874_p2;
wire   [63:0] tmp_344_cast_fu_1897_p1;
wire   [22:0] tmp_190_fu_1900_p1;
wire   [33:0] tmp_260_fu_1926_p1;
wire   [59:0] absELog2_pad_L_fu_1930_p3;
wire   [22:0] LogF_normal_H_cast_fu_1908_p2;
wire   [63:0] LogF_normal_H_fu_1903_p2;
wire   [0:0] tmp_267_fu_1942_p3;
wire   [63:0] tmp_192_fu_1950_p2;
wire   [60:0] LogF_normal_L_2_cast_fu_1913_p1;
wire   [60:0] absELog2_pad_L_cast_fu_1938_p1;
wire   [7:0] tmp_233_cast_fu_1976_p1;
wire   [7:0] absELog2_H_fu_1979_p2;
wire   [33:0] absELog2_pad_H_fu_1984_p3;
wire  signed [61:0] tmp_354_cast_fu_2002_p1;
wire   [61:0] tmp_353_cast_fu_1999_p1;
wire   [0:0] tmp_282_fu_2020_p3;
wire   [34:0] absELog2_pad_H_cast_fu_1995_p1;
wire   [34:0] tmp_356_cast_fu_2032_p1;
wire   [34:0] tmp_199_fu_2036_p2;
wire  signed [63:0] tmp_357_cast_fu_2042_p1;
wire   [63:0] absELog2_pad_H_cast1_fu_1991_p1;
wire   [63:0] tmp198_fu_2051_p2;
wire   [63:0] tmp_356_cast1_fu_2028_p1;
wire   [31:0] tmp_202_fu_2062_p4;
wire   [59:0] tmp_203_fu_2072_p3;
wire   [49:0] tmp_204_fu_2086_p4;
wire   [17:0] tmp_206_fu_2100_p4;
wire  signed [19:0] tmp_207_fu_2110_p1;
wire  signed [51:0] tmp_205_fu_2096_p1;
wire   [51:0] sf_cast_fu_2114_p1;
wire   [51:0] p_in7_fu_2118_p3;
wire   [15:0] tmp_298_fu_2126_p1;
wire   [59:0] tmp_208_fu_2136_p4;
wire   [0:0] sel_tmp28_fu_2158_p2;
wire   [0:0] tmp_209_fu_2146_p2;
wire   [0:0] or_cond1_fu_2172_p2;
wire   [5:0] newSel1_fu_2164_p3;
wire   [5:0] newSel242_cast_cast_fu_2178_p3;
wire   [5:0] newSel2_fu_2186_p3;
wire  signed [63:0] Log_normal_L_cast_fu_2016_p1;
wire   [63:0] newSel244_cast_fu_2194_p1;
wire   [63:0] p_in1_fu_2198_p2;
wire   [7:0] tmp_300_fu_2204_p1;
wire   [7:0] tmp_301_fu_2214_p1;
wire   [7:0] tmp_211_fu_2224_p4;
wire   [7:0] tmp_210_fu_2218_p2;
wire   [15:0] tmp_212_fu_2234_p3;
wire   [3:0] tmp_304_fu_2248_p1;
wire   [3:0] tmp_220_fu_2252_p4;
wire   [0:0] tmp_214_fu_2242_p2;
wire   [3:0] tmp_221_fu_2262_p3;
wire   [3:0] tmp_222_fu_2270_p4;
wire   [7:0] tmp_230_fu_2288_p3;
wire   [7:0] tmp_231_fu_2296_p4;
wire   [7:0] tmp_232_fu_2306_p3;
wire   [7:0] tmp_233_fu_2314_p4;
wire   [0:0] sel_tmp29_fu_2342_p2;
wire   [0:0] sel_tmp26_fu_2337_p2;
wire   [0:0] sel_tmp32_fu_2357_p2;
wire   [0:0] sel_tmp33_fu_2362_p2;
wire   [0:0] sel_tmp121_demorgan_fu_2378_p2;
wire   [0:0] sel_tmp36_fu_2382_p2;
wire   [0:0] sel_tmp30_fu_2346_p2;
wire   [3:0] tmp_219_fu_2429_p4;
wire   [0:0] sel_tmp31_fu_2351_p2;
wire   [3:0] tmp_218_fu_2420_p4;
wire   [3:0] tmp_225_fu_2438_p3;
wire   [0:0] sel_tmp34_fu_2367_p2;
wire   [3:0] tmp_217_fu_2411_p4;
wire   [3:0] tmp_226_fu_2445_p3;
wire   [0:0] sel_tmp35_fu_2372_p2;
wire   [3:0] tmp_216_fu_2402_p4;
wire   [3:0] tmp_227_fu_2453_p3;
wire   [0:0] sel_tmp37_fu_2388_p2;
wire   [3:0] tmp_215_fu_2393_p4;
wire   [3:0] tmp_228_fu_2461_p3;
wire   [3:0] tmp_229_fu_2469_p3;
wire   [7:0] tmp_235_fu_2483_p4;
wire   [7:0] tmp_237_fu_2499_p4;
wire   [7:0] tmp_236_fu_2492_p3;
wire   [7:0] tmp_239_fu_2516_p4;
wire   [7:0] tmp_238_fu_2508_p3;
wire   [7:0] tmp_241_fu_2533_p4;
wire   [7:0] tmp_240_fu_2525_p3;
wire   [7:0] tmp_243_fu_2550_p4;
wire   [7:0] tmp_242_fu_2542_p3;
wire   [7:0] p_val8_4_fu_2559_p3;
wire   [3:0] tmp_244_fu_2567_p4;
wire   [0:0] p_result_2_2_fu_2477_p2;
wire   [7:0] tmp_245_fu_2577_p1;
wire   [7:0] p_val8_5_fu_2581_p3;
wire   [1:0] tmp_305_fu_2589_p4;
wire   [0:0] p_result_1_2_fu_2599_p2;
wire   [0:0] tmp_315_fu_2605_p3;
wire   [0:0] tmp_319_fu_2613_p3;
wire   [0:0] tmp_246_fu_2621_p3;
wire   [5:0] tmp_247_fu_2629_p7;
wire   [5:0] E_normal_L_fu_2642_p2;
wire   [31:0] tmp_248_fu_2652_p4;
wire   [33:0] tmp_249_fu_2662_p3;
wire   [45:0] tmp_252_fu_2682_p4;
wire   [63:0] tmp_323_fu_2676_p2;
wire   [63:0] tmp_253_fu_2692_p1;
wire   [63:0] p_v1_fu_2696_p3;
wire   [15:0] tmp_326_fu_2704_p1;
wire   [13:0] tmp_254_fu_2714_p4;
wire   [15:0] tmp_255_fu_2724_p3;
wire   [17:0] tmp_259_fu_2738_p4;
wire   [15:0] tmp_258_fu_2732_p2;
wire   [33:0] tmp_261_fu_2748_p3;
wire   [0:0] sel_tmp39_fu_2768_p2;
wire   [1:0] tmp_328_fu_2780_p1;
wire   [0:0] sel_tmp40_fu_2774_p2;
wire   [7:0] tmp_263_fu_2784_p3;
wire   [7:0] tmp_264_fu_2792_p4;
wire   [0:0] tmp_262_fu_2756_p2;
wire   [7:0] tmp_266_fu_2816_p4;
wire   [0:0] or_cond2_fu_2810_p2;
wire   [7:0] tmp_265_fu_2802_p3;
wire   [7:0] tmp_268_fu_2826_p3;
wire   [7:0] tmp_269_fu_2834_p3;
wire   [7:0] tmp_336_fu_2858_p1;
wire   [7:0] tmp_271_fu_2868_p4;
wire   [7:0] tmp_270_fu_2862_p2;
wire   [15:0] tmp_272_fu_2878_p3;
wire   [15:0] tmp_273_fu_2886_p2;
wire   [33:0] tmp_274_fu_2892_p3;
wire   [0:0] tmp_276_fu_2906_p2;
wire   [0:0] sel_tmp38_fu_2762_p2;
wire   [0:0] sel_tmp42_fu_2918_p2;
wire   [0:0] sel_tmp45_fu_2936_p2;
wire   [0:0] sel_tmp46_fu_2942_p2;
wire   [0:0] sel_tmp185_demorgan_fu_2960_p2;
wire   [0:0] sel_tmp49_fu_2966_p2;
wire   [0:0] sel_tmp50_fu_2972_p2;
wire   [3:0] tmp_277_fu_2978_p3;
wire   [3:0] tmp_278_fu_2986_p4;
wire   [0:0] sel_tmp48_fu_2954_p2;
wire   [0:0] sel_tmp43_fu_2924_p2;
wire   [3:0] tmp_427_cast_fu_2848_p4;
wire   [0:0] sel_tmp41_fu_2912_p2;
wire   [0:0] tmp_275_fu_2900_p2;
wire   [3:0] tmp_280_fu_3024_p4;
wire   [3:0] tmp_281_fu_3042_p4;
wire   [3:0] tmp_279_fu_2996_p3;
wire   [3:0] tmp_283_fu_3052_p3;
wire   [0:0] or_cond5_fu_3018_p2;
wire   [3:0] newSel3_fu_3010_p3;
wire   [3:0] newSel258_cast_fu_3034_p3;
wire   [7:0] tmp_286_fu_3076_p4;
wire   [7:0] tmp_287_fu_3086_p3;
wire   [7:0] tmp_288_fu_3094_p3;
wire   [7:0] tmp_290_fu_3110_p4;
wire   [7:0] tmp_289_fu_3102_p3;
wire   [7:0] tmp_291_fu_3120_p3;
wire   [7:0] tmp_292_fu_3128_p3;
wire   [7:0] tmp_293_fu_3136_p3;
wire   [6:0] E_normal_L_cast_fu_2648_p1;
wire   [0:0] or_cond4_fu_3171_p2;
wire   [0:0] or_cond6_fu_3175_p2;
wire   [3:0] tmp_285_fu_3180_p3;
wire   [0:0] p_result_2_3_fu_3186_p2;
wire   [7:0] tmp_295_fu_3192_p1;
wire   [7:0] p_val8_7_fu_3195_p3;
wire   [1:0] tmp_340_fu_3202_p4;
wire   [0:0] p_result_1_3_fu_3212_p2;
wire   [0:0] tmp_347_fu_3218_p3;
wire   [0:0] tmp_348_fu_3226_p3;
wire   [0:0] tmp_296_fu_3234_p3;
wire   [5:0] tmp_297_fu_3242_p7;
wire   [5:0] E_normal_H_fu_3255_p2;
wire   [0:0] tmp_299_fu_3265_p2;
wire   [6:0] E_normal_H_cast_fu_3261_p1;
wire   [63:0] tmp_306_fu_3284_p1;
wire   [6:0] tmp_308_fu_3293_p2;
wire  signed [31:0] tmp_472_cast_fu_3299_p1;
wire   [59:0] tmp_473_cast_fu_3303_p1;
wire   [63:0] tmp_307_fu_3288_p2;
wire   [0:0] tmp_303_fu_3278_p2;
wire   [32:0] tmp_349_fu_3312_p1;
wire   [63:0] Log_normal_L_1_cast_fu_3168_p1;
wire   [59:0] tmp_309_fu_3307_p2;
wire   [32:0] tmp_354_fu_3330_p1;
wire   [32:0] tmp_310_fu_3316_p3;
wire   [63:0] Log_normal_normd_L_fu_3324_p2;
wire   [32:0] tmp_331_fu_3334_p2;
wire   [23:0] tmp_505_cast_fu_3340_p4;
wire   [57:0] Z_small_fu_3367_p3;
wire   [58:0] Z_small_cast_fu_3374_p1;
wire   [58:0] Z2o2_small_cast_fu_3364_p1;
wire   [57:0] tmp_314_fu_3384_p4;
wire   [58:0] tmp_487_cast_fu_3392_p1;
wire   [58:0] tmp_313_fu_3378_p2;
wire   [58:0] Log_small_fu_3396_p3;
wire   [55:0] tmp_316_fu_3403_p4;
wire   [58:0] Log_small_1_fu_3413_p3;
wire   [63:0] Log_small_1_cast_fu_3421_p1;
wire   [0:0] tmp_350_fu_3425_p3;
wire   [0:0] tmp_317_fu_3433_p3;
wire   [0:0] tmp_351_fu_3449_p2;
wire   [1:0] E0_sub_fu_3441_p3;
wire   [1:0] E0_sub_1_fu_3455_p3;
wire   [9:0] tmp_318_fu_3463_p3;
wire   [10:0] tmp_492_cast_fu_3471_p1;
wire   [10:0] lzo_cast_fu_3358_p1;
wire   [10:0] tmp_471_cast_fu_3361_p1;
wire   [53:0] tmp_321_fu_3499_p4;
wire   [0:0] tmp_352_fu_3481_p3;
wire   [55:0] tmp_322_fu_3509_p3;
wire   [55:0] tmp_353_fu_3495_p1;
wire   [54:0] tmp_325_fu_3525_p4;
wire   [55:0] tmp_327_fu_3535_p3;
wire   [55:0] tmp_324_fu_3517_p3;
wire   [55:0] tmp_329_fu_3543_p3;
wire   [56:0] tmp_330_fu_3551_p3;
wire   [56:0] Log_g_fu_3559_p3;
wire   [3:0] tmp_355_fu_3565_p1;
wire   [0:0] sticky_fu_3569_p2;
wire   [0:0] tmp_357_fu_3593_p3;
wire   [0:0] tmp_356_fu_3575_p3;
wire   [0:0] tmp_334_fu_3601_p2;
wire   [0:0] tmp_335_fu_3607_p2;
wire   [10:0] E_small_fu_3475_p2;
wire   [10:0] tmp_320_fu_3489_p2;
wire   [10:0] tmp_337_fu_3617_p3;
wire   [51:0] tmp_333_fu_3583_p4;
wire   [62:0] tmp_338_fu_3624_p3;
wire   [63:0] tmp_514_cast_fu_3613_p1;
wire   [63:0] tmp_517_cast_fu_3632_p1;
wire   [63:0] EFR_fu_3636_p2;
wire   [63:0] tmp_339_fu_3642_p3;
wire   [63:0] res_fp_fu_3649_p2;
wire   [8:0] m1_fu_3660_p0;
wire   [10:0] m1_fu_3660_p1;
reg   [7:0] ap_NS_fsm;
wire   [19:0] m1_fu_3660_p10;
wire   [58:0] tmp_129_fu_1849_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_range_red_fu_448_ap_start_reg = 1'b0;
end

range_red grp_range_red_fu_448(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_range_red_fu_448_ap_start),
    .ap_done(grp_range_red_fu_448_ap_done),
    .ap_idle(grp_range_red_fu_448_ap_idle),
    .ap_ready(grp_range_red_fu_448_ap_ready),
    .A(A_reg_3790),
    .Y0(Y0_reg_3673),
    .ap_return_0(grp_range_red_fu_448_ap_return_0),
    .ap_return_1(grp_range_red_fu_448_ap_return_1),
    .ap_return_2(grp_range_red_fu_448_ap_return_2)
);

logd_mul_mul_9ns_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 20 ))
logd_mul_mul_9ns_ocq_U21(
    .din0(m1_fu_3660_p0),
    .din1(m1_fu_3660_p1),
    .dout(m1_fu_3660_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_range_red_fu_448_ap_start_reg <= 1'b0;
    end else begin
        if (((tmp_128_fu_659_p2 == 1'd0) & (tmp_138_fu_651_p3 == 1'd0) & (tmp_125_fu_645_p2 == 1'd0) & (tmp_124_fu_639_p2 == 1'd0) & (tmp_123_fu_633_p2 == 1'd0) & (tmp_122_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_range_red_fu_448_ap_start_reg <= 1'b1;
        end else if ((grp_range_red_fu_448_ap_ready == 1'b1)) begin
            grp_range_red_fu_448_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_128_fu_659_p2 == 1'd1) & (tmp_138_fu_651_p3 == 1'd0) & (tmp_125_fu_645_p2 == 1'd0) & (tmp_124_fu_639_p2 == 1'd0) & (tmp_123_fu_633_p2 == 1'd0) & (tmp_122_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_0_reg_420 <= 64'd0;
    end else if ((((tmp_138_fu_651_p3 == 1'd1) & (tmp_125_fu_645_p2 == 1'd0) & (tmp_124_fu_639_p2 == 1'd0) & (tmp_123_fu_633_p2 == 1'd0) & (tmp_122_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((tmp_124_fu_639_p2 == 1'd1) & (tmp_123_fu_633_p2 == 1'd0) & (tmp_122_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        p_0_reg_420 <= 64'd9221120237041090560;
    end else if (((tmp_123_fu_633_p2 == 1'd1) & (tmp_122_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_0_reg_420 <= 64'd9218868437227405312;
    end else if (((tmp_122_fu_627_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_0_reg_420 <= 64'd18442240474082181120;
    end else if (((tmp_128_reg_3713 == 1'd0) & (tmp_138_reg_3709 == 1'd0) & (tmp_125_reg_3705 == 1'd0) & (tmp_124_reg_3701 == 1'd0) & (tmp_123_reg_3697 == 1'd0) & (tmp_122_reg_3693 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        p_0_reg_420 <= tmp_341_fu_3655_p1;
    end else if (((tmp_125_fu_645_p2 == 1'd1) & (tmp_124_fu_639_p2 == 1'd0) & (tmp_123_fu_633_p2 == 1'd0) & (tmp_122_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_0_reg_420 <= tmp_127_fu_1490_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_128_fu_659_p2 == 1'd0) & (tmp_138_fu_651_p3 == 1'd0) & (tmp_125_fu_645_p2 == 1'd0) & (tmp_124_fu_639_p2 == 1'd0) & (tmp_123_fu_633_p2 == 1'd0) & (tmp_122_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        A_reg_3790 <= {{fpX_fu_486_p1[51:47]}};
        p_result_2_1_reg_3753 <= p_result_2_1_fu_1305_p2;
        p_result_2_reg_3747 <= p_result_2_fu_1151_p2;
        p_result_3_1_reg_3742 <= p_result_3_1_fu_971_p2;
        p_result_3_reg_3737 <= p_result_3_fu_917_p2;
        p_result_4_1_reg_3732 <= p_result_4_1_fu_799_p2;
        p_result_4_reg_3727 <= p_result_4_fu_757_p2;
        p_result_5_1_reg_3722 <= p_result_5_1_fu_715_p2;
        p_result_5_reg_3717 <= p_result_5_fu_699_p2;
        p_val8_2_reg_3769 <= p_val8_2_fu_1445_p3;
        p_val8_reg_3759 <= p_val8_fu_1375_p3;
        tmp_159_reg_3764 <= {{p_val8_fu_1375_p3[7:4]}};
        tmp_171_reg_3774 <= {{p_val8_2_fu_1445_p3[7:4]}};
        tmp_178_reg_3779 <= tmp_178_fu_1463_p2;
        tmp_223_reg_3784 <= tmp_223_fu_1469_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        E_normal_H_2_reg_4030 <= E_normal_H_2_fu_3271_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        FirstBit_reg_3668 <= fpX_fu_486_p1[32'd51];
        Y0_reg_3673 <= Y0_fu_536_p3;
        absE_reg_3687 <= absE_fu_619_p3;
        sR_reg_3678 <= sR_fu_607_p2;
        tmp_122_reg_3693 <= tmp_122_fu_627_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        LogF_normal_H_2_reg_3885 <= LogF_normal_H_2_fu_1956_p3;
        tmp_140_reg_3875 <= m0_fu_1874_p2[32'd60];
        tmp_231_cast_reg_3870 <= {{m1_fu_3660_p2[18:11]}};
        tmp_347_cast_reg_3880 <= {{m0_fu_1874_p2[59:34]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        LogF_normal_L_2_reg_3853 <= LogF_normal_L_2_fu_1800_p2;
        Z2o2_small_reg_3864[30 : 3] <= Z2o2_small_fu_1835_p3[30 : 3];
        tmp_256_reg_3858 <= LogF_normal_L_fu_1795_p2[32'd60];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        Log_normal_H_reg_3970 <= Log_normal_H_fu_2332_p3;
        newSel4_reg_4010 <= newSel4_fu_3068_p3;
        or_cond3_reg_4000 <= or_cond3_fu_3004_p2;
        p_result_3_3_reg_3985 <= p_result_3_3_fu_2842_p2;
        p_result_4_3_reg_3980 <= p_result_4_3_fu_2708_p2;
        p_result_5_3_reg_3975 <= p_result_5_3_fu_2670_p2;
        p_val8_6_reg_4015 <= p_val8_6_fu_3144_p3;
        sel_tmp44_reg_3990 <= sel_tmp44_fu_2930_p2;
        sel_tmp47_reg_3995 <= sel_tmp47_fu_2948_p2;
        tmp_284_reg_4005 <= tmp_284_fu_3060_p3;
        tmp_294_reg_4020 <= {{p_val8_6_fu_3144_p3[7:4]}};
        tmp_302_reg_4025 <= tmp_302_fu_3162_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((small_reg_3811 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        Log_normal_L_1_reg_3915 <= Log_normal_L_1_fu_2012_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        Log_normal_L_reg_3901 <= Log_normal_L_fu_2005_p3;
        p_result_3_2_reg_3952 <= p_result_3_2_fu_2208_p2;
        p_result_4_2_reg_3940 <= p_result_4_2_fu_2130_p2;
        p_result_5_2_reg_3931 <= p_result_5_2_fu_2080_p2;
        sel_tmp27_reg_3947 <= sel_tmp27_fu_2152_p2;
        tmp_224_reg_3960 <= tmp_224_fu_2280_p3;
        tmp_234_reg_3965 <= tmp_234_fu_2324_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_range_red_fu_448_ap_done == 1'b1))) begin
        absZ0s_reg_3827 <= absZ0s_fu_1703_p1;
        almostLog_H_reg_3817 <= grp_range_red_fu_448_ap_return_1;
        almostLog_L_reg_3822 <= grp_range_red_fu_448_ap_return_2;
        lzo_reg_3800 <= lzo_fu_1623_p2;
        shiftval_reg_3805 <= shiftval_fu_1633_p2;
        small_reg_3811 <= small_fu_1661_p2;
        squarerIn_reg_3833 <= squarerIn_fu_1729_p3;
        tmp_250_reg_3838 <= tmp_250_fu_1737_p1;
        tmp_251_reg_3843 <= tmp_251_fu_1741_p1;
        tmp_257_reg_3848 <= tmp_257_fu_1745_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_122_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_123_reg_3697 <= tmp_123_fu_633_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_123_fu_633_p2 == 1'd0) & (tmp_122_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_124_reg_3701 <= tmp_124_fu_639_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_124_fu_639_p2 == 1'd0) & (tmp_123_fu_633_p2 == 1'd0) & (tmp_122_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_125_reg_3705 <= tmp_125_fu_645_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_138_fu_651_p3 == 1'd0) & (tmp_125_fu_645_p2 == 1'd0) & (tmp_124_fu_639_p2 == 1'd0) & (tmp_123_fu_633_p2 == 1'd0) & (tmp_122_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_128_reg_3713 <= tmp_128_fu_659_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_125_fu_645_p2 == 1'd0) & (tmp_124_fu_639_p2 == 1'd0) & (tmp_123_fu_633_p2 == 1'd0) & (tmp_122_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_138_reg_3709 <= fpX_fu_486_p1[32'd63];
    end
end

always @ (posedge ap_clk) begin
    if (((sR_reg_3678 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_194_reg_3891 <= tmp_194_fu_1964_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((sR_reg_3678 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_196_reg_3896 <= tmp_196_fu_1970_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((sR_reg_3678 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_200_reg_3921 <= tmp_200_fu_2046_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((sR_reg_3678 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_201_reg_3926 <= tmp_201_fu_2056_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((small_reg_3811 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        tmp_332_reg_4035 <= tmp_332_fu_3350_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_128_reg_3713 == 1'd0) & (tmp_138_reg_3709 == 1'd0) & (tmp_125_reg_3705 == 1'd0) & (tmp_124_reg_3701 == 1'd0) & (tmp_123_reg_3697 == 1'd0) & (tmp_122_reg_3693 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_phi_mux_p_0_phi_fu_427_p14 = tmp_341_fu_3655_p1;
    end else begin
        ap_phi_mux_p_0_phi_fu_427_p14 = p_0_reg_420;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((tmp_128_fu_659_p2 == 1'd0) & (tmp_138_fu_651_p3 == 1'd0) & (tmp_125_fu_645_p2 == 1'd0) & (tmp_124_fu_639_p2 == 1'd0) & (tmp_123_fu_633_p2 == 1'd0) & (tmp_122_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & ((tmp_122_fu_627_p2 == 1'd1) | ((tmp_123_fu_633_p2 == 1'd1) | ((tmp_124_fu_639_p2 == 1'd1) | ((tmp_125_fu_645_p2 == 1'd1) | ((tmp_128_fu_659_p2 == 1'd1) | (tmp_138_fu_651_p3 == 1'd1)))))))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_range_red_fu_448_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign E0_sub_1_fu_3455_p3 = ((tmp_351_fu_3449_p2[0:0] === 1'b1) ? E0_sub_fu_3441_p3 : 2'd1);

assign E0_sub_fu_3441_p3 = ((tmp_350_fu_3425_p3[0:0] === 1'b1) ? 2'd3 : 2'd2);

assign EFR_fu_3636_p2 = (tmp_514_cast_fu_3613_p1 + tmp_517_cast_fu_3632_p1);

assign E_fu_573_p2 = (tmp_208_cast_fu_563_p4 - tmp_207_cast_fu_559_p1);

assign E_normal_H_2_fu_3271_p3 = ((tmp_299_fu_3265_p2[0:0] === 1'b1) ? tmp_302_reg_4025 : E_normal_H_cast_fu_3261_p1);

assign E_normal_H_cast_fu_3261_p1 = E_normal_H_fu_3255_p2;

assign E_normal_H_fu_3255_p2 = (tmp_297_fu_3242_p7 ^ 6'd1);

assign E_normal_L_cast_fu_2648_p1 = E_normal_L_fu_2642_p2;

assign E_normal_L_fu_2642_p2 = (tmp_247_fu_2629_p7 ^ 6'd1);

assign E_small_fu_3475_p2 = (tmp_492_cast_fu_3471_p1 - lzo_cast_fu_3358_p1);

assign FirstBit_fu_498_p3 = fpX_fu_486_p1[32'd51];

assign Log1p_normal_1_cast_fu_1787_p1 = Log1p_normal_fu_1782_p2;

assign Log1p_normal_fu_1782_p2 = (tmp_250_reg_3838 - tmp_187_fu_1778_p1);

assign LogF_normal_H_2_fu_1956_p3 = ((tmp_267_fu_1942_p3[0:0] === 1'b1) ? tmp_192_fu_1950_p2 : LogF_normal_H_fu_1903_p2);

assign LogF_normal_H_cast_fu_1908_p2 = (tmp_257_reg_3848 + tmp_190_fu_1900_p1);

assign LogF_normal_H_fu_1903_p2 = (tmp_344_cast_fu_1897_p1 + almostLog_H_reg_3817);

assign LogF_normal_L_2_cast_fu_1913_p1 = LogF_normal_L_2_reg_3853;

assign LogF_normal_L_2_fu_1800_p2 = (tmp_251_reg_3843 + tmp_189_fu_1791_p1);

assign LogF_normal_L_fu_1795_p2 = (Log1p_normal_1_cast_fu_1787_p1 + almostLog_L_reg_3822);

assign Log_g_fu_3559_p3 = ((small_reg_3811[0:0] === 1'b1) ? tmp_330_fu_3551_p3 : tmp_332_reg_4035);

assign Log_normal_H_fu_2332_p3 = ((sR_reg_3678[0:0] === 1'b1) ? tmp_200_reg_3921 : tmp_201_reg_3926);

assign Log_normal_L_1_cast_fu_3168_p1 = Log_normal_L_1_reg_3915;

assign Log_normal_L_1_fu_2012_p1 = Log_normal_L_fu_2005_p3[59:0];

assign Log_normal_L_cast_fu_2016_p1 = Log_normal_L_fu_2005_p3;

assign Log_normal_L_fu_2005_p3 = ((sR_reg_3678[0:0] === 1'b1) ? tmp_354_cast_fu_2002_p1 : tmp_353_cast_fu_1999_p1);

assign Log_normal_normd_L_fu_3324_p2 = Log_normal_L_1_cast_fu_3168_p1 << tmp_306_fu_3284_p1;

assign Log_small_1_cast_fu_3421_p1 = Log_small_1_fu_3413_p3;

assign Log_small_1_fu_3413_p3 = {{tmp_316_fu_3403_p4}, {3'd0}};

assign Log_small_fu_3396_p3 = ((sR_reg_3678[0:0] === 1'b1) ? tmp_487_cast_fu_3392_p1 : tmp_313_fu_3378_p2);

assign MAN_IN_1_fu_675_p3 = {{tmp_132_fu_665_p4}, {12'd0}};

assign MAN_IN_fu_683_p2 = (64'd18446744073709547520 ^ MAN_IN_1_fu_675_p3);

assign Y0_fu_536_p3 = ((tmp_135_fu_506_p3[0:0] === 1'b1) ? tmp_203_cast_fu_532_p1 : tmp_s_fu_514_p4);

assign Z2o2_cast_fu_1758_p4 = {{Z2o2_full_fu_1752_p2[53:26]}};

assign Z2o2_full_fu_1752_p0 = squarerIn_1_cast_fu_1749_p1;

assign Z2o2_full_fu_1752_p1 = squarerIn_1_cast_fu_1749_p1;

assign Z2o2_full_fu_1752_p2 = (Z2o2_full_fu_1752_p0 * Z2o2_full_fu_1752_p1);

assign Z2o2_small_cast_fu_3364_p1 = Z2o2_small_reg_3864;

assign Z2o2_small_fu_1835_p3 = ((tmp_311_fu_1813_p2[0:0] === 1'b1) ? 31'd0 : phitmp1_fu_1827_p3);

assign Z_small_cast_fu_3374_p1 = Z_small_fu_3367_p3;

assign Z_small_fu_3367_p3 = {{absZ0s_reg_3827}, {33'd0}};

assign absELog2_H_fu_1979_p2 = (tmp_233_cast_fu_1976_p1 + tmp_231_cast_reg_3870);

assign absELog2_pad_H_cast1_fu_1991_p1 = absELog2_pad_H_fu_1984_p3;

assign absELog2_pad_H_cast_fu_1995_p1 = absELog2_pad_H_fu_1984_p3;

assign absELog2_pad_H_fu_1984_p3 = {{absELog2_H_fu_1979_p2}, {tmp_347_cast_reg_3880}};

assign absELog2_pad_L_cast_fu_1938_p1 = absELog2_pad_L_fu_1930_p3;

assign absELog2_pad_L_fu_1930_p3 = {{tmp_260_fu_1926_p1}, {26'd0}};

assign absE_fu_619_p3 = ((sR_fu_607_p2[0:0] === 1'b1) ? tmp_121_fu_613_p2 : E_fu_573_p2);

assign absZ0_fu_1671_p3 = ((sR_reg_3678[0:0] === 1'b1) ? tmp_180_fu_1666_p2 : tmp_223_reg_3784);

assign absZ0s_fu_1703_p1 = tmp_184_fu_1697_p2[24:0];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_return = ap_phi_mux_p_0_phi_fu_427_p14;

assign doRR_fu_1647_p3 = tmp_175_fu_1643_p1[8'd6];

assign fpX_fu_486_p1 = x;

assign grp_range_red_fu_448_ap_start = grp_range_red_fu_448_ap_start_reg;

assign lzo_1_in_fu_1616_p3 = ((FirstBit_reg_3668[0:0] === 1'b1) ? tmp_162_fu_1543_p7 : tmp_174_fu_1604_p7);

assign lzo_cast1_fu_1629_p1 = lzo_fu_1623_p2;

assign lzo_cast_fu_3358_p1 = lzo_reg_3800;

assign lzo_fu_1623_p2 = (lzo_1_in_fu_1616_p3 ^ 6'd1);

assign m0_fu_1874_p2 = (tmp_230_cast_fu_1870_p1 + tmp_227_cast_fu_1855_p1);

assign m1_fu_3660_p0 = 20'd177;

assign m1_fu_3660_p1 = m1_fu_3660_p10;

assign m1_fu_3660_p10 = absE_reg_3687;

assign newSel1_fu_2164_p3 = ((sel_tmp28_fu_2158_p2[0:0] === 1'b1) ? 6'd20 : 6'd36);

assign newSel236_v_v_fu_1121_p3 = ((p_result_3_fu_917_p2[0:0] === 1'b1) ? p_in79_v_pn_fu_1011_p3 : 6'd60);

assign newSel238_v_fu_1141_p2 = MAN_IN_fu_683_p2 >> newSel238_v_v_cast_fu_1137_p1;

assign newSel238_v_v_cast_fu_1137_p1 = newSel238_v_v_fu_1129_p3;

assign newSel238_v_v_fu_1129_p3 = ((or_cond_fu_1115_p2[0:0] === 1'b1) ? newSel_v_v_fu_1107_p3 : newSel236_v_v_fu_1121_p3);

assign newSel242_cast_cast_fu_2178_p3 = ((tmp_209_fu_2146_p2[0:0] === 1'b1) ? 6'd4 : 6'd52);

assign newSel244_cast_fu_2194_p1 = newSel2_fu_2186_p3;

assign newSel258_cast_fu_3034_p3 = ((tmp_275_fu_2900_p2[0:0] === 1'b1) ? 4'd0 : tmp_280_fu_3024_p4);

assign newSel2_fu_2186_p3 = ((or_cond1_fu_2172_p2[0:0] === 1'b1) ? newSel1_fu_2164_p3 : newSel242_cast_cast_fu_2178_p3);

assign newSel3_fu_3010_p3 = ((sel_tmp43_fu_2924_p2[0:0] === 1'b1) ? 4'd0 : tmp_427_cast_fu_2848_p4);

assign newSel4_fu_3068_p3 = ((or_cond5_fu_3018_p2[0:0] === 1'b1) ? newSel3_fu_3010_p3 : newSel258_cast_fu_3034_p3);

assign newSel_v_v_fu_1107_p3 = ((p_result_5_fu_699_p2[0:0] === 1'b1) ? p_in4_v_cast_fu_1099_p3 : 6'd44);

assign not_tmp_s_fu_601_p2 = ((tmp_120_fu_579_p3 != 63'd4607182418800017408) ? 1'b1 : 1'b0);

assign or_cond1_fu_2172_p2 = (p_result_5_2_fu_2080_p2 ^ p_result_4_2_fu_2130_p2);

assign or_cond2_fu_2810_p2 = (p_result_5_3_fu_2670_p2 ^ p_result_4_3_fu_2708_p2);

assign or_cond3_fu_3004_p2 = (sel_tmp50_fu_2972_p2 | sel_tmp48_fu_2954_p2);

assign or_cond4_fu_3171_p2 = (sel_tmp47_reg_3995 | sel_tmp44_reg_3990);

assign or_cond5_fu_3018_p2 = (sel_tmp43_fu_2924_p2 | sel_tmp41_fu_2912_p2);

assign or_cond6_fu_3175_p2 = (or_cond4_fu_3171_p2 | or_cond3_reg_4000);

assign or_cond_fu_1115_p2 = (sel_tmp8_fu_1093_p2 | sel_tmp6_fu_1075_p2);

assign p_in1_fu_2198_p2 = Log_normal_L_cast_fu_2016_p1 >> newSel244_cast_fu_2194_p1;

assign p_in2_fu_861_p3 = ((p_result_5_1_fu_715_p2[0:0] === 1'b1) ? tmp_246_cast_fu_843_p3 : tmp_247_cast_fu_851_p4);

assign p_in4_v_cast_fu_1099_p3 = ((sel_tmp8_fu_1093_p2[0:0] === 1'b1) ? 6'd28 : 6'd12);

assign p_in5_fu_1003_p3 = ((p_result_5_1_fu_715_p2[0:0] === 1'b1) ? 4'd0 : tmp_258_cast_fu_993_p4);

assign p_in78_v_fu_985_p3 = ((p_result_5_fu_699_p2[0:0] === 1'b1) ? 6'd20 : 6'd52);

assign p_in79_v_fu_977_p3 = ((p_result_5_fu_699_p2[0:0] === 1'b1) ? 6'd4 : 6'd36);

assign p_in79_v_pn_fu_1011_p3 = ((p_result_4_fu_757_p2[0:0] === 1'b1) ? p_in79_v_fu_977_p3 : p_in78_v_fu_985_p3);

assign p_in7_fu_2118_p3 = ((p_result_5_2_fu_2080_p2[0:0] === 1'b1) ? tmp_205_fu_2096_p1 : sf_cast_fu_2114_p1);

assign p_in8_fu_1297_p3 = ((sel_tmp23_fu_1291_p2[0:0] === 1'b1) ? tmp_269_cast_fu_1049_p4 : sel_tmp21_fu_1271_p3);

assign p_in_fu_787_p3 = ((p_result_5_1_fu_715_p2[0:0] === 1'b1) ? st2_fu_763_p4 : tmp_141_cast_fu_783_p1);

assign p_result_1_1_fu_1574_p2 = ((tmp_197_fu_1564_p4 == 2'd0) ? 1'b1 : 1'b0);

assign p_result_1_2_fu_2599_p2 = ((tmp_305_fu_2589_p4 == 2'd0) ? 1'b1 : 1'b0);

assign p_result_1_3_fu_3212_p2 = ((tmp_340_fu_3202_p4 == 2'd0) ? 1'b1 : 1'b0);

assign p_result_1_fu_1513_p2 = ((tmp_191_fu_1503_p4 == 2'd0) ? 1'b1 : 1'b0);

assign p_result_2_1_fu_1305_p2 = ((p_in8_fu_1297_p3 == 4'd0) ? 1'b1 : 1'b0);

assign p_result_2_2_fu_2477_p2 = ((tmp_229_fu_2469_p3 == 4'd0) ? 1'b1 : 1'b0);

assign p_result_2_3_fu_3186_p2 = ((tmp_285_fu_3180_p3 == 4'd0) ? 1'b1 : 1'b0);

assign p_result_2_fu_1151_p2 = ((tmp_177_fu_1147_p1 == 4'd0) ? 1'b1 : 1'b0);

assign p_result_3_1_fu_971_p2 = ((tmp_147_fu_963_p3 == 8'd0) ? 1'b1 : 1'b0);

assign p_result_3_2_fu_2208_p2 = ((tmp_300_fu_2204_p1 == 8'd0) ? 1'b1 : 1'b0);

assign p_result_3_3_fu_2842_p2 = ((tmp_269_fu_2834_p3 == 8'd0) ? 1'b1 : 1'b0);

assign p_result_3_fu_917_p2 = ((tmp_143_fu_909_p3 == 8'd0) ? 1'b1 : 1'b0);

assign p_result_4_1_fu_799_p2 = ((tmp_176_fu_795_p1 == 16'd0) ? 1'b1 : 1'b0);

assign p_result_4_2_fu_2130_p2 = ((tmp_298_fu_2126_p1 == 16'd0) ? 1'b1 : 1'b0);

assign p_result_4_3_fu_2708_p2 = ((tmp_326_fu_2704_p1 == 16'd0) ? 1'b1 : 1'b0);

assign p_result_4_fu_757_p2 = ((tmp_164_fu_753_p1 == 16'd0) ? 1'b1 : 1'b0);

assign p_result_5_1_fu_715_p2 = ((tmp_151_fu_705_p4 == 32'd0) ? 1'b1 : 1'b0);

assign p_result_5_2_fu_2080_p2 = ((tmp_203_fu_2072_p3 == 60'd0) ? 1'b1 : 1'b0);

assign p_result_5_3_fu_2670_p2 = ((tmp_249_fu_2662_p3 == 34'd0) ? 1'b1 : 1'b0);

assign p_result_5_fu_699_p2 = ((tmp_141_fu_689_p4 == 32'd0) ? 1'b1 : 1'b0);

assign p_v1_fu_2696_p3 = ((p_result_5_3_fu_2670_p2[0:0] === 1'b1) ? tmp_323_fu_2676_p2 : tmp_253_fu_2692_p1);

assign p_v_fu_745_p3 = ((p_result_5_fu_699_p2[0:0] === 1'b1) ? st1_fu_721_p4 : tmp_138_cast_fu_741_p1);

assign p_val8_1_fu_1497_p3 = ((p_result_2_reg_3747[0:0] === 1'b1) ? p_val8_reg_3759 : tmp_160_fu_1494_p1);

assign p_val8_2_fu_1445_p3 = ((sel_tmp23_fu_1291_p2[0:0] === 1'b1) ? tmp_146_fu_953_p4 : tmp_170_fu_1437_p3);

assign p_val8_3_fu_1558_p3 = ((p_result_2_1_reg_3753[0:0] === 1'b1) ? p_val8_2_reg_3769 : tmp_172_fu_1555_p1);

assign p_val8_4_fu_2559_p3 = ((sel_tmp37_fu_2388_p2[0:0] === 1'b1) ? tmp_243_fu_2550_p4 : tmp_242_fu_2542_p3);

assign p_val8_5_fu_2581_p3 = ((p_result_2_2_fu_2477_p2[0:0] === 1'b1) ? p_val8_4_fu_2559_p3 : tmp_245_fu_2577_p1);

assign p_val8_6_fu_3144_p3 = ((sel_tmp50_fu_2972_p2[0:0] === 1'b1) ? tmp_263_fu_2784_p3 : tmp_293_fu_3136_p3);

assign p_val8_7_fu_3195_p3 = ((p_result_2_3_fu_3186_p2[0:0] === 1'b1) ? p_val8_6_reg_4015 : tmp_295_fu_3192_p1);

assign p_val8_fu_1375_p3 = ((sel_tmp8_fu_1093_p2[0:0] === 1'b1) ? tmp_248_cast_fu_869_p4 : sel_tmp25_fu_1367_p3);

assign phitmp1_fu_1827_p3 = {{tmp_312_fu_1821_p2}, {3'd0}};

assign phitmp_fu_595_p2 = (tmp_137_fu_587_p3 ^ 1'd1);

assign res_fp_fu_3649_p2 = (tmp_339_fu_3642_p3 | EFR_fu_3636_p2);

assign sR_fu_607_p2 = (phitmp_fu_595_p2 & not_tmp_s_fu_601_p2);

assign sel_tmp10_fu_1199_p2 = (sel_tmp3_fu_941_p2 & p_result_3_1_fu_971_p2);

assign sel_tmp11_fu_1205_p2 = (sel_tmp10_fu_1199_p2 & p_result_5_1_fu_715_p2);

assign sel_tmp121_demorgan_fu_2378_p2 = (p_result_4_2_reg_3940 | p_result_3_2_reg_3952);

assign sel_tmp12_fu_1211_p3 = ((sel_tmp11_fu_1205_p2[0:0] === 1'b1) ? tmp_264_cast_fu_1019_p4 : sel_tmp9_fu_1191_p3);

assign sel_tmp13_fu_1219_p2 = (p_result_5_1_fu_715_p2 ^ 1'd1);

assign sel_tmp14_fu_1225_p2 = (sel_tmp13_fu_1219_p2 & sel_tmp10_fu_1199_p2);

assign sel_tmp15_fu_1231_p3 = ((sel_tmp14_fu_1225_p2[0:0] === 1'b1) ? tmp_265_cast_fu_1029_p4 : sel_tmp12_fu_1211_p3);

assign sel_tmp16_fu_1239_p2 = (p_result_3_1_fu_971_p2 ^ 1'd1);

assign sel_tmp17_fu_1245_p2 = (sel_tmp16_fu_1239_p2 & p_result_4_1_fu_799_p2);

assign sel_tmp185_demorgan_fu_2960_p2 = (p_result_4_3_fu_2708_p2 | p_result_3_3_fu_2842_p2);

assign sel_tmp18_fu_1251_p2 = (sel_tmp17_fu_1245_p2 & p_result_5_1_fu_715_p2);

assign sel_tmp19_fu_1257_p3 = ((sel_tmp18_fu_1251_p2[0:0] === 1'b1) ? tmp_142_fu_833_p4 : sel_tmp15_fu_1231_p3);

assign sel_tmp1_fu_897_p2 = (p_result_4_fu_757_p2 ^ 1'd1);

assign sel_tmp20_fu_1265_p2 = (sel_tmp17_fu_1245_p2 & sel_tmp13_fu_1219_p2);

assign sel_tmp21_fu_1271_p3 = ((sel_tmp20_fu_1265_p2[0:0] === 1'b1) ? tmp_268_cast_fu_1039_p4 : sel_tmp19_fu_1257_p3);

assign sel_tmp22_fu_1285_p2 = (sel_tmp55_demorgan_fu_1279_p2 ^ 1'd1);

assign sel_tmp23_fu_1291_p2 = (sel_tmp22_fu_1285_p2 & p_result_5_1_fu_715_p2);

assign sel_tmp24_fu_1359_p3 = ((p_result_3_fu_917_p2[0:0] === 1'b1) ? tmp_157_fu_1351_p3 : tmp_250_cast_fu_879_p4);

assign sel_tmp25_fu_1367_p3 = ((sel_tmp6_fu_1075_p2[0:0] === 1'b1) ? tmp_136_fu_825_p3 : sel_tmp24_fu_1359_p3);

assign sel_tmp26_fu_2337_p2 = (p_result_5_2_reg_3931 ^ 1'd1);

assign sel_tmp27_fu_2152_p2 = (p_result_4_2_fu_2130_p2 ^ 1'd1);

assign sel_tmp28_fu_2158_p2 = (sel_tmp27_fu_2152_p2 & p_result_5_2_fu_2080_p2);

assign sel_tmp29_fu_2342_p2 = (sel_tmp27_reg_3947 & p_result_3_2_reg_3952);

assign sel_tmp2_fu_903_p2 = (sel_tmp1_fu_897_p2 & p_result_5_fu_699_p2);

assign sel_tmp30_demorgan_fu_1081_p2 = (p_result_4_fu_757_p2 | p_result_3_fu_917_p2);

assign sel_tmp30_fu_2346_p2 = (sel_tmp29_fu_2342_p2 & p_result_5_2_reg_3931);

assign sel_tmp31_fu_2351_p2 = (sel_tmp29_fu_2342_p2 & sel_tmp26_fu_2337_p2);

assign sel_tmp32_fu_2357_p2 = (p_result_3_2_reg_3952 ^ 1'd1);

assign sel_tmp33_fu_2362_p2 = (sel_tmp32_fu_2357_p2 & p_result_4_2_reg_3940);

assign sel_tmp34_fu_2367_p2 = (sel_tmp33_fu_2362_p2 & p_result_5_2_reg_3931);

assign sel_tmp35_fu_2372_p2 = (sel_tmp33_fu_2362_p2 & sel_tmp26_fu_2337_p2);

assign sel_tmp36_fu_2382_p2 = (sel_tmp121_demorgan_fu_2378_p2 ^ 1'd1);

assign sel_tmp37_fu_2388_p2 = (sel_tmp36_fu_2382_p2 & p_result_5_2_reg_3931);

assign sel_tmp38_fu_2762_p2 = (p_result_5_3_fu_2670_p2 ^ 1'd1);

assign sel_tmp39_fu_2768_p2 = (p_result_4_3_fu_2708_p2 ^ 1'd1);

assign sel_tmp3_fu_941_p2 = (p_result_4_1_fu_799_p2 ^ 1'd1);

assign sel_tmp40_fu_2774_p2 = (sel_tmp39_fu_2768_p2 & p_result_5_3_fu_2670_p2);

assign sel_tmp41_fu_2912_p2 = (tmp_276_fu_2906_p2 & sel_tmp38_fu_2762_p2);

assign sel_tmp42_fu_2918_p2 = (sel_tmp39_fu_2768_p2 & p_result_3_3_fu_2842_p2);

assign sel_tmp43_fu_2924_p2 = (sel_tmp42_fu_2918_p2 & p_result_5_3_fu_2670_p2);

assign sel_tmp44_fu_2930_p2 = (sel_tmp42_fu_2918_p2 & sel_tmp38_fu_2762_p2);

assign sel_tmp45_fu_2936_p2 = (p_result_3_3_fu_2842_p2 ^ 1'd1);

assign sel_tmp46_fu_2942_p2 = (sel_tmp45_fu_2936_p2 & p_result_4_3_fu_2708_p2);

assign sel_tmp47_fu_2948_p2 = (sel_tmp46_fu_2942_p2 & p_result_5_3_fu_2670_p2);

assign sel_tmp48_fu_2954_p2 = (sel_tmp46_fu_2942_p2 & sel_tmp38_fu_2762_p2);

assign sel_tmp49_fu_2966_p2 = (sel_tmp185_demorgan_fu_2960_p2 ^ 1'd1);

assign sel_tmp4_fu_947_p2 = (sel_tmp3_fu_941_p2 & p_result_5_1_fu_715_p2);

assign sel_tmp50_fu_2972_p2 = (sel_tmp49_fu_2966_p2 & p_result_5_3_fu_2670_p2);

assign sel_tmp55_demorgan_fu_1279_p2 = (p_result_4_1_fu_799_p2 | p_result_3_1_fu_971_p2);

assign sel_tmp5_fu_1069_p2 = (p_result_3_fu_917_p2 ^ 1'd1);

assign sel_tmp6_fu_1075_p2 = (sel_tmp5_fu_1069_p2 & p_result_4_fu_757_p2);

assign sel_tmp7_fu_1087_p2 = (sel_tmp30_demorgan_fu_1081_p2 ^ 1'd1);

assign sel_tmp8_fu_1093_p2 = (sel_tmp7_fu_1087_p2 & p_result_5_fu_699_p2);

assign sel_tmp9_fu_1191_p3 = ((tmp_152_fu_1185_p2[0:0] === 1'b1) ? p_in5_fu_1003_p3 : tmp_271_cast_fu_1059_p4);

assign sel_tmp_fu_889_p3 = ((p_result_4_fu_757_p2[0:0] === 1'b1) ? tmp_136_fu_825_p3 : tmp_250_cast_fu_879_p4);

assign sf_cast_fu_2114_p1 = $unsigned(tmp_207_fu_2110_p1);

assign shiftval_cast_fu_1639_p1 = shiftval_fu_1633_p2;

assign shiftval_fu_1633_p2 = ($signed(7'd100) + $signed(lzo_cast1_fu_1629_p1));

assign small_fu_1661_p2 = (tmp_179_fu_1655_p2 & tmp_178_reg_3779);

assign squarerIn_1_cast_fu_1749_p1 = squarerIn_reg_3833;

assign squarerIn_fu_1729_p3 = ((doRR_fu_1647_p3[0:0] === 1'b1) ? tmp_338_cast_fu_1707_p4 : tmp_341_cast_fu_1725_p1);

assign st1_fu_721_p4 = {{MAN_IN_fu_683_p2[63:16]}};

assign st2_fu_763_p4 = {{Y0_fu_536_p3[53:5]}};

assign sticky_fu_3569_p2 = ((tmp_355_fu_3565_p1 != 4'd0) ? 1'b1 : 1'b0);

assign tmp198_fu_2051_p2 = (absELog2_pad_H_cast1_fu_1991_p1 + LogF_normal_H_2_reg_3885);

assign tmp_117_fu_524_p3 = {{1'd1}, {tmp_130_fu_494_p1}};

assign tmp_118_fu_545_p2 = (1'd1 ^ FirstBit_fu_498_p3);

assign tmp_119_fu_551_p3 = {{9'd511}, {tmp_118_fu_545_p2}};

assign tmp_120_fu_579_p3 = {{tmp_208_cast_fu_563_p4}, {52'd0}};

assign tmp_121_fu_613_p2 = (11'd0 - E_fu_573_p2);

assign tmp_122_fu_627_p2 = ((tmp_fu_490_p1 == 63'd0) ? 1'b1 : 1'b0);

assign tmp_123_fu_633_p2 = ((fpX_fu_486_p1 == 64'd9218868437227405312) ? 1'b1 : 1'b0);

assign tmp_124_fu_639_p2 = ((fpX_fu_486_p1 == 64'd18442240474082181120) ? 1'b1 : 1'b0);

assign tmp_125_fu_645_p2 = ((E_fu_573_p2 == 11'd2047) ? 1'b1 : 1'b0);

assign tmp_126_fu_1484_p2 = (fpX_fu_486_p1 | 64'd9221120237041090560);

assign tmp_127_fu_1490_p1 = tmp_126_fu_1484_p2;

assign tmp_128_fu_659_p2 = ((fpX_fu_486_p1 == 64'd4607182418800017408) ? 1'b1 : 1'b0);

assign tmp_129_fu_1849_p1 = tmp_129_fu_1849_p10;

assign tmp_129_fu_1849_p10 = absE_reg_3687;

assign tmp_129_fu_1849_p2 = (59'd250894535073523 * tmp_129_fu_1849_p1);

assign tmp_130_fu_494_p1 = fpX_fu_486_p1[51:0];

assign tmp_131_fu_1862_p3 = {{tmp_139_fu_1859_p1}, {49'd0}};

assign tmp_132_fu_665_p4 = {{Y0_fu_536_p3[52:1]}};

assign tmp_133_fu_805_p4 = {{MAN_IN_fu_683_p2[15:8]}};

assign tmp_134_fu_815_p4 = {{MAN_IN_fu_683_p2[47:40]}};

assign tmp_135_fu_506_p3 = fpX_fu_486_p1[32'd51];

assign tmp_136_fu_825_p3 = ((p_result_5_fu_699_p2[0:0] === 1'b1) ? tmp_133_fu_805_p4 : tmp_134_fu_815_p4);

assign tmp_137_fu_587_p3 = fpX_fu_486_p1[32'd62];

assign tmp_138_cast_fu_741_p1 = tmp_158_fu_731_p4;

assign tmp_138_fu_651_p3 = fpX_fu_486_p1[32'd63];

assign tmp_139_fu_1859_p1 = m1_fu_3660_p2[10:0];

assign tmp_141_cast_fu_783_p1 = tmp_165_fu_773_p4;

assign tmp_141_fu_689_p4 = {{MAN_IN_fu_683_p2[63:32]}};

assign tmp_142_fu_833_p4 = {{Y0_fu_536_p3[4:1]}};

assign tmp_143_fu_909_p3 = ((sel_tmp2_fu_903_p2[0:0] === 1'b1) ? tmp_248_cast_fu_869_p4 : sel_tmp_fu_889_p3);

assign tmp_144_fu_923_p4 = {{Y0_fu_536_p3[52:45]}};

assign tmp_145_fu_933_p3 = ((p_result_4_1_fu_799_p2[0:0] === 1'b1) ? p_in2_fu_861_p3 : tmp_144_fu_923_p4);

assign tmp_146_fu_953_p4 = {{Y0_fu_536_p3[20:13]}};

assign tmp_147_fu_963_p3 = ((sel_tmp4_fu_947_p2[0:0] === 1'b1) ? tmp_146_fu_953_p4 : tmp_145_fu_933_p3);

assign tmp_148_fu_1161_p2 = (tmp_183_fu_1157_p1 | tmp_147_fu_963_p3);

assign tmp_149_fu_1167_p4 = {{p_in_fu_787_p3[15:8]}};

assign tmp_150_fu_1177_p3 = {{tmp_149_fu_1167_p4}, {tmp_148_fu_1161_p2}};

assign tmp_151_fu_705_p4 = {{Y0_fu_536_p3[52:21]}};

assign tmp_152_fu_1185_p2 = ((tmp_150_fu_1177_p3 == 16'd0) ? 1'b1 : 1'b0);

assign tmp_153_fu_1311_p4 = {{MAN_IN_fu_683_p2[39:32]}};

assign tmp_154_fu_1321_p3 = ((p_result_5_fu_699_p2[0:0] === 1'b1) ? 8'd0 : tmp_153_fu_1311_p4);

assign tmp_155_fu_1333_p4 = {{Y0_fu_536_p3[28:21]}};

assign tmp_156_fu_1343_p3 = ((p_result_5_1_fu_715_p2[0:0] === 1'b1) ? 8'd0 : tmp_155_fu_1333_p4);

assign tmp_157_fu_1351_p3 = ((p_result_4_fu_757_p2[0:0] === 1'b1) ? tmp_154_fu_1321_p3 : tmp_188_fu_1329_p1);

assign tmp_158_fu_731_p4 = {{MAN_IN_fu_683_p2[63:48]}};

assign tmp_160_fu_1494_p1 = tmp_159_reg_3764;

assign tmp_161_fu_1535_p3 = ((p_result_1_fu_1513_p2[0:0] === 1'b1) ? tmp_193_fu_1519_p3 : tmp_195_fu_1527_p3);

assign tmp_162_fu_1543_p7 = {{{{{{p_result_5_reg_3717}, {p_result_4_reg_3727}}, {p_result_3_reg_3737}}, {p_result_2_reg_3747}}, {p_result_1_fu_1513_p2}}, {tmp_161_fu_1535_p3}};

assign tmp_163_fu_1393_p3 = ((tmp_152_fu_1185_p2[0:0] === 1'b1) ? tmp_156_fu_1343_p3 : tmp_144_fu_923_p4);

assign tmp_164_fu_753_p1 = p_v_fu_745_p3[15:0];

assign tmp_165_fu_773_p4 = {{Y0_fu_536_p3[53:37]}};

assign tmp_166_fu_1401_p4 = {{Y0_fu_536_p3[12:5]}};

assign tmp_167_fu_1411_p3 = ((sel_tmp11_fu_1205_p2[0:0] === 1'b1) ? tmp_166_fu_1401_p4 : tmp_163_fu_1393_p3);

assign tmp_168_fu_1419_p4 = {{Y0_fu_536_p3[44:37]}};

assign tmp_169_fu_1429_p3 = ((sel_tmp14_fu_1225_p2[0:0] === 1'b1) ? tmp_168_fu_1419_p4 : tmp_167_fu_1411_p3);

assign tmp_170_fu_1437_p3 = ((sel_tmp17_fu_1245_p2[0:0] === 1'b1) ? p_in2_fu_861_p3 : tmp_169_fu_1429_p3);

assign tmp_172_fu_1555_p1 = tmp_171_reg_3774;

assign tmp_173_fu_1596_p3 = ((p_result_1_1_fu_1574_p2[0:0] === 1'b1) ? tmp_198_fu_1580_p3 : tmp_213_fu_1588_p3);

assign tmp_174_fu_1604_p7 = {{{{{{p_result_5_1_reg_3722}, {p_result_4_1_reg_3732}}, {p_result_3_1_reg_3742}}, {p_result_2_1_reg_3753}}, {p_result_1_1_fu_1574_p2}}, {tmp_173_fu_1596_p3}};

assign tmp_175_fu_1643_p1 = $unsigned(shiftval_cast_fu_1639_p1);

assign tmp_176_fu_795_p1 = p_in_fu_787_p3[15:0];

assign tmp_177_fu_1147_p1 = newSel238_v_fu_1141_p2[3:0];

assign tmp_178_fu_1463_p2 = ((tmp_208_cast_fu_563_p4 == tmp_207_cast_fu_559_p1) ? 1'b1 : 1'b0);

assign tmp_179_fu_1655_p2 = (doRR_fu_1647_p3 ^ 1'd1);

assign tmp_180_fu_1666_p2 = (26'd0 - tmp_223_reg_3784);

assign tmp_181_fu_1689_p1 = absZ0_fu_1671_p3;

assign tmp_182_fu_1693_p1 = $unsigned(shiftval_fu_1633_p2);

assign tmp_183_fu_1157_p1 = p_in_fu_787_p3[7:0];

assign tmp_184_fu_1697_p2 = tmp_181_fu_1689_p1 << tmp_182_fu_1693_p1;

assign tmp_185_fu_1717_p3 = {{absZ0s_fu_1703_p1}, {1'd0}};

assign tmp_186_fu_1768_p4 = {{Z2o2_full_fu_1752_p2[53:28]}};

assign tmp_187_fu_1778_p1 = tmp_186_fu_1768_p4;

assign tmp_188_fu_1329_p1 = p_v_fu_745_p3[7:0];

assign tmp_189_fu_1791_p1 = Log1p_normal_fu_1782_p2;

assign tmp_190_fu_1900_p1 = tmp_256_reg_3858;

assign tmp_191_fu_1503_p4 = {{p_val8_1_fu_1497_p3[3:2]}};

assign tmp_192_fu_1950_p2 = (64'd17171480576 | LogF_normal_H_fu_1903_p2);

assign tmp_193_fu_1519_p3 = p_val8_1_fu_1497_p3[32'd1];

assign tmp_194_fu_1964_p2 = (LogF_normal_L_2_cast_fu_1913_p1 + absELog2_pad_L_cast_fu_1938_p1);

assign tmp_195_fu_1527_p3 = p_val8_1_fu_1497_p3[32'd3];

assign tmp_196_fu_1970_p2 = (absELog2_pad_L_cast_fu_1938_p1 - LogF_normal_L_2_cast_fu_1913_p1);

assign tmp_197_fu_1564_p4 = {{p_val8_3_fu_1558_p3[3:2]}};

assign tmp_198_fu_1580_p3 = p_val8_3_fu_1558_p3[32'd1];

assign tmp_199_fu_2036_p2 = (absELog2_pad_H_cast_fu_1995_p1 - tmp_356_cast_fu_2032_p1);

assign tmp_200_fu_2046_p2 = ($signed(tmp_357_cast_fu_2042_p1) - $signed(LogF_normal_H_2_reg_3885));

assign tmp_201_fu_2056_p2 = (tmp198_fu_2051_p2 + tmp_356_cast1_fu_2028_p1);

assign tmp_202_fu_2062_p4 = {{Log_normal_L_fu_2005_p3[59:28]}};

assign tmp_203_cast_fu_532_p1 = tmp_117_fu_524_p3;

assign tmp_203_fu_2072_p3 = {{tmp_202_fu_2062_p4}, {28'd0}};

assign tmp_204_fu_2086_p4 = {{Log_normal_L_fu_2005_p3[61:12]}};

assign tmp_205_fu_2096_p1 = $signed(tmp_204_fu_2086_p4);

assign tmp_206_fu_2100_p4 = {{Log_normal_L_fu_2005_p3[61:44]}};

assign tmp_207_cast_fu_559_p1 = tmp_119_fu_551_p3;

assign tmp_207_fu_2110_p1 = $signed(tmp_206_fu_2100_p4);

assign tmp_208_cast_fu_563_p4 = {{fpX_fu_486_p1[62:52]}};

assign tmp_208_fu_2136_p4 = {{{tmp_202_fu_2062_p4}, {12'd0}}, {tmp_298_fu_2126_p1}};

assign tmp_209_fu_2146_p2 = ((tmp_208_fu_2136_p4 == 60'd0) ? 1'b1 : 1'b0);

assign tmp_210_fu_2218_p2 = (tmp_301_fu_2214_p1 | tmp_300_fu_2204_p1);

assign tmp_211_fu_2224_p4 = {{p_in7_fu_2118_p3[15:8]}};

assign tmp_212_fu_2234_p3 = {{tmp_211_fu_2224_p4}, {tmp_210_fu_2218_p2}};

assign tmp_213_fu_1588_p3 = p_val8_3_fu_1558_p3[32'd3];

assign tmp_214_fu_2242_p2 = ((tmp_212_fu_2234_p3 == 16'd0) ? 1'b1 : 1'b0);

assign tmp_215_fu_2393_p4 = {{Log_normal_L_reg_3901[27:24]}};

assign tmp_216_fu_2402_p4 = {{Log_normal_L_reg_3901[43:40]}};

assign tmp_217_fu_2411_p4 = {{Log_normal_L_reg_3901[11:8]}};

assign tmp_218_fu_2420_p4 = {{Log_normal_L_reg_3901[51:48]}};

assign tmp_219_fu_2429_p4 = {{Log_normal_L_reg_3901[19:16]}};

assign tmp_220_fu_2252_p4 = {{Log_normal_L_fu_2005_p3[35:32]}};

assign tmp_221_fu_2262_p3 = ((p_result_5_2_fu_2080_p2[0:0] === 1'b1) ? tmp_304_fu_2248_p1 : tmp_220_fu_2252_p4);

assign tmp_222_fu_2270_p4 = {{Log_normal_L_fu_2005_p3[59:56]}};

assign tmp_223_fu_1469_p1 = Y0_fu_536_p3[25:0];

assign tmp_224_fu_2280_p3 = ((tmp_214_fu_2242_p2[0:0] === 1'b1) ? tmp_221_fu_2262_p3 : tmp_222_fu_2270_p4);

assign tmp_225_fu_2438_p3 = ((sel_tmp30_fu_2346_p2[0:0] === 1'b1) ? tmp_219_fu_2429_p4 : tmp_224_reg_3960);

assign tmp_226_fu_2445_p3 = ((sel_tmp31_fu_2351_p2[0:0] === 1'b1) ? tmp_218_fu_2420_p4 : tmp_225_fu_2438_p3);

assign tmp_227_cast_fu_1855_p1 = tmp_129_fu_1849_p2;

assign tmp_227_fu_2453_p3 = ((sel_tmp34_fu_2367_p2[0:0] === 1'b1) ? tmp_217_fu_2411_p4 : tmp_226_fu_2445_p3);

assign tmp_228_fu_2461_p3 = ((sel_tmp35_fu_2372_p2[0:0] === 1'b1) ? tmp_216_fu_2402_p4 : tmp_227_fu_2453_p3);

assign tmp_229_fu_2469_p3 = ((sel_tmp37_fu_2388_p2[0:0] === 1'b1) ? tmp_215_fu_2393_p4 : tmp_228_fu_2461_p3);

assign tmp_230_cast_fu_1870_p1 = tmp_131_fu_1862_p3;

assign tmp_230_fu_2288_p3 = {{tmp_304_fu_2248_p1}, {4'd0}};

assign tmp_231_fu_2296_p4 = {{Log_normal_L_fu_2005_p3[35:28]}};

assign tmp_232_fu_2306_p3 = ((p_result_5_2_fu_2080_p2[0:0] === 1'b1) ? tmp_230_fu_2288_p3 : tmp_231_fu_2296_p4);

assign tmp_233_cast_fu_1976_p1 = tmp_140_reg_3875;

assign tmp_233_fu_2314_p4 = {{Log_normal_L_fu_2005_p3[59:52]}};

assign tmp_234_fu_2324_p3 = ((tmp_214_fu_2242_p2[0:0] === 1'b1) ? tmp_232_fu_2306_p3 : tmp_233_fu_2314_p4);

assign tmp_235_fu_2483_p4 = {{Log_normal_L_reg_3901[19:12]}};

assign tmp_236_fu_2492_p3 = ((sel_tmp30_fu_2346_p2[0:0] === 1'b1) ? tmp_235_fu_2483_p4 : tmp_234_reg_3965);

assign tmp_237_fu_2499_p4 = {{Log_normal_L_reg_3901[51:44]}};

assign tmp_238_fu_2508_p3 = ((sel_tmp31_fu_2351_p2[0:0] === 1'b1) ? tmp_237_fu_2499_p4 : tmp_236_fu_2492_p3);

assign tmp_239_fu_2516_p4 = {{Log_normal_L_reg_3901[11:4]}};

assign tmp_240_fu_2525_p3 = ((sel_tmp34_fu_2367_p2[0:0] === 1'b1) ? tmp_239_fu_2516_p4 : tmp_238_fu_2508_p3);

assign tmp_241_fu_2533_p4 = {{Log_normal_L_reg_3901[43:36]}};

assign tmp_242_fu_2542_p3 = ((sel_tmp35_fu_2372_p2[0:0] === 1'b1) ? tmp_241_fu_2533_p4 : tmp_240_fu_2525_p3);

assign tmp_243_fu_2550_p4 = {{Log_normal_L_reg_3901[27:20]}};

assign tmp_244_fu_2567_p4 = {{p_val8_4_fu_2559_p3[7:4]}};

assign tmp_245_fu_2577_p1 = tmp_244_fu_2567_p4;

assign tmp_246_cast_fu_843_p3 = {{tmp_142_fu_833_p4}, {4'd0}};

assign tmp_246_fu_2621_p3 = ((p_result_1_2_fu_2599_p2[0:0] === 1'b1) ? tmp_315_fu_2605_p3 : tmp_319_fu_2613_p3);

assign tmp_247_cast_fu_851_p4 = {{Y0_fu_536_p3[36:29]}};

assign tmp_247_fu_2629_p7 = {{{{{{p_result_5_2_reg_3931}, {p_result_4_2_reg_3940}}, {p_result_3_2_reg_3952}}, {p_result_2_2_fu_2477_p2}}, {p_result_1_2_fu_2599_p2}}, {tmp_246_fu_2621_p3}};

assign tmp_248_cast_fu_869_p4 = {{MAN_IN_fu_683_p2[31:24]}};

assign tmp_248_fu_2652_p4 = {{Log_normal_H_fu_2332_p3[33:2]}};

assign tmp_249_fu_2662_p3 = {{tmp_248_fu_2652_p4}, {2'd0}};

assign tmp_250_cast_fu_879_p4 = {{MAN_IN_fu_683_p2[63:56]}};

assign tmp_250_fu_1737_p1 = grp_range_red_fu_448_ap_return_0[54:0];

assign tmp_251_fu_1741_p1 = grp_range_red_fu_448_ap_return_2[59:0];

assign tmp_252_fu_2682_p4 = {{Log_normal_H_fu_2332_p3[63:18]}};

assign tmp_253_fu_2692_p1 = tmp_252_fu_2682_p4;

assign tmp_254_fu_2714_p4 = {{Log_normal_H_fu_2332_p3[15:2]}};

assign tmp_255_fu_2724_p3 = {{tmp_254_fu_2714_p4}, {2'd0}};

assign tmp_257_fu_1745_p1 = grp_range_red_fu_448_ap_return_1[22:0];

assign tmp_258_cast_fu_993_p4 = {{Y0_fu_536_p3[28:25]}};

assign tmp_258_fu_2732_p2 = (tmp_326_fu_2704_p1 | tmp_255_fu_2724_p3);

assign tmp_259_fu_2738_p4 = {{Log_normal_H_fu_2332_p3[33:16]}};

assign tmp_260_fu_1926_p1 = tmp_129_fu_1849_p2[33:0];

assign tmp_261_fu_2748_p3 = {{tmp_259_fu_2738_p4}, {tmp_258_fu_2732_p2}};

assign tmp_262_fu_2756_p2 = ((tmp_261_fu_2748_p3 == 34'd0) ? 1'b1 : 1'b0);

assign tmp_263_fu_2784_p3 = {{tmp_328_fu_2780_p1}, {6'd0}};

assign tmp_264_cast_fu_1019_p4 = {{Y0_fu_536_p3[12:9]}};

assign tmp_264_fu_2792_p4 = {{Log_normal_H_fu_2332_p3[17:10]}};

assign tmp_265_cast_fu_1029_p4 = {{Y0_fu_536_p3[44:41]}};

assign tmp_265_fu_2802_p3 = ((sel_tmp40_fu_2774_p2[0:0] === 1'b1) ? tmp_263_fu_2784_p3 : tmp_264_fu_2792_p4);

assign tmp_266_fu_2816_p4 = {{Log_normal_H_fu_2332_p3[33:26]}};

assign tmp_267_fu_1942_p3 = LogF_normal_H_cast_fu_1908_p2[32'd22];

assign tmp_268_cast_fu_1039_p4 = {{Y0_fu_536_p3[36:33]}};

assign tmp_268_fu_2826_p3 = ((tmp_262_fu_2756_p2[0:0] === 1'b1) ? 8'd0 : tmp_266_fu_2816_p4);

assign tmp_269_cast_fu_1049_p4 = {{Y0_fu_536_p3[20:17]}};

assign tmp_269_fu_2834_p3 = ((or_cond2_fu_2810_p2[0:0] === 1'b1) ? tmp_265_fu_2802_p3 : tmp_268_fu_2826_p3);

assign tmp_270_fu_2862_p2 = (tmp_336_fu_2858_p1 | tmp_269_fu_2834_p3);

assign tmp_271_cast_fu_1059_p4 = {{Y0_fu_536_p3[52:49]}};

assign tmp_271_fu_2868_p4 = {{p_v1_fu_2696_p3[15:8]}};

assign tmp_272_fu_2878_p3 = {{tmp_271_fu_2868_p4}, {tmp_270_fu_2862_p2}};

assign tmp_273_fu_2886_p2 = (tmp_272_fu_2878_p3 | tmp_255_fu_2724_p3);

assign tmp_274_fu_2892_p3 = {{tmp_259_fu_2738_p4}, {tmp_273_fu_2886_p2}};

assign tmp_275_fu_2900_p2 = ((tmp_274_fu_2892_p3 == 34'd0) ? 1'b1 : 1'b0);

assign tmp_276_fu_2906_p2 = ((tmp_272_fu_2878_p3 == 16'd0) ? 1'b1 : 1'b0);

assign tmp_277_fu_2978_p3 = {{tmp_328_fu_2780_p1}, {2'd0}};

assign tmp_278_fu_2986_p4 = {{Log_normal_H_fu_2332_p3[17:14]}};

assign tmp_279_fu_2996_p3 = ((sel_tmp50_fu_2972_p2[0:0] === 1'b1) ? tmp_277_fu_2978_p3 : tmp_278_fu_2986_p4);

assign tmp_280_fu_3024_p4 = {{Log_normal_H_fu_2332_p3[33:30]}};

assign tmp_281_fu_3042_p4 = {{Log_normal_H_fu_2332_p3[25:22]}};

assign tmp_282_fu_2020_p3 = Log_normal_L_fu_2005_p3[32'd60];

assign tmp_283_fu_3052_p3 = ((sel_tmp47_fu_2948_p2[0:0] === 1'b1) ? 4'd0 : tmp_281_fu_3042_p4);

assign tmp_284_fu_3060_p3 = ((or_cond3_fu_3004_p2[0:0] === 1'b1) ? tmp_279_fu_2996_p3 : tmp_283_fu_3052_p3);

assign tmp_285_fu_3180_p3 = ((or_cond6_fu_3175_p2[0:0] === 1'b1) ? tmp_284_reg_4005 : newSel4_reg_4010);

assign tmp_286_fu_3076_p4 = {{Log_normal_H_fu_2332_p3[9:2]}};

assign tmp_287_fu_3086_p3 = ((p_result_5_3_fu_2670_p2[0:0] === 1'b1) ? 8'd0 : tmp_286_fu_3076_p4);

assign tmp_288_fu_3094_p3 = ((tmp_276_fu_2906_p2[0:0] === 1'b1) ? tmp_287_fu_3086_p3 : tmp_266_fu_2816_p4);

assign tmp_289_fu_3102_p3 = ((sel_tmp43_fu_2924_p2[0:0] === 1'b1) ? 8'd0 : tmp_288_fu_3094_p3);

assign tmp_290_fu_3110_p4 = {{Log_normal_H_fu_2332_p3[25:18]}};

assign tmp_291_fu_3120_p3 = ((sel_tmp44_fu_2930_p2[0:0] === 1'b1) ? tmp_290_fu_3110_p4 : tmp_289_fu_3102_p3);

assign tmp_292_fu_3128_p3 = ((sel_tmp47_fu_2948_p2[0:0] === 1'b1) ? 8'd0 : tmp_291_fu_3120_p3);

assign tmp_293_fu_3136_p3 = ((sel_tmp48_fu_2954_p2[0:0] === 1'b1) ? tmp_264_fu_2792_p4 : tmp_292_fu_3128_p3);

assign tmp_295_fu_3192_p1 = tmp_294_reg_4020;

assign tmp_296_fu_3234_p3 = ((p_result_1_3_fu_3212_p2[0:0] === 1'b1) ? tmp_347_fu_3218_p3 : tmp_348_fu_3226_p3);

assign tmp_297_fu_3242_p7 = {{{{{{p_result_5_3_reg_3975}, {p_result_4_3_reg_3980}}, {p_result_3_3_reg_3985}}, {p_result_2_3_fu_3186_p2}}, {p_result_1_3_fu_3212_p2}}, {tmp_296_fu_3234_p3}};

assign tmp_298_fu_2126_p1 = p_in7_fu_2118_p3[15:0];

assign tmp_299_fu_3265_p2 = ((E_normal_H_fu_3255_p2 > 6'd33) ? 1'b1 : 1'b0);

assign tmp_300_fu_2204_p1 = p_in1_fu_2198_p2[7:0];

assign tmp_301_fu_2214_p1 = p_in7_fu_2118_p3[7:0];

assign tmp_302_fu_3162_p2 = (7'd34 + E_normal_L_cast_fu_2648_p1);

assign tmp_303_fu_3278_p2 = ((E_normal_H_2_fu_3271_p3 < 7'd34) ? 1'b1 : 1'b0);

assign tmp_304_fu_2248_p1 = Log_normal_L_fu_2005_p3[3:0];

assign tmp_305_fu_2589_p4 = {{p_val8_5_fu_2581_p3[3:2]}};

assign tmp_306_fu_3284_p1 = E_normal_H_2_fu_3271_p3;

assign tmp_307_fu_3288_p2 = Log_normal_H_reg_3970 << tmp_306_fu_3284_p1;

assign tmp_308_fu_3293_p2 = (7'd60 - E_normal_H_2_fu_3271_p3);

assign tmp_309_fu_3307_p2 = Log_normal_L_1_reg_3915 >> tmp_473_cast_fu_3303_p1;

assign tmp_310_fu_3316_p3 = ((tmp_303_fu_3278_p2[0:0] === 1'b1) ? tmp_349_fu_3312_p1 : 33'd0);

assign tmp_311_fu_1813_p2 = ((shiftval_reg_3805 > 7'd58) ? 1'b1 : 1'b0);

assign tmp_312_fu_1821_p2 = Z2o2_cast_fu_1758_p4 >> tmp_482_cast_fu_1818_p1;

assign tmp_313_fu_3378_p2 = (Z_small_cast_fu_3374_p1 - Z2o2_small_cast_fu_3364_p1);

assign tmp_314_fu_3384_p4 = {{{absZ0s_reg_3827}, {2'd0}}, {Z2o2_small_reg_3864}};

assign tmp_315_fu_2605_p3 = p_val8_5_fu_2581_p3[32'd1];

assign tmp_316_fu_3403_p4 = {{Log_small_fu_3396_p3[58:3]}};

assign tmp_317_fu_3433_p3 = Log_small_1_cast_fu_3421_p1[32'd57];

assign tmp_318_fu_3463_p3 = {{8'd255}, {E0_sub_1_fu_3455_p3}};

assign tmp_319_fu_2613_p3 = p_val8_5_fu_2581_p3[32'd3];

assign tmp_320_fu_3489_p2 = ($signed(11'd1033) - $signed(tmp_471_cast_fu_3361_p1));

assign tmp_321_fu_3499_p4 = {{Log_small_fu_3396_p3[56:3]}};

assign tmp_322_fu_3509_p3 = {{tmp_321_fu_3499_p4}, {2'd0}};

assign tmp_323_fu_2676_p2 = Log_normal_H_fu_2332_p3 << 64'd14;

assign tmp_324_fu_3517_p3 = ((tmp_352_fu_3481_p3[0:0] === 1'b1) ? tmp_322_fu_3509_p3 : tmp_353_fu_3495_p1);

assign tmp_325_fu_3525_p4 = {{Log_small_fu_3396_p3[57:3]}};

assign tmp_326_fu_2704_p1 = p_v1_fu_2696_p3[15:0];

assign tmp_327_fu_3535_p3 = {{tmp_325_fu_3525_p4}, {1'd0}};

assign tmp_328_fu_2780_p1 = Log_normal_H_fu_2332_p3[1:0];

assign tmp_329_fu_3543_p3 = ((tmp_350_fu_3425_p3[0:0] === 1'b1) ? tmp_327_fu_3535_p3 : tmp_324_fu_3517_p3);

assign tmp_330_fu_3551_p3 = {{tmp_329_fu_3543_p3}, {1'd0}};

assign tmp_331_fu_3334_p2 = (tmp_354_fu_3330_p1 | tmp_310_fu_3316_p3);

assign tmp_332_fu_3350_p3 = {{tmp_331_fu_3334_p2}, {tmp_505_cast_fu_3340_p4}};

assign tmp_333_fu_3583_p4 = {{Log_g_fu_3559_p3[56:5]}};

assign tmp_334_fu_3601_p2 = (tmp_357_fu_3593_p3 | sticky_fu_3569_p2);

assign tmp_335_fu_3607_p2 = (tmp_356_fu_3575_p3 & tmp_334_fu_3601_p2);

assign tmp_336_fu_2858_p1 = p_v1_fu_2696_p3[7:0];

assign tmp_337_fu_3617_p3 = ((small_reg_3811[0:0] === 1'b1) ? E_small_fu_3475_p2 : tmp_320_fu_3489_p2);

assign tmp_338_cast_fu_1707_p4 = {{grp_range_red_fu_448_ap_return_0[54:28]}};

assign tmp_338_fu_3624_p3 = {{tmp_337_fu_3617_p3}, {tmp_333_fu_3583_p4}};

assign tmp_339_fu_3642_p3 = {{sR_reg_3678}, {63'd0}};

assign tmp_340_fu_3202_p4 = {{p_val8_7_fu_3195_p3[3:2]}};

assign tmp_341_cast_fu_1725_p1 = tmp_185_fu_1717_p3;

assign tmp_341_fu_3655_p1 = res_fp_fu_3649_p2;

assign tmp_344_cast_fu_1897_p1 = tmp_256_reg_3858;

assign tmp_347_fu_3218_p3 = p_val8_7_fu_3195_p3[32'd1];

assign tmp_348_fu_3226_p3 = p_val8_7_fu_3195_p3[32'd3];

assign tmp_349_fu_3312_p1 = tmp_307_fu_3288_p2[32:0];

assign tmp_350_fu_3425_p3 = Log_small_fu_3396_p3[32'd58];

assign tmp_351_fu_3449_p2 = (tmp_350_fu_3425_p3 | tmp_317_fu_3433_p3);

assign tmp_352_fu_3481_p3 = Log_small_fu_3396_p3[32'd57];

assign tmp_353_cast_fu_1999_p1 = tmp_194_reg_3891;

assign tmp_353_fu_3495_p1 = Log_small_fu_3396_p3[55:0];

assign tmp_354_cast_fu_2002_p1 = $signed(tmp_196_reg_3896);

assign tmp_354_fu_3330_p1 = tmp_309_fu_3307_p2[32:0];

assign tmp_355_fu_3565_p1 = Log_g_fu_3559_p3[3:0];

assign tmp_356_cast1_fu_2028_p1 = tmp_282_fu_2020_p3;

assign tmp_356_cast_fu_2032_p1 = tmp_282_fu_2020_p3;

assign tmp_356_fu_3575_p3 = Log_g_fu_3559_p3[32'd4];

assign tmp_357_cast_fu_2042_p1 = $signed(tmp_199_fu_2036_p2);

assign tmp_357_fu_3593_p3 = Log_g_fu_3559_p3[32'd5];

assign tmp_427_cast_fu_2848_p4 = {{Log_normal_H_fu_2332_p3[9:6]}};

assign tmp_471_cast_fu_3361_p1 = E_normal_H_2_reg_4030;

assign tmp_472_cast_fu_3299_p1 = $signed(tmp_308_fu_3293_p2);

assign tmp_473_cast_fu_3303_p1 = $unsigned(tmp_472_cast_fu_3299_p1);

assign tmp_482_cast_fu_1818_p1 = $unsigned(shiftval_reg_3805);

assign tmp_487_cast_fu_3392_p1 = tmp_314_fu_3384_p4;

assign tmp_492_cast_fu_3471_p1 = tmp_318_fu_3463_p3;

assign tmp_505_cast_fu_3340_p4 = {{Log_normal_normd_L_fu_3324_p2[59:36]}};

assign tmp_514_cast_fu_3613_p1 = tmp_335_fu_3607_p2;

assign tmp_517_cast_fu_3632_p1 = tmp_338_fu_3624_p3;

assign tmp_fu_490_p1 = fpX_fu_486_p1[62:0];

assign tmp_s_fu_514_p4 = {{{{1'd1}, {tmp_130_fu_494_p1}}}, {1'd0}};

always @ (posedge ap_clk) begin
    Z2o2_small_reg_3864[2:0] <= 3'b000;
end

endmodule //logd
