// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="logd,hls_ip_2018_3,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx690tffg1761-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.572857,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=11,HLS_SYN_FF=3787,HLS_SYN_LUT=9625,HLS_VERSION=2018_3}" *)

module logd (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        ap_return
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] x;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] FirstBit_fu_496_p3;
reg   [0:0] FirstBit_reg_3661;
wire   [53:0] Y0_fu_534_p3;
reg   [53:0] Y0_reg_3666;
wire   [0:0] sR_fu_605_p2;
reg   [0:0] sR_reg_3671;
wire   [10:0] absE_fu_617_p3;
reg   [10:0] absE_reg_3680;
wire   [0:0] tmp_122_fu_625_p2;
reg   [0:0] tmp_122_reg_3686;
wire   [0:0] tmp_123_fu_631_p2;
reg   [0:0] tmp_123_reg_3690;
wire   [0:0] tmp_124_fu_637_p2;
reg   [0:0] tmp_124_reg_3694;
wire   [0:0] tmp_125_fu_643_p2;
reg   [0:0] tmp_125_reg_3698;
wire   [0:0] tmp_136_fu_649_p3;
reg   [0:0] tmp_136_reg_3702;
wire   [0:0] tmp_126_fu_657_p2;
reg   [0:0] tmp_126_reg_3706;
wire   [0:0] p_result_5_fu_697_p2;
reg   [0:0] p_result_5_reg_3710;
wire   [0:0] p_result_5_1_fu_713_p2;
reg   [0:0] p_result_5_1_reg_3715;
wire   [0:0] p_result_4_fu_755_p2;
reg   [0:0] p_result_4_reg_3720;
wire   [0:0] p_result_4_1_fu_797_p2;
reg   [0:0] p_result_4_1_reg_3725;
wire   [0:0] p_result_3_fu_915_p2;
reg   [0:0] p_result_3_reg_3730;
wire   [0:0] p_result_3_1_fu_969_p2;
reg   [0:0] p_result_3_1_reg_3735;
wire   [0:0] p_result_2_fu_1149_p2;
reg   [0:0] p_result_2_reg_3740;
wire   [0:0] p_result_2_1_fu_1303_p2;
reg   [0:0] p_result_2_1_reg_3746;
wire   [7:0] p_val8_fu_1373_p3;
reg   [7:0] p_val8_reg_3752;
reg   [3:0] tmp_157_reg_3757;
wire   [7:0] p_val8_2_fu_1443_p3;
reg   [7:0] p_val8_2_reg_3762;
reg   [3:0] tmp_169_reg_3767;
wire   [0:0] tmp_176_fu_1461_p2;
reg   [0:0] tmp_176_reg_3772;
wire   [25:0] tmp_221_fu_1467_p1;
reg   [25:0] tmp_221_reg_3777;
reg   [4:0] A_reg_3783;
wire   [5:0] lzo_fu_1611_p2;
reg   [5:0] lzo_reg_3788;
wire    ap_CS_fsm_state2;
wire    grp_range_red_fu_446_ap_ready;
wire    grp_range_red_fu_446_ap_done;
wire  signed [6:0] shiftval_fu_1621_p2;
reg  signed [6:0] shiftval_reg_3793;
wire   [0:0] small_fu_1649_p2;
reg   [0:0] small_reg_3799;
reg   [63:0] almostLog_H_reg_3805;
reg   [63:0] almostLog_L_reg_3810;
wire   [24:0] absZ0s_fu_1691_p1;
reg   [24:0] absZ0s_reg_3815;
wire   [26:0] squarerIn_fu_1717_p3;
reg   [26:0] squarerIn_reg_3821;
wire   [54:0] tmp_248_fu_1725_p1;
reg   [54:0] tmp_248_reg_3826;
wire   [59:0] tmp_249_fu_1729_p1;
reg   [59:0] tmp_249_reg_3831;
wire   [22:0] tmp_255_fu_1733_p1;
reg   [22:0] tmp_255_reg_3836;
wire   [59:0] LogF_normal_L_2_fu_1788_p2;
reg   [59:0] LogF_normal_L_2_reg_3841;
wire    ap_CS_fsm_state3;
reg   [0:0] tmp_254_reg_3846;
wire   [30:0] Z2o2_small_fu_1823_p3;
reg   [30:0] Z2o2_small_reg_3852;
reg   [7:0] tmp_229_cast_reg_3858;
wire    ap_CS_fsm_state4;
reg   [0:0] tmp_138_reg_3863;
reg   [25:0] tmp_345_cast_reg_3868;
wire   [63:0] LogF_normal_H_2_fu_1944_p3;
reg   [63:0] LogF_normal_H_2_reg_3873;
wire   [60:0] tmp_192_fu_1952_p2;
reg   [60:0] tmp_192_reg_3879;
wire   [60:0] tmp_194_fu_1958_p2;
reg   [60:0] tmp_194_reg_3884;
wire  signed [61:0] Log_normal_L_fu_1993_p3;
reg  signed [61:0] Log_normal_L_reg_3889;
wire    ap_CS_fsm_state5;
wire   [59:0] Log_normal_L_1_fu_2000_p1;
reg   [59:0] Log_normal_L_1_reg_3903;
wire   [63:0] tmp_198_fu_2034_p2;
reg   [63:0] tmp_198_reg_3909;
wire   [63:0] tmp_199_fu_2044_p2;
reg   [63:0] tmp_199_reg_3914;
wire   [0:0] p_result_5_2_fu_2068_p2;
reg   [0:0] p_result_5_2_reg_3919;
wire   [0:0] p_result_4_2_fu_2118_p2;
reg   [0:0] p_result_4_2_reg_3928;
wire   [0:0] sel_tmp27_fu_2140_p2;
reg   [0:0] sel_tmp27_reg_3935;
wire   [0:0] p_result_3_2_fu_2196_p2;
reg   [0:0] p_result_3_2_reg_3940;
wire   [3:0] tmp_222_fu_2268_p3;
reg   [3:0] tmp_222_reg_3948;
wire   [7:0] tmp_232_fu_2312_p3;
reg   [7:0] tmp_232_reg_3953;
wire   [63:0] Log_normal_H_fu_2320_p3;
reg   [63:0] Log_normal_H_reg_3958;
wire    ap_CS_fsm_state6;
wire   [0:0] p_result_5_3_fu_2658_p2;
reg   [0:0] p_result_5_3_reg_3963;
wire   [0:0] p_result_4_3_fu_2696_p2;
reg   [0:0] p_result_4_3_reg_3968;
wire   [0:0] p_result_3_3_fu_2830_p2;
reg   [0:0] p_result_3_3_reg_3973;
wire   [0:0] sel_tmp44_fu_2918_p2;
reg   [0:0] sel_tmp44_reg_3978;
wire   [0:0] sel_tmp47_fu_2936_p2;
reg   [0:0] sel_tmp47_reg_3983;
wire   [0:0] or_cond3_fu_2992_p2;
reg   [0:0] or_cond3_reg_3988;
wire   [3:0] tmp_282_fu_3048_p3;
reg   [3:0] tmp_282_reg_3993;
wire   [3:0] newSel4_fu_3056_p3;
reg   [3:0] newSel4_reg_3998;
wire   [7:0] p_val8_6_fu_3132_p3;
reg   [7:0] p_val8_6_reg_4003;
reg   [3:0] tmp_292_reg_4008;
wire   [6:0] tmp_300_fu_3150_p2;
reg   [6:0] tmp_300_reg_4013;
wire   [6:0] E_normal_H_2_fu_3259_p3;
reg   [6:0] E_normal_H_2_reg_4018;
wire    ap_CS_fsm_state7;
wire   [56:0] tmp_330_fu_3338_p3;
reg   [56:0] tmp_330_reg_4023;
wire    grp_range_red_fu_446_ap_start;
wire    grp_range_red_fu_446_ap_idle;
wire   [63:0] grp_range_red_fu_446_ap_return_0;
wire   [63:0] grp_range_red_fu_446_ap_return_1;
wire   [63:0] grp_range_red_fu_446_ap_return_2;
wire   [63:0] tmp_339_fu_3643_p1;
reg   [63:0] ap_phi_mux_p_0_phi_fu_425_p14;
reg   [63:0] p_0_reg_418;
wire    ap_CS_fsm_state8;
reg    grp_range_red_fu_446_ap_start_reg;
wire   [63:0] fpX_fu_484_p1;
wire   [51:0] tmp_128_fu_492_p1;
wire   [52:0] tmp_117_fu_522_p3;
wire   [0:0] tmp_133_fu_504_p3;
wire   [53:0] tmp_203_cast_fu_530_p1;
wire   [53:0] tmp_s_fu_512_p4;
wire   [0:0] tmp_118_fu_543_p2;
wire   [9:0] tmp_119_fu_549_p3;
wire   [10:0] tmp_208_cast_fu_561_p4;
wire   [10:0] tmp_207_cast_fu_557_p1;
wire   [0:0] tmp_135_fu_585_p3;
wire   [62:0] tmp_120_fu_577_p3;
wire   [0:0] not_tmp_s_fu_599_p2;
wire   [0:0] phitmp_fu_593_p2;
wire   [10:0] E_fu_571_p2;
wire   [10:0] tmp_121_fu_611_p2;
wire   [62:0] tmp_fu_488_p1;
wire   [51:0] tmp_130_fu_663_p4;
wire   [63:0] MAN_IN_1_fu_673_p3;
wire   [63:0] MAN_IN_fu_681_p2;
wire   [31:0] tmp_139_fu_687_p4;
wire   [31:0] tmp_149_fu_703_p4;
wire   [15:0] tmp_156_fu_729_p4;
wire   [47:0] st1_fu_719_p4;
wire   [47:0] tmp_136_cast_fu_739_p1;
wire   [47:0] p_v_fu_743_p3;
wire   [15:0] tmp_162_fu_751_p1;
wire   [16:0] tmp_163_fu_771_p4;
wire   [48:0] st2_fu_761_p4;
wire   [48:0] tmp_139_cast_fu_781_p1;
wire   [48:0] p_in_fu_785_p3;
wire   [15:0] tmp_174_fu_793_p1;
wire   [7:0] tmp_131_fu_803_p4;
wire   [7:0] tmp_132_fu_813_p4;
wire   [3:0] tmp_140_fu_831_p4;
wire   [7:0] tmp_244_cast_fu_841_p3;
wire   [7:0] tmp_245_cast_fu_849_p4;
wire   [7:0] tmp_134_fu_823_p3;
wire   [7:0] tmp_248_cast_fu_877_p4;
wire   [0:0] sel_tmp1_fu_895_p2;
wire   [0:0] sel_tmp2_fu_901_p2;
wire   [7:0] tmp_246_cast_fu_867_p4;
wire   [7:0] sel_tmp_fu_887_p3;
wire   [7:0] tmp_141_fu_907_p3;
wire   [7:0] p_in2_fu_859_p3;
wire   [7:0] tmp_142_fu_921_p4;
wire   [0:0] sel_tmp3_fu_939_p2;
wire   [0:0] sel_tmp4_fu_945_p2;
wire   [7:0] tmp_144_fu_951_p4;
wire   [7:0] tmp_143_fu_931_p3;
wire   [7:0] tmp_145_fu_961_p3;
wire   [3:0] tmp_256_cast_fu_991_p4;
wire   [5:0] p_in79_v_fu_975_p3;
wire   [5:0] p_in78_v_fu_983_p3;
wire   [0:0] sel_tmp5_fu_1067_p2;
wire   [0:0] sel_tmp30_demorgan_fu_1079_p2;
wire   [0:0] sel_tmp7_fu_1085_p2;
wire   [0:0] sel_tmp8_fu_1091_p2;
wire   [5:0] p_in4_v_cast_fu_1097_p3;
wire   [0:0] sel_tmp6_fu_1073_p2;
wire   [5:0] p_in79_v_pn_fu_1009_p3;
wire   [0:0] or_cond_fu_1113_p2;
wire   [5:0] newSel_v_v_fu_1105_p3;
wire   [5:0] newSel236_v_v_fu_1119_p3;
wire   [5:0] newSel238_v_v_fu_1127_p3;
wire   [63:0] newSel238_v_v_cast_fu_1135_p1;
wire   [63:0] newSel238_v_fu_1139_p2;
wire   [3:0] tmp_175_fu_1145_p1;
wire   [7:0] tmp_181_fu_1155_p1;
wire   [7:0] tmp_147_fu_1165_p4;
wire   [7:0] tmp_146_fu_1159_p2;
wire   [15:0] tmp_148_fu_1175_p3;
wire   [0:0] tmp_150_fu_1183_p2;
wire   [3:0] p_in5_fu_1001_p3;
wire   [3:0] tmp_269_cast_fu_1057_p4;
wire   [0:0] sel_tmp10_fu_1197_p2;
wire   [0:0] sel_tmp11_fu_1203_p2;
wire   [3:0] tmp_262_cast_fu_1017_p4;
wire   [3:0] sel_tmp9_fu_1189_p3;
wire   [0:0] sel_tmp13_fu_1217_p2;
wire   [0:0] sel_tmp14_fu_1223_p2;
wire   [3:0] tmp_263_cast_fu_1027_p4;
wire   [3:0] sel_tmp12_fu_1209_p3;
wire   [0:0] sel_tmp16_fu_1237_p2;
wire   [0:0] sel_tmp17_fu_1243_p2;
wire   [0:0] sel_tmp18_fu_1249_p2;
wire   [3:0] sel_tmp15_fu_1229_p3;
wire   [0:0] sel_tmp20_fu_1263_p2;
wire   [3:0] tmp_266_cast_fu_1037_p4;
wire   [3:0] sel_tmp19_fu_1255_p3;
wire   [0:0] sel_tmp55_demorgan_fu_1277_p2;
wire   [0:0] sel_tmp22_fu_1283_p2;
wire   [0:0] sel_tmp23_fu_1289_p2;
wire   [3:0] tmp_267_cast_fu_1047_p4;
wire   [3:0] sel_tmp21_fu_1269_p3;
wire   [3:0] p_in8_fu_1295_p3;
wire   [7:0] tmp_151_fu_1309_p4;
wire   [7:0] tmp_153_fu_1331_p4;
wire   [7:0] tmp_152_fu_1319_p3;
wire   [7:0] tmp_186_fu_1327_p1;
wire   [7:0] tmp_155_fu_1349_p3;
wire   [7:0] sel_tmp24_fu_1357_p3;
wire   [7:0] sel_tmp25_fu_1365_p3;
wire   [7:0] tmp_154_fu_1341_p3;
wire   [7:0] tmp_164_fu_1399_p4;
wire   [7:0] tmp_161_fu_1391_p3;
wire   [7:0] tmp_166_fu_1417_p4;
wire   [7:0] tmp_165_fu_1409_p3;
wire   [7:0] tmp_167_fu_1427_p3;
wire   [7:0] tmp_168_fu_1435_p3;
wire   [7:0] tmp_158_fu_1482_p1;
wire   [7:0] p_val8_1_fu_1485_p3;
wire   [1:0] tmp_189_fu_1491_p4;
wire   [0:0] p_result_1_fu_1501_p2;
wire   [0:0] tmp_191_fu_1507_p3;
wire   [0:0] tmp_193_fu_1515_p3;
wire   [0:0] tmp_159_fu_1523_p3;
wire   [7:0] tmp_170_fu_1543_p1;
wire   [7:0] p_val8_3_fu_1546_p3;
wire   [1:0] tmp_195_fu_1552_p4;
wire   [0:0] p_result_1_1_fu_1562_p2;
wire   [0:0] tmp_196_fu_1568_p3;
wire   [0:0] tmp_211_fu_1576_p3;
wire   [0:0] tmp_171_fu_1584_p3;
wire   [5:0] tmp_160_fu_1531_p7;
wire   [5:0] tmp_172_fu_1592_p7;
wire   [5:0] lzo_1_in_fu_1604_p3;
wire   [6:0] lzo_cast1_fu_1617_p1;
wire  signed [15:0] shiftval_cast_fu_1627_p1;
wire   [31:0] tmp_173_fu_1631_p1;
wire   [0:0] doRR_fu_1635_p3;
wire   [0:0] tmp_177_fu_1643_p2;
wire   [25:0] tmp_178_fu_1654_p2;
wire   [25:0] absZ0_fu_1659_p3;
wire   [63:0] tmp_179_fu_1677_p1;
wire   [63:0] tmp_180_fu_1681_p1;
wire   [63:0] tmp_182_fu_1685_p2;
wire   [25:0] tmp_183_fu_1705_p3;
wire   [26:0] tmp_336_cast_fu_1695_p4;
wire   [26:0] tmp_339_cast_fu_1713_p1;
wire   [26:0] Z2o2_full_fu_1740_p0;
wire   [53:0] squarerIn_1_cast_fu_1737_p1;
wire   [26:0] Z2o2_full_fu_1740_p1;
wire   [53:0] Z2o2_full_fu_1740_p2;
wire   [25:0] tmp_184_fu_1756_p4;
wire   [54:0] tmp_185_fu_1766_p1;
wire   [54:0] Log1p_normal_fu_1770_p2;
wire   [63:0] Log1p_normal_1_cast_fu_1775_p1;
wire   [59:0] tmp_187_fu_1779_p1;
wire   [63:0] LogF_normal_L_fu_1783_p2;
wire   [27:0] Z2o2_cast_fu_1746_p4;
wire   [27:0] tmp_480_cast_fu_1806_p1;
wire   [27:0] tmp_310_fu_1809_p2;
wire   [0:0] tmp_309_fu_1801_p2;
wire   [30:0] phitmp1_fu_1815_p3;
wire   [10:0] tmp_127_fu_1837_p1;
wire   [58:0] tmp_127_fu_1837_p2;
wire   [19:0] m1_fu_3648_p2;
wire   [10:0] tmp_137_fu_1847_p1;
wire   [59:0] tmp_129_fu_1850_p3;
wire   [60:0] tmp_228_cast_fu_1858_p1;
wire   [60:0] tmp_225_cast_fu_1843_p1;
wire   [60:0] m0_fu_1862_p2;
wire   [63:0] tmp_342_cast_fu_1885_p1;
wire   [22:0] tmp_188_fu_1888_p1;
wire   [33:0] tmp_258_fu_1914_p1;
wire   [59:0] absELog2_pad_L_fu_1918_p3;
wire   [22:0] LogF_normal_H_cast_fu_1896_p2;
wire   [63:0] LogF_normal_H_fu_1891_p2;
wire   [0:0] tmp_265_fu_1930_p3;
wire   [63:0] tmp_190_fu_1938_p2;
wire   [60:0] LogF_normal_L_2_cast_fu_1901_p1;
wire   [60:0] absELog2_pad_L_cast_fu_1926_p1;
wire   [7:0] tmp_231_cast_fu_1964_p1;
wire   [7:0] absELog2_H_fu_1967_p2;
wire   [33:0] absELog2_pad_H_fu_1972_p3;
wire  signed [61:0] tmp_352_cast_fu_1990_p1;
wire   [61:0] tmp_351_cast_fu_1987_p1;
wire   [0:0] tmp_280_fu_2008_p3;
wire   [34:0] absELog2_pad_H_cast_fu_1983_p1;
wire   [34:0] tmp_354_cast_fu_2020_p1;
wire   [34:0] tmp_197_fu_2024_p2;
wire  signed [63:0] tmp_355_cast_fu_2030_p1;
wire   [63:0] absELog2_pad_H_cast1_fu_1979_p1;
wire   [63:0] tmp196_fu_2039_p2;
wire   [63:0] tmp_354_cast1_fu_2016_p1;
wire   [31:0] tmp_200_fu_2050_p4;
wire   [59:0] tmp_201_fu_2060_p3;
wire   [49:0] tmp_202_fu_2074_p4;
wire   [17:0] tmp_204_fu_2088_p4;
wire  signed [19:0] tmp_205_fu_2098_p1;
wire  signed [51:0] tmp_203_fu_2084_p1;
wire   [51:0] sf_cast_fu_2102_p1;
wire   [51:0] p_in7_fu_2106_p3;
wire   [15:0] tmp_296_fu_2114_p1;
wire   [59:0] tmp_206_fu_2124_p4;
wire   [0:0] sel_tmp28_fu_2146_p2;
wire   [0:0] tmp_207_fu_2134_p2;
wire   [0:0] or_cond1_fu_2160_p2;
wire   [5:0] newSel1_fu_2152_p3;
wire   [5:0] newSel242_cast_cast_fu_2166_p3;
wire   [5:0] newSel2_fu_2174_p3;
wire  signed [63:0] Log_normal_L_cast_fu_2004_p1;
wire   [63:0] newSel244_cast_fu_2182_p1;
wire   [63:0] p_in1_fu_2186_p2;
wire   [7:0] tmp_298_fu_2192_p1;
wire   [7:0] tmp_299_fu_2202_p1;
wire   [7:0] tmp_209_fu_2212_p4;
wire   [7:0] tmp_208_fu_2206_p2;
wire   [15:0] tmp_210_fu_2222_p3;
wire   [3:0] tmp_302_fu_2236_p1;
wire   [3:0] tmp_218_fu_2240_p4;
wire   [0:0] tmp_212_fu_2230_p2;
wire   [3:0] tmp_219_fu_2250_p3;
wire   [3:0] tmp_220_fu_2258_p4;
wire   [7:0] tmp_228_fu_2276_p3;
wire   [7:0] tmp_229_fu_2284_p4;
wire   [7:0] tmp_230_fu_2294_p3;
wire   [7:0] tmp_231_fu_2302_p4;
wire   [0:0] sel_tmp29_fu_2330_p2;
wire   [0:0] sel_tmp26_fu_2325_p2;
wire   [0:0] sel_tmp32_fu_2345_p2;
wire   [0:0] sel_tmp33_fu_2350_p2;
wire   [0:0] sel_tmp121_demorgan_fu_2366_p2;
wire   [0:0] sel_tmp36_fu_2370_p2;
wire   [0:0] sel_tmp30_fu_2334_p2;
wire   [3:0] tmp_217_fu_2417_p4;
wire   [0:0] sel_tmp31_fu_2339_p2;
wire   [3:0] tmp_216_fu_2408_p4;
wire   [3:0] tmp_223_fu_2426_p3;
wire   [0:0] sel_tmp34_fu_2355_p2;
wire   [3:0] tmp_215_fu_2399_p4;
wire   [3:0] tmp_224_fu_2433_p3;
wire   [0:0] sel_tmp35_fu_2360_p2;
wire   [3:0] tmp_214_fu_2390_p4;
wire   [3:0] tmp_225_fu_2441_p3;
wire   [0:0] sel_tmp37_fu_2376_p2;
wire   [3:0] tmp_213_fu_2381_p4;
wire   [3:0] tmp_226_fu_2449_p3;
wire   [3:0] tmp_227_fu_2457_p3;
wire   [7:0] tmp_233_fu_2471_p4;
wire   [7:0] tmp_235_fu_2487_p4;
wire   [7:0] tmp_234_fu_2480_p3;
wire   [7:0] tmp_237_fu_2504_p4;
wire   [7:0] tmp_236_fu_2496_p3;
wire   [7:0] tmp_239_fu_2521_p4;
wire   [7:0] tmp_238_fu_2513_p3;
wire   [7:0] tmp_241_fu_2538_p4;
wire   [7:0] tmp_240_fu_2530_p3;
wire   [7:0] p_val8_4_fu_2547_p3;
wire   [3:0] tmp_242_fu_2555_p4;
wire   [0:0] p_result_2_2_fu_2465_p2;
wire   [7:0] tmp_243_fu_2565_p1;
wire   [7:0] p_val8_5_fu_2569_p3;
wire   [1:0] tmp_303_fu_2577_p4;
wire   [0:0] p_result_1_2_fu_2587_p2;
wire   [0:0] tmp_313_fu_2593_p3;
wire   [0:0] tmp_317_fu_2601_p3;
wire   [0:0] tmp_244_fu_2609_p3;
wire   [5:0] tmp_245_fu_2617_p7;
wire   [5:0] E_normal_L_fu_2630_p2;
wire   [31:0] tmp_246_fu_2640_p4;
wire   [33:0] tmp_247_fu_2650_p3;
wire   [45:0] tmp_250_fu_2670_p4;
wire   [63:0] tmp_321_fu_2664_p2;
wire   [63:0] tmp_251_fu_2680_p1;
wire   [63:0] p_v1_fu_2684_p3;
wire   [15:0] tmp_324_fu_2692_p1;
wire   [13:0] tmp_252_fu_2702_p4;
wire   [15:0] tmp_253_fu_2712_p3;
wire   [17:0] tmp_257_fu_2726_p4;
wire   [15:0] tmp_256_fu_2720_p2;
wire   [33:0] tmp_259_fu_2736_p3;
wire   [0:0] sel_tmp39_fu_2756_p2;
wire   [1:0] tmp_326_fu_2768_p1;
wire   [0:0] sel_tmp40_fu_2762_p2;
wire   [7:0] tmp_261_fu_2772_p3;
wire   [7:0] tmp_262_fu_2780_p4;
wire   [0:0] tmp_260_fu_2744_p2;
wire   [7:0] tmp_264_fu_2804_p4;
wire   [0:0] or_cond2_fu_2798_p2;
wire   [7:0] tmp_263_fu_2790_p3;
wire   [7:0] tmp_266_fu_2814_p3;
wire   [7:0] tmp_267_fu_2822_p3;
wire   [7:0] tmp_334_fu_2846_p1;
wire   [7:0] tmp_269_fu_2856_p4;
wire   [7:0] tmp_268_fu_2850_p2;
wire   [15:0] tmp_270_fu_2866_p3;
wire   [15:0] tmp_271_fu_2874_p2;
wire   [33:0] tmp_272_fu_2880_p3;
wire   [0:0] tmp_274_fu_2894_p2;
wire   [0:0] sel_tmp38_fu_2750_p2;
wire   [0:0] sel_tmp42_fu_2906_p2;
wire   [0:0] sel_tmp45_fu_2924_p2;
wire   [0:0] sel_tmp46_fu_2930_p2;
wire   [0:0] sel_tmp185_demorgan_fu_2948_p2;
wire   [0:0] sel_tmp49_fu_2954_p2;
wire   [0:0] sel_tmp50_fu_2960_p2;
wire   [3:0] tmp_275_fu_2966_p3;
wire   [3:0] tmp_276_fu_2974_p4;
wire   [0:0] sel_tmp48_fu_2942_p2;
wire   [0:0] sel_tmp43_fu_2912_p2;
wire   [3:0] tmp_425_cast_fu_2836_p4;
wire   [0:0] sel_tmp41_fu_2900_p2;
wire   [0:0] tmp_273_fu_2888_p2;
wire   [3:0] tmp_278_fu_3012_p4;
wire   [3:0] tmp_279_fu_3030_p4;
wire   [3:0] tmp_277_fu_2984_p3;
wire   [3:0] tmp_281_fu_3040_p3;
wire   [0:0] or_cond5_fu_3006_p2;
wire   [3:0] newSel3_fu_2998_p3;
wire   [3:0] newSel258_cast_fu_3022_p3;
wire   [7:0] tmp_284_fu_3064_p4;
wire   [7:0] tmp_285_fu_3074_p3;
wire   [7:0] tmp_286_fu_3082_p3;
wire   [7:0] tmp_288_fu_3098_p4;
wire   [7:0] tmp_287_fu_3090_p3;
wire   [7:0] tmp_289_fu_3108_p3;
wire   [7:0] tmp_290_fu_3116_p3;
wire   [7:0] tmp_291_fu_3124_p3;
wire   [6:0] E_normal_L_cast_fu_2636_p1;
wire   [0:0] or_cond4_fu_3159_p2;
wire   [0:0] or_cond6_fu_3163_p2;
wire   [3:0] tmp_283_fu_3168_p3;
wire   [0:0] p_result_2_3_fu_3174_p2;
wire   [7:0] tmp_293_fu_3180_p1;
wire   [7:0] p_val8_7_fu_3183_p3;
wire   [1:0] tmp_338_fu_3190_p4;
wire   [0:0] p_result_1_3_fu_3200_p2;
wire   [0:0] tmp_345_fu_3206_p3;
wire   [0:0] tmp_346_fu_3214_p3;
wire   [0:0] tmp_294_fu_3222_p3;
wire   [5:0] tmp_295_fu_3230_p7;
wire   [5:0] E_normal_H_fu_3243_p2;
wire   [0:0] tmp_297_fu_3253_p2;
wire   [6:0] E_normal_H_cast_fu_3249_p1;
wire   [63:0] tmp_304_fu_3272_p1;
wire   [6:0] tmp_306_fu_3281_p2;
wire  signed [31:0] tmp_470_cast_fu_3287_p1;
wire   [59:0] tmp_471_cast_fu_3291_p1;
wire   [63:0] tmp_305_fu_3276_p2;
wire   [0:0] tmp_301_fu_3266_p2;
wire   [32:0] tmp_347_fu_3300_p1;
wire   [63:0] Log_normal_L_1_cast_fu_3156_p1;
wire   [59:0] tmp_307_fu_3295_p2;
wire   [32:0] tmp_352_fu_3318_p1;
wire   [32:0] tmp_308_fu_3304_p3;
wire   [63:0] Log_normal_normd_L_fu_3312_p2;
wire   [32:0] tmp_329_fu_3322_p2;
wire   [23:0] tmp_503_cast_fu_3328_p4;
wire   [57:0] Z_small_fu_3355_p3;
wire   [58:0] Z_small_cast_fu_3362_p1;
wire   [58:0] Z2o2_small_cast_fu_3352_p1;
wire   [57:0] tmp_312_fu_3372_p4;
wire   [58:0] tmp_485_cast_fu_3380_p1;
wire   [58:0] tmp_311_fu_3366_p2;
wire   [58:0] Log_small_fu_3384_p3;
wire   [55:0] tmp_314_fu_3391_p4;
wire   [58:0] Log_small_1_fu_3401_p3;
wire   [63:0] Log_small_1_cast_fu_3409_p1;
wire   [0:0] tmp_348_fu_3413_p3;
wire   [0:0] tmp_315_fu_3421_p3;
wire   [0:0] tmp_349_fu_3437_p2;
wire   [1:0] E0_sub_fu_3429_p3;
wire   [1:0] E0_sub_1_fu_3443_p3;
wire   [9:0] tmp_316_fu_3451_p3;
wire   [10:0] tmp_490_cast_fu_3459_p1;
wire   [10:0] lzo_cast_fu_3346_p1;
wire   [10:0] tmp_469_cast_fu_3349_p1;
wire   [53:0] tmp_319_fu_3487_p4;
wire   [0:0] tmp_350_fu_3469_p3;
wire   [55:0] tmp_320_fu_3497_p3;
wire   [55:0] tmp_351_fu_3483_p1;
wire   [54:0] tmp_323_fu_3513_p4;
wire   [55:0] tmp_325_fu_3523_p3;
wire   [55:0] tmp_322_fu_3505_p3;
wire   [55:0] tmp_327_fu_3531_p3;
wire   [56:0] tmp_328_fu_3539_p3;
wire   [56:0] Log_g_fu_3547_p3;
wire   [3:0] tmp_353_fu_3553_p1;
wire   [0:0] sticky_fu_3557_p2;
wire   [0:0] tmp_355_fu_3581_p3;
wire   [0:0] tmp_354_fu_3563_p3;
wire   [0:0] tmp_332_fu_3589_p2;
wire   [0:0] tmp_333_fu_3595_p2;
wire   [10:0] E_small_fu_3463_p2;
wire   [10:0] tmp_318_fu_3477_p2;
wire   [10:0] tmp_335_fu_3605_p3;
wire   [51:0] tmp_331_fu_3571_p4;
wire   [62:0] tmp_336_fu_3612_p3;
wire   [63:0] tmp_512_cast_fu_3601_p1;
wire   [63:0] tmp_515_cast_fu_3620_p1;
wire   [63:0] EFR_fu_3624_p2;
wire   [63:0] tmp_337_fu_3630_p3;
wire   [63:0] res_fp_fu_3637_p2;
wire   [8:0] m1_fu_3648_p0;
wire   [10:0] m1_fu_3648_p1;
reg   [7:0] ap_NS_fsm;
wire   [19:0] m1_fu_3648_p10;
wire   [58:0] tmp_127_fu_1837_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_range_red_fu_446_ap_start_reg = 1'b0;
end

range_red grp_range_red_fu_446(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_range_red_fu_446_ap_start),
    .ap_done(grp_range_red_fu_446_ap_done),
    .ap_idle(grp_range_red_fu_446_ap_idle),
    .ap_ready(grp_range_red_fu_446_ap_ready),
    .A(A_reg_3783),
    .Y0(Y0_reg_3666),
    .ap_return_0(grp_range_red_fu_446_ap_return_0),
    .ap_return_1(grp_range_red_fu_446_ap_return_1),
    .ap_return_2(grp_range_red_fu_446_ap_return_2)
);

logd_mul_mul_9ns_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 20 ))
logd_mul_mul_9ns_ocq_U21(
    .din0(m1_fu_3648_p0),
    .din1(m1_fu_3648_p1),
    .dout(m1_fu_3648_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_range_red_fu_446_ap_start_reg <= 1'b0;
    end else begin
        if (((tmp_126_fu_657_p2 == 1'd0) & (tmp_136_fu_649_p3 == 1'd0) & (tmp_125_fu_643_p2 == 1'd0) & (tmp_124_fu_637_p2 == 1'd0) & (tmp_123_fu_631_p2 == 1'd0) & (tmp_122_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_range_red_fu_446_ap_start_reg <= 1'b1;
        end else if ((grp_range_red_fu_446_ap_ready == 1'b1)) begin
            grp_range_red_fu_446_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_126_fu_657_p2 == 1'd1) & (tmp_136_fu_649_p3 == 1'd0) & (tmp_125_fu_643_p2 == 1'd0) & (tmp_124_fu_637_p2 == 1'd0) & (tmp_123_fu_631_p2 == 1'd0) & (tmp_122_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_0_reg_418 <= 64'd0;
    end else if (((tmp_125_fu_643_p2 == 1'd1) & (tmp_124_fu_637_p2 == 1'd0) & (tmp_123_fu_631_p2 == 1'd0) & (tmp_122_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_0_reg_418 <= x;
    end else if ((((tmp_136_fu_649_p3 == 1'd1) & (tmp_125_fu_643_p2 == 1'd0) & (tmp_124_fu_637_p2 == 1'd0) & (tmp_123_fu_631_p2 == 1'd0) & (tmp_122_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((tmp_124_fu_637_p2 == 1'd1) & (tmp_123_fu_631_p2 == 1'd0) & (tmp_122_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        p_0_reg_418 <= 64'd9221120237041090560;
    end else if (((tmp_123_fu_631_p2 == 1'd1) & (tmp_122_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_0_reg_418 <= 64'd9218868437227405312;
    end else if (((tmp_122_fu_625_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_0_reg_418 <= 64'd18442240474082181120;
    end else if (((tmp_126_reg_3706 == 1'd0) & (tmp_136_reg_3702 == 1'd0) & (tmp_125_reg_3698 == 1'd0) & (tmp_124_reg_3694 == 1'd0) & (tmp_123_reg_3690 == 1'd0) & (tmp_122_reg_3686 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        p_0_reg_418 <= tmp_339_fu_3643_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_126_fu_657_p2 == 1'd0) & (tmp_136_fu_649_p3 == 1'd0) & (tmp_125_fu_643_p2 == 1'd0) & (tmp_124_fu_637_p2 == 1'd0) & (tmp_123_fu_631_p2 == 1'd0) & (tmp_122_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        A_reg_3783 <= {{fpX_fu_484_p1[51:47]}};
        p_result_2_1_reg_3746 <= p_result_2_1_fu_1303_p2;
        p_result_2_reg_3740 <= p_result_2_fu_1149_p2;
        p_result_3_1_reg_3735 <= p_result_3_1_fu_969_p2;
        p_result_3_reg_3730 <= p_result_3_fu_915_p2;
        p_result_4_1_reg_3725 <= p_result_4_1_fu_797_p2;
        p_result_4_reg_3720 <= p_result_4_fu_755_p2;
        p_result_5_1_reg_3715 <= p_result_5_1_fu_713_p2;
        p_result_5_reg_3710 <= p_result_5_fu_697_p2;
        p_val8_2_reg_3762 <= p_val8_2_fu_1443_p3;
        p_val8_reg_3752 <= p_val8_fu_1373_p3;
        tmp_157_reg_3757 <= {{p_val8_fu_1373_p3[7:4]}};
        tmp_169_reg_3767 <= {{p_val8_2_fu_1443_p3[7:4]}};
        tmp_176_reg_3772 <= tmp_176_fu_1461_p2;
        tmp_221_reg_3777 <= tmp_221_fu_1467_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        E_normal_H_2_reg_4018 <= E_normal_H_2_fu_3259_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        FirstBit_reg_3661 <= fpX_fu_484_p1[32'd51];
        Y0_reg_3666 <= Y0_fu_534_p3;
        absE_reg_3680 <= absE_fu_617_p3;
        sR_reg_3671 <= sR_fu_605_p2;
        tmp_122_reg_3686 <= tmp_122_fu_625_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        LogF_normal_H_2_reg_3873 <= LogF_normal_H_2_fu_1944_p3;
        tmp_138_reg_3863 <= m0_fu_1862_p2[32'd60];
        tmp_229_cast_reg_3858 <= {{m1_fu_3648_p2[18:11]}};
        tmp_345_cast_reg_3868 <= {{m0_fu_1862_p2[59:34]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        LogF_normal_L_2_reg_3841 <= LogF_normal_L_2_fu_1788_p2;
        Z2o2_small_reg_3852[30 : 3] <= Z2o2_small_fu_1823_p3[30 : 3];
        tmp_254_reg_3846 <= LogF_normal_L_fu_1783_p2[32'd60];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        Log_normal_H_reg_3958 <= Log_normal_H_fu_2320_p3;
        newSel4_reg_3998 <= newSel4_fu_3056_p3;
        or_cond3_reg_3988 <= or_cond3_fu_2992_p2;
        p_result_3_3_reg_3973 <= p_result_3_3_fu_2830_p2;
        p_result_4_3_reg_3968 <= p_result_4_3_fu_2696_p2;
        p_result_5_3_reg_3963 <= p_result_5_3_fu_2658_p2;
        p_val8_6_reg_4003 <= p_val8_6_fu_3132_p3;
        sel_tmp44_reg_3978 <= sel_tmp44_fu_2918_p2;
        sel_tmp47_reg_3983 <= sel_tmp47_fu_2936_p2;
        tmp_282_reg_3993 <= tmp_282_fu_3048_p3;
        tmp_292_reg_4008 <= {{p_val8_6_fu_3132_p3[7:4]}};
        tmp_300_reg_4013 <= tmp_300_fu_3150_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((small_reg_3799 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        Log_normal_L_1_reg_3903 <= Log_normal_L_1_fu_2000_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        Log_normal_L_reg_3889 <= Log_normal_L_fu_1993_p3;
        p_result_3_2_reg_3940 <= p_result_3_2_fu_2196_p2;
        p_result_4_2_reg_3928 <= p_result_4_2_fu_2118_p2;
        p_result_5_2_reg_3919 <= p_result_5_2_fu_2068_p2;
        sel_tmp27_reg_3935 <= sel_tmp27_fu_2140_p2;
        tmp_222_reg_3948 <= tmp_222_fu_2268_p3;
        tmp_232_reg_3953 <= tmp_232_fu_2312_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_range_red_fu_446_ap_done == 1'b1))) begin
        absZ0s_reg_3815 <= absZ0s_fu_1691_p1;
        almostLog_H_reg_3805 <= grp_range_red_fu_446_ap_return_1;
        almostLog_L_reg_3810 <= grp_range_red_fu_446_ap_return_2;
        lzo_reg_3788 <= lzo_fu_1611_p2;
        shiftval_reg_3793 <= shiftval_fu_1621_p2;
        small_reg_3799 <= small_fu_1649_p2;
        squarerIn_reg_3821 <= squarerIn_fu_1717_p3;
        tmp_248_reg_3826 <= tmp_248_fu_1725_p1;
        tmp_249_reg_3831 <= tmp_249_fu_1729_p1;
        tmp_255_reg_3836 <= tmp_255_fu_1733_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_122_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_123_reg_3690 <= tmp_123_fu_631_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_123_fu_631_p2 == 1'd0) & (tmp_122_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_124_reg_3694 <= tmp_124_fu_637_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_124_fu_637_p2 == 1'd0) & (tmp_123_fu_631_p2 == 1'd0) & (tmp_122_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_125_reg_3698 <= tmp_125_fu_643_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_136_fu_649_p3 == 1'd0) & (tmp_125_fu_643_p2 == 1'd0) & (tmp_124_fu_637_p2 == 1'd0) & (tmp_123_fu_631_p2 == 1'd0) & (tmp_122_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_126_reg_3706 <= tmp_126_fu_657_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_125_fu_643_p2 == 1'd0) & (tmp_124_fu_637_p2 == 1'd0) & (tmp_123_fu_631_p2 == 1'd0) & (tmp_122_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_136_reg_3702 <= fpX_fu_484_p1[32'd63];
    end
end

always @ (posedge ap_clk) begin
    if (((sR_reg_3671 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_192_reg_3879 <= tmp_192_fu_1952_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((sR_reg_3671 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_194_reg_3884 <= tmp_194_fu_1958_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((sR_reg_3671 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_198_reg_3909 <= tmp_198_fu_2034_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((sR_reg_3671 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_199_reg_3914 <= tmp_199_fu_2044_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((small_reg_3799 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        tmp_330_reg_4023 <= tmp_330_fu_3338_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_126_reg_3706 == 1'd0) & (tmp_136_reg_3702 == 1'd0) & (tmp_125_reg_3698 == 1'd0) & (tmp_124_reg_3694 == 1'd0) & (tmp_123_reg_3690 == 1'd0) & (tmp_122_reg_3686 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_phi_mux_p_0_phi_fu_425_p14 = tmp_339_fu_3643_p1;
    end else begin
        ap_phi_mux_p_0_phi_fu_425_p14 = p_0_reg_418;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((tmp_126_fu_657_p2 == 1'd0) & (tmp_136_fu_649_p3 == 1'd0) & (tmp_125_fu_643_p2 == 1'd0) & (tmp_124_fu_637_p2 == 1'd0) & (tmp_123_fu_631_p2 == 1'd0) & (tmp_122_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & ((tmp_122_fu_625_p2 == 1'd1) | ((tmp_123_fu_631_p2 == 1'd1) | ((tmp_124_fu_637_p2 == 1'd1) | ((tmp_125_fu_643_p2 == 1'd1) | ((tmp_126_fu_657_p2 == 1'd1) | (tmp_136_fu_649_p3 == 1'd1)))))))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_range_red_fu_446_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign E0_sub_1_fu_3443_p3 = ((tmp_349_fu_3437_p2[0:0] === 1'b1) ? E0_sub_fu_3429_p3 : 2'd1);

assign E0_sub_fu_3429_p3 = ((tmp_348_fu_3413_p3[0:0] === 1'b1) ? 2'd3 : 2'd2);

assign EFR_fu_3624_p2 = (tmp_512_cast_fu_3601_p1 + tmp_515_cast_fu_3620_p1);

assign E_fu_571_p2 = (tmp_208_cast_fu_561_p4 - tmp_207_cast_fu_557_p1);

assign E_normal_H_2_fu_3259_p3 = ((tmp_297_fu_3253_p2[0:0] === 1'b1) ? tmp_300_reg_4013 : E_normal_H_cast_fu_3249_p1);

assign E_normal_H_cast_fu_3249_p1 = E_normal_H_fu_3243_p2;

assign E_normal_H_fu_3243_p2 = (tmp_295_fu_3230_p7 ^ 6'd1);

assign E_normal_L_cast_fu_2636_p1 = E_normal_L_fu_2630_p2;

assign E_normal_L_fu_2630_p2 = (tmp_245_fu_2617_p7 ^ 6'd1);

assign E_small_fu_3463_p2 = (tmp_490_cast_fu_3459_p1 - lzo_cast_fu_3346_p1);

assign FirstBit_fu_496_p3 = fpX_fu_484_p1[32'd51];

assign Log1p_normal_1_cast_fu_1775_p1 = Log1p_normal_fu_1770_p2;

assign Log1p_normal_fu_1770_p2 = (tmp_248_reg_3826 - tmp_185_fu_1766_p1);

assign LogF_normal_H_2_fu_1944_p3 = ((tmp_265_fu_1930_p3[0:0] === 1'b1) ? tmp_190_fu_1938_p2 : LogF_normal_H_fu_1891_p2);

assign LogF_normal_H_cast_fu_1896_p2 = (tmp_255_reg_3836 + tmp_188_fu_1888_p1);

assign LogF_normal_H_fu_1891_p2 = (tmp_342_cast_fu_1885_p1 + almostLog_H_reg_3805);

assign LogF_normal_L_2_cast_fu_1901_p1 = LogF_normal_L_2_reg_3841;

assign LogF_normal_L_2_fu_1788_p2 = (tmp_249_reg_3831 + tmp_187_fu_1779_p1);

assign LogF_normal_L_fu_1783_p2 = (Log1p_normal_1_cast_fu_1775_p1 + almostLog_L_reg_3810);

assign Log_g_fu_3547_p3 = ((small_reg_3799[0:0] === 1'b1) ? tmp_328_fu_3539_p3 : tmp_330_reg_4023);

assign Log_normal_H_fu_2320_p3 = ((sR_reg_3671[0:0] === 1'b1) ? tmp_198_reg_3909 : tmp_199_reg_3914);

assign Log_normal_L_1_cast_fu_3156_p1 = Log_normal_L_1_reg_3903;

assign Log_normal_L_1_fu_2000_p1 = Log_normal_L_fu_1993_p3[59:0];

assign Log_normal_L_cast_fu_2004_p1 = Log_normal_L_fu_1993_p3;

assign Log_normal_L_fu_1993_p3 = ((sR_reg_3671[0:0] === 1'b1) ? tmp_352_cast_fu_1990_p1 : tmp_351_cast_fu_1987_p1);

assign Log_normal_normd_L_fu_3312_p2 = Log_normal_L_1_cast_fu_3156_p1 << tmp_304_fu_3272_p1;

assign Log_small_1_cast_fu_3409_p1 = Log_small_1_fu_3401_p3;

assign Log_small_1_fu_3401_p3 = {{tmp_314_fu_3391_p4}, {3'd0}};

assign Log_small_fu_3384_p3 = ((sR_reg_3671[0:0] === 1'b1) ? tmp_485_cast_fu_3380_p1 : tmp_311_fu_3366_p2);

assign MAN_IN_1_fu_673_p3 = {{tmp_130_fu_663_p4}, {12'd0}};

assign MAN_IN_fu_681_p2 = (64'd18446744073709547520 ^ MAN_IN_1_fu_673_p3);

assign Y0_fu_534_p3 = ((tmp_133_fu_504_p3[0:0] === 1'b1) ? tmp_203_cast_fu_530_p1 : tmp_s_fu_512_p4);

assign Z2o2_cast_fu_1746_p4 = {{Z2o2_full_fu_1740_p2[53:26]}};

assign Z2o2_full_fu_1740_p0 = squarerIn_1_cast_fu_1737_p1;

assign Z2o2_full_fu_1740_p1 = squarerIn_1_cast_fu_1737_p1;

assign Z2o2_full_fu_1740_p2 = (Z2o2_full_fu_1740_p0 * Z2o2_full_fu_1740_p1);

assign Z2o2_small_cast_fu_3352_p1 = Z2o2_small_reg_3852;

assign Z2o2_small_fu_1823_p3 = ((tmp_309_fu_1801_p2[0:0] === 1'b1) ? 31'd0 : phitmp1_fu_1815_p3);

assign Z_small_cast_fu_3362_p1 = Z_small_fu_3355_p3;

assign Z_small_fu_3355_p3 = {{absZ0s_reg_3815}, {33'd0}};

assign absELog2_H_fu_1967_p2 = (tmp_231_cast_fu_1964_p1 + tmp_229_cast_reg_3858);

assign absELog2_pad_H_cast1_fu_1979_p1 = absELog2_pad_H_fu_1972_p3;

assign absELog2_pad_H_cast_fu_1983_p1 = absELog2_pad_H_fu_1972_p3;

assign absELog2_pad_H_fu_1972_p3 = {{absELog2_H_fu_1967_p2}, {tmp_345_cast_reg_3868}};

assign absELog2_pad_L_cast_fu_1926_p1 = absELog2_pad_L_fu_1918_p3;

assign absELog2_pad_L_fu_1918_p3 = {{tmp_258_fu_1914_p1}, {26'd0}};

assign absE_fu_617_p3 = ((sR_fu_605_p2[0:0] === 1'b1) ? tmp_121_fu_611_p2 : E_fu_571_p2);

assign absZ0_fu_1659_p3 = ((sR_reg_3671[0:0] === 1'b1) ? tmp_178_fu_1654_p2 : tmp_221_reg_3777);

assign absZ0s_fu_1691_p1 = tmp_182_fu_1685_p2[24:0];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_return = ap_phi_mux_p_0_phi_fu_425_p14;

assign doRR_fu_1635_p3 = tmp_173_fu_1631_p1[8'd6];

assign fpX_fu_484_p1 = x;

assign grp_range_red_fu_446_ap_start = grp_range_red_fu_446_ap_start_reg;

assign lzo_1_in_fu_1604_p3 = ((FirstBit_reg_3661[0:0] === 1'b1) ? tmp_160_fu_1531_p7 : tmp_172_fu_1592_p7);

assign lzo_cast1_fu_1617_p1 = lzo_fu_1611_p2;

assign lzo_cast_fu_3346_p1 = lzo_reg_3788;

assign lzo_fu_1611_p2 = (lzo_1_in_fu_1604_p3 ^ 6'd1);

assign m0_fu_1862_p2 = (tmp_228_cast_fu_1858_p1 + tmp_225_cast_fu_1843_p1);

assign m1_fu_3648_p0 = 20'd177;

assign m1_fu_3648_p1 = m1_fu_3648_p10;

assign m1_fu_3648_p10 = absE_reg_3680;

assign newSel1_fu_2152_p3 = ((sel_tmp28_fu_2146_p2[0:0] === 1'b1) ? 6'd20 : 6'd36);

assign newSel236_v_v_fu_1119_p3 = ((p_result_3_fu_915_p2[0:0] === 1'b1) ? p_in79_v_pn_fu_1009_p3 : 6'd60);

assign newSel238_v_fu_1139_p2 = MAN_IN_fu_681_p2 >> newSel238_v_v_cast_fu_1135_p1;

assign newSel238_v_v_cast_fu_1135_p1 = newSel238_v_v_fu_1127_p3;

assign newSel238_v_v_fu_1127_p3 = ((or_cond_fu_1113_p2[0:0] === 1'b1) ? newSel_v_v_fu_1105_p3 : newSel236_v_v_fu_1119_p3);

assign newSel242_cast_cast_fu_2166_p3 = ((tmp_207_fu_2134_p2[0:0] === 1'b1) ? 6'd4 : 6'd52);

assign newSel244_cast_fu_2182_p1 = newSel2_fu_2174_p3;

assign newSel258_cast_fu_3022_p3 = ((tmp_273_fu_2888_p2[0:0] === 1'b1) ? 4'd0 : tmp_278_fu_3012_p4);

assign newSel2_fu_2174_p3 = ((or_cond1_fu_2160_p2[0:0] === 1'b1) ? newSel1_fu_2152_p3 : newSel242_cast_cast_fu_2166_p3);

assign newSel3_fu_2998_p3 = ((sel_tmp43_fu_2912_p2[0:0] === 1'b1) ? 4'd0 : tmp_425_cast_fu_2836_p4);

assign newSel4_fu_3056_p3 = ((or_cond5_fu_3006_p2[0:0] === 1'b1) ? newSel3_fu_2998_p3 : newSel258_cast_fu_3022_p3);

assign newSel_v_v_fu_1105_p3 = ((p_result_5_fu_697_p2[0:0] === 1'b1) ? p_in4_v_cast_fu_1097_p3 : 6'd44);

assign not_tmp_s_fu_599_p2 = ((tmp_120_fu_577_p3 != 63'd4607182418800017408) ? 1'b1 : 1'b0);

assign or_cond1_fu_2160_p2 = (p_result_5_2_fu_2068_p2 ^ p_result_4_2_fu_2118_p2);

assign or_cond2_fu_2798_p2 = (p_result_5_3_fu_2658_p2 ^ p_result_4_3_fu_2696_p2);

assign or_cond3_fu_2992_p2 = (sel_tmp50_fu_2960_p2 | sel_tmp48_fu_2942_p2);

assign or_cond4_fu_3159_p2 = (sel_tmp47_reg_3983 | sel_tmp44_reg_3978);

assign or_cond5_fu_3006_p2 = (sel_tmp43_fu_2912_p2 | sel_tmp41_fu_2900_p2);

assign or_cond6_fu_3163_p2 = (or_cond4_fu_3159_p2 | or_cond3_reg_3988);

assign or_cond_fu_1113_p2 = (sel_tmp8_fu_1091_p2 | sel_tmp6_fu_1073_p2);

assign p_in1_fu_2186_p2 = Log_normal_L_cast_fu_2004_p1 >> newSel244_cast_fu_2182_p1;

assign p_in2_fu_859_p3 = ((p_result_5_1_fu_713_p2[0:0] === 1'b1) ? tmp_244_cast_fu_841_p3 : tmp_245_cast_fu_849_p4);

assign p_in4_v_cast_fu_1097_p3 = ((sel_tmp8_fu_1091_p2[0:0] === 1'b1) ? 6'd28 : 6'd12);

assign p_in5_fu_1001_p3 = ((p_result_5_1_fu_713_p2[0:0] === 1'b1) ? 4'd0 : tmp_256_cast_fu_991_p4);

assign p_in78_v_fu_983_p3 = ((p_result_5_fu_697_p2[0:0] === 1'b1) ? 6'd20 : 6'd52);

assign p_in79_v_fu_975_p3 = ((p_result_5_fu_697_p2[0:0] === 1'b1) ? 6'd4 : 6'd36);

assign p_in79_v_pn_fu_1009_p3 = ((p_result_4_fu_755_p2[0:0] === 1'b1) ? p_in79_v_fu_975_p3 : p_in78_v_fu_983_p3);

assign p_in7_fu_2106_p3 = ((p_result_5_2_fu_2068_p2[0:0] === 1'b1) ? tmp_203_fu_2084_p1 : sf_cast_fu_2102_p1);

assign p_in8_fu_1295_p3 = ((sel_tmp23_fu_1289_p2[0:0] === 1'b1) ? tmp_267_cast_fu_1047_p4 : sel_tmp21_fu_1269_p3);

assign p_in_fu_785_p3 = ((p_result_5_1_fu_713_p2[0:0] === 1'b1) ? st2_fu_761_p4 : tmp_139_cast_fu_781_p1);

assign p_result_1_1_fu_1562_p2 = ((tmp_195_fu_1552_p4 == 2'd0) ? 1'b1 : 1'b0);

assign p_result_1_2_fu_2587_p2 = ((tmp_303_fu_2577_p4 == 2'd0) ? 1'b1 : 1'b0);

assign p_result_1_3_fu_3200_p2 = ((tmp_338_fu_3190_p4 == 2'd0) ? 1'b1 : 1'b0);

assign p_result_1_fu_1501_p2 = ((tmp_189_fu_1491_p4 == 2'd0) ? 1'b1 : 1'b0);

assign p_result_2_1_fu_1303_p2 = ((p_in8_fu_1295_p3 == 4'd0) ? 1'b1 : 1'b0);

assign p_result_2_2_fu_2465_p2 = ((tmp_227_fu_2457_p3 == 4'd0) ? 1'b1 : 1'b0);

assign p_result_2_3_fu_3174_p2 = ((tmp_283_fu_3168_p3 == 4'd0) ? 1'b1 : 1'b0);

assign p_result_2_fu_1149_p2 = ((tmp_175_fu_1145_p1 == 4'd0) ? 1'b1 : 1'b0);

assign p_result_3_1_fu_969_p2 = ((tmp_145_fu_961_p3 == 8'd0) ? 1'b1 : 1'b0);

assign p_result_3_2_fu_2196_p2 = ((tmp_298_fu_2192_p1 == 8'd0) ? 1'b1 : 1'b0);

assign p_result_3_3_fu_2830_p2 = ((tmp_267_fu_2822_p3 == 8'd0) ? 1'b1 : 1'b0);

assign p_result_3_fu_915_p2 = ((tmp_141_fu_907_p3 == 8'd0) ? 1'b1 : 1'b0);

assign p_result_4_1_fu_797_p2 = ((tmp_174_fu_793_p1 == 16'd0) ? 1'b1 : 1'b0);

assign p_result_4_2_fu_2118_p2 = ((tmp_296_fu_2114_p1 == 16'd0) ? 1'b1 : 1'b0);

assign p_result_4_3_fu_2696_p2 = ((tmp_324_fu_2692_p1 == 16'd0) ? 1'b1 : 1'b0);

assign p_result_4_fu_755_p2 = ((tmp_162_fu_751_p1 == 16'd0) ? 1'b1 : 1'b0);

assign p_result_5_1_fu_713_p2 = ((tmp_149_fu_703_p4 == 32'd0) ? 1'b1 : 1'b0);

assign p_result_5_2_fu_2068_p2 = ((tmp_201_fu_2060_p3 == 60'd0) ? 1'b1 : 1'b0);

assign p_result_5_3_fu_2658_p2 = ((tmp_247_fu_2650_p3 == 34'd0) ? 1'b1 : 1'b0);

assign p_result_5_fu_697_p2 = ((tmp_139_fu_687_p4 == 32'd0) ? 1'b1 : 1'b0);

assign p_v1_fu_2684_p3 = ((p_result_5_3_fu_2658_p2[0:0] === 1'b1) ? tmp_321_fu_2664_p2 : tmp_251_fu_2680_p1);

assign p_v_fu_743_p3 = ((p_result_5_fu_697_p2[0:0] === 1'b1) ? st1_fu_719_p4 : tmp_136_cast_fu_739_p1);

assign p_val8_1_fu_1485_p3 = ((p_result_2_reg_3740[0:0] === 1'b1) ? p_val8_reg_3752 : tmp_158_fu_1482_p1);

assign p_val8_2_fu_1443_p3 = ((sel_tmp23_fu_1289_p2[0:0] === 1'b1) ? tmp_144_fu_951_p4 : tmp_168_fu_1435_p3);

assign p_val8_3_fu_1546_p3 = ((p_result_2_1_reg_3746[0:0] === 1'b1) ? p_val8_2_reg_3762 : tmp_170_fu_1543_p1);

assign p_val8_4_fu_2547_p3 = ((sel_tmp37_fu_2376_p2[0:0] === 1'b1) ? tmp_241_fu_2538_p4 : tmp_240_fu_2530_p3);

assign p_val8_5_fu_2569_p3 = ((p_result_2_2_fu_2465_p2[0:0] === 1'b1) ? p_val8_4_fu_2547_p3 : tmp_243_fu_2565_p1);

assign p_val8_6_fu_3132_p3 = ((sel_tmp50_fu_2960_p2[0:0] === 1'b1) ? tmp_261_fu_2772_p3 : tmp_291_fu_3124_p3);

assign p_val8_7_fu_3183_p3 = ((p_result_2_3_fu_3174_p2[0:0] === 1'b1) ? p_val8_6_reg_4003 : tmp_293_fu_3180_p1);

assign p_val8_fu_1373_p3 = ((sel_tmp8_fu_1091_p2[0:0] === 1'b1) ? tmp_246_cast_fu_867_p4 : sel_tmp25_fu_1365_p3);

assign phitmp1_fu_1815_p3 = {{tmp_310_fu_1809_p2}, {3'd0}};

assign phitmp_fu_593_p2 = (tmp_135_fu_585_p3 ^ 1'd1);

assign res_fp_fu_3637_p2 = (tmp_337_fu_3630_p3 | EFR_fu_3624_p2);

assign sR_fu_605_p2 = (phitmp_fu_593_p2 & not_tmp_s_fu_599_p2);

assign sel_tmp10_fu_1197_p2 = (sel_tmp3_fu_939_p2 & p_result_3_1_fu_969_p2);

assign sel_tmp11_fu_1203_p2 = (sel_tmp10_fu_1197_p2 & p_result_5_1_fu_713_p2);

assign sel_tmp121_demorgan_fu_2366_p2 = (p_result_4_2_reg_3928 | p_result_3_2_reg_3940);

assign sel_tmp12_fu_1209_p3 = ((sel_tmp11_fu_1203_p2[0:0] === 1'b1) ? tmp_262_cast_fu_1017_p4 : sel_tmp9_fu_1189_p3);

assign sel_tmp13_fu_1217_p2 = (p_result_5_1_fu_713_p2 ^ 1'd1);

assign sel_tmp14_fu_1223_p2 = (sel_tmp13_fu_1217_p2 & sel_tmp10_fu_1197_p2);

assign sel_tmp15_fu_1229_p3 = ((sel_tmp14_fu_1223_p2[0:0] === 1'b1) ? tmp_263_cast_fu_1027_p4 : sel_tmp12_fu_1209_p3);

assign sel_tmp16_fu_1237_p2 = (p_result_3_1_fu_969_p2 ^ 1'd1);

assign sel_tmp17_fu_1243_p2 = (sel_tmp16_fu_1237_p2 & p_result_4_1_fu_797_p2);

assign sel_tmp185_demorgan_fu_2948_p2 = (p_result_4_3_fu_2696_p2 | p_result_3_3_fu_2830_p2);

assign sel_tmp18_fu_1249_p2 = (sel_tmp17_fu_1243_p2 & p_result_5_1_fu_713_p2);

assign sel_tmp19_fu_1255_p3 = ((sel_tmp18_fu_1249_p2[0:0] === 1'b1) ? tmp_140_fu_831_p4 : sel_tmp15_fu_1229_p3);

assign sel_tmp1_fu_895_p2 = (p_result_4_fu_755_p2 ^ 1'd1);

assign sel_tmp20_fu_1263_p2 = (sel_tmp17_fu_1243_p2 & sel_tmp13_fu_1217_p2);

assign sel_tmp21_fu_1269_p3 = ((sel_tmp20_fu_1263_p2[0:0] === 1'b1) ? tmp_266_cast_fu_1037_p4 : sel_tmp19_fu_1255_p3);

assign sel_tmp22_fu_1283_p2 = (sel_tmp55_demorgan_fu_1277_p2 ^ 1'd1);

assign sel_tmp23_fu_1289_p2 = (sel_tmp22_fu_1283_p2 & p_result_5_1_fu_713_p2);

assign sel_tmp24_fu_1357_p3 = ((p_result_3_fu_915_p2[0:0] === 1'b1) ? tmp_155_fu_1349_p3 : tmp_248_cast_fu_877_p4);

assign sel_tmp25_fu_1365_p3 = ((sel_tmp6_fu_1073_p2[0:0] === 1'b1) ? tmp_134_fu_823_p3 : sel_tmp24_fu_1357_p3);

assign sel_tmp26_fu_2325_p2 = (p_result_5_2_reg_3919 ^ 1'd1);

assign sel_tmp27_fu_2140_p2 = (p_result_4_2_fu_2118_p2 ^ 1'd1);

assign sel_tmp28_fu_2146_p2 = (sel_tmp27_fu_2140_p2 & p_result_5_2_fu_2068_p2);

assign sel_tmp29_fu_2330_p2 = (sel_tmp27_reg_3935 & p_result_3_2_reg_3940);

assign sel_tmp2_fu_901_p2 = (sel_tmp1_fu_895_p2 & p_result_5_fu_697_p2);

assign sel_tmp30_demorgan_fu_1079_p2 = (p_result_4_fu_755_p2 | p_result_3_fu_915_p2);

assign sel_tmp30_fu_2334_p2 = (sel_tmp29_fu_2330_p2 & p_result_5_2_reg_3919);

assign sel_tmp31_fu_2339_p2 = (sel_tmp29_fu_2330_p2 & sel_tmp26_fu_2325_p2);

assign sel_tmp32_fu_2345_p2 = (p_result_3_2_reg_3940 ^ 1'd1);

assign sel_tmp33_fu_2350_p2 = (sel_tmp32_fu_2345_p2 & p_result_4_2_reg_3928);

assign sel_tmp34_fu_2355_p2 = (sel_tmp33_fu_2350_p2 & p_result_5_2_reg_3919);

assign sel_tmp35_fu_2360_p2 = (sel_tmp33_fu_2350_p2 & sel_tmp26_fu_2325_p2);

assign sel_tmp36_fu_2370_p2 = (sel_tmp121_demorgan_fu_2366_p2 ^ 1'd1);

assign sel_tmp37_fu_2376_p2 = (sel_tmp36_fu_2370_p2 & p_result_5_2_reg_3919);

assign sel_tmp38_fu_2750_p2 = (p_result_5_3_fu_2658_p2 ^ 1'd1);

assign sel_tmp39_fu_2756_p2 = (p_result_4_3_fu_2696_p2 ^ 1'd1);

assign sel_tmp3_fu_939_p2 = (p_result_4_1_fu_797_p2 ^ 1'd1);

assign sel_tmp40_fu_2762_p2 = (sel_tmp39_fu_2756_p2 & p_result_5_3_fu_2658_p2);

assign sel_tmp41_fu_2900_p2 = (tmp_274_fu_2894_p2 & sel_tmp38_fu_2750_p2);

assign sel_tmp42_fu_2906_p2 = (sel_tmp39_fu_2756_p2 & p_result_3_3_fu_2830_p2);

assign sel_tmp43_fu_2912_p2 = (sel_tmp42_fu_2906_p2 & p_result_5_3_fu_2658_p2);

assign sel_tmp44_fu_2918_p2 = (sel_tmp42_fu_2906_p2 & sel_tmp38_fu_2750_p2);

assign sel_tmp45_fu_2924_p2 = (p_result_3_3_fu_2830_p2 ^ 1'd1);

assign sel_tmp46_fu_2930_p2 = (sel_tmp45_fu_2924_p2 & p_result_4_3_fu_2696_p2);

assign sel_tmp47_fu_2936_p2 = (sel_tmp46_fu_2930_p2 & p_result_5_3_fu_2658_p2);

assign sel_tmp48_fu_2942_p2 = (sel_tmp46_fu_2930_p2 & sel_tmp38_fu_2750_p2);

assign sel_tmp49_fu_2954_p2 = (sel_tmp185_demorgan_fu_2948_p2 ^ 1'd1);

assign sel_tmp4_fu_945_p2 = (sel_tmp3_fu_939_p2 & p_result_5_1_fu_713_p2);

assign sel_tmp50_fu_2960_p2 = (sel_tmp49_fu_2954_p2 & p_result_5_3_fu_2658_p2);

assign sel_tmp55_demorgan_fu_1277_p2 = (p_result_4_1_fu_797_p2 | p_result_3_1_fu_969_p2);

assign sel_tmp5_fu_1067_p2 = (p_result_3_fu_915_p2 ^ 1'd1);

assign sel_tmp6_fu_1073_p2 = (sel_tmp5_fu_1067_p2 & p_result_4_fu_755_p2);

assign sel_tmp7_fu_1085_p2 = (sel_tmp30_demorgan_fu_1079_p2 ^ 1'd1);

assign sel_tmp8_fu_1091_p2 = (sel_tmp7_fu_1085_p2 & p_result_5_fu_697_p2);

assign sel_tmp9_fu_1189_p3 = ((tmp_150_fu_1183_p2[0:0] === 1'b1) ? p_in5_fu_1001_p3 : tmp_269_cast_fu_1057_p4);

assign sel_tmp_fu_887_p3 = ((p_result_4_fu_755_p2[0:0] === 1'b1) ? tmp_134_fu_823_p3 : tmp_248_cast_fu_877_p4);

assign sf_cast_fu_2102_p1 = $unsigned(tmp_205_fu_2098_p1);

assign shiftval_cast_fu_1627_p1 = shiftval_fu_1621_p2;

assign shiftval_fu_1621_p2 = ($signed(7'd100) + $signed(lzo_cast1_fu_1617_p1));

assign small_fu_1649_p2 = (tmp_177_fu_1643_p2 & tmp_176_reg_3772);

assign squarerIn_1_cast_fu_1737_p1 = squarerIn_reg_3821;

assign squarerIn_fu_1717_p3 = ((doRR_fu_1635_p3[0:0] === 1'b1) ? tmp_336_cast_fu_1695_p4 : tmp_339_cast_fu_1713_p1);

assign st1_fu_719_p4 = {{MAN_IN_fu_681_p2[63:16]}};

assign st2_fu_761_p4 = {{Y0_fu_534_p3[53:5]}};

assign sticky_fu_3557_p2 = ((tmp_353_fu_3553_p1 != 4'd0) ? 1'b1 : 1'b0);

assign tmp196_fu_2039_p2 = (absELog2_pad_H_cast1_fu_1979_p1 + LogF_normal_H_2_reg_3873);

assign tmp_117_fu_522_p3 = {{1'd1}, {tmp_128_fu_492_p1}};

assign tmp_118_fu_543_p2 = (1'd1 ^ FirstBit_fu_496_p3);

assign tmp_119_fu_549_p3 = {{9'd511}, {tmp_118_fu_543_p2}};

assign tmp_120_fu_577_p3 = {{tmp_208_cast_fu_561_p4}, {52'd0}};

assign tmp_121_fu_611_p2 = (11'd0 - E_fu_571_p2);

assign tmp_122_fu_625_p2 = ((tmp_fu_488_p1 == 63'd0) ? 1'b1 : 1'b0);

assign tmp_123_fu_631_p2 = ((fpX_fu_484_p1 == 64'd9218868437227405312) ? 1'b1 : 1'b0);

assign tmp_124_fu_637_p2 = ((fpX_fu_484_p1 == 64'd18442240474082181120) ? 1'b1 : 1'b0);

assign tmp_125_fu_643_p2 = ((E_fu_571_p2 == 11'd2047) ? 1'b1 : 1'b0);

assign tmp_126_fu_657_p2 = ((fpX_fu_484_p1 == 64'd4607182418800017408) ? 1'b1 : 1'b0);

assign tmp_127_fu_1837_p1 = tmp_127_fu_1837_p10;

assign tmp_127_fu_1837_p10 = absE_reg_3680;

assign tmp_127_fu_1837_p2 = (59'd250894535073523 * tmp_127_fu_1837_p1);

assign tmp_128_fu_492_p1 = fpX_fu_484_p1[51:0];

assign tmp_129_fu_1850_p3 = {{tmp_137_fu_1847_p1}, {49'd0}};

assign tmp_130_fu_663_p4 = {{Y0_fu_534_p3[52:1]}};

assign tmp_131_fu_803_p4 = {{MAN_IN_fu_681_p2[15:8]}};

assign tmp_132_fu_813_p4 = {{MAN_IN_fu_681_p2[47:40]}};

assign tmp_133_fu_504_p3 = fpX_fu_484_p1[32'd51];

assign tmp_134_fu_823_p3 = ((p_result_5_fu_697_p2[0:0] === 1'b1) ? tmp_131_fu_803_p4 : tmp_132_fu_813_p4);

assign tmp_135_fu_585_p3 = fpX_fu_484_p1[32'd62];

assign tmp_136_cast_fu_739_p1 = tmp_156_fu_729_p4;

assign tmp_136_fu_649_p3 = fpX_fu_484_p1[32'd63];

assign tmp_137_fu_1847_p1 = m1_fu_3648_p2[10:0];

assign tmp_139_cast_fu_781_p1 = tmp_163_fu_771_p4;

assign tmp_139_fu_687_p4 = {{MAN_IN_fu_681_p2[63:32]}};

assign tmp_140_fu_831_p4 = {{Y0_fu_534_p3[4:1]}};

assign tmp_141_fu_907_p3 = ((sel_tmp2_fu_901_p2[0:0] === 1'b1) ? tmp_246_cast_fu_867_p4 : sel_tmp_fu_887_p3);

assign tmp_142_fu_921_p4 = {{Y0_fu_534_p3[52:45]}};

assign tmp_143_fu_931_p3 = ((p_result_4_1_fu_797_p2[0:0] === 1'b1) ? p_in2_fu_859_p3 : tmp_142_fu_921_p4);

assign tmp_144_fu_951_p4 = {{Y0_fu_534_p3[20:13]}};

assign tmp_145_fu_961_p3 = ((sel_tmp4_fu_945_p2[0:0] === 1'b1) ? tmp_144_fu_951_p4 : tmp_143_fu_931_p3);

assign tmp_146_fu_1159_p2 = (tmp_181_fu_1155_p1 | tmp_145_fu_961_p3);

assign tmp_147_fu_1165_p4 = {{p_in_fu_785_p3[15:8]}};

assign tmp_148_fu_1175_p3 = {{tmp_147_fu_1165_p4}, {tmp_146_fu_1159_p2}};

assign tmp_149_fu_703_p4 = {{Y0_fu_534_p3[52:21]}};

assign tmp_150_fu_1183_p2 = ((tmp_148_fu_1175_p3 == 16'd0) ? 1'b1 : 1'b0);

assign tmp_151_fu_1309_p4 = {{MAN_IN_fu_681_p2[39:32]}};

assign tmp_152_fu_1319_p3 = ((p_result_5_fu_697_p2[0:0] === 1'b1) ? 8'd0 : tmp_151_fu_1309_p4);

assign tmp_153_fu_1331_p4 = {{Y0_fu_534_p3[28:21]}};

assign tmp_154_fu_1341_p3 = ((p_result_5_1_fu_713_p2[0:0] === 1'b1) ? 8'd0 : tmp_153_fu_1331_p4);

assign tmp_155_fu_1349_p3 = ((p_result_4_fu_755_p2[0:0] === 1'b1) ? tmp_152_fu_1319_p3 : tmp_186_fu_1327_p1);

assign tmp_156_fu_729_p4 = {{MAN_IN_fu_681_p2[63:48]}};

assign tmp_158_fu_1482_p1 = tmp_157_reg_3757;

assign tmp_159_fu_1523_p3 = ((p_result_1_fu_1501_p2[0:0] === 1'b1) ? tmp_191_fu_1507_p3 : tmp_193_fu_1515_p3);

assign tmp_160_fu_1531_p7 = {{{{{{p_result_5_reg_3710}, {p_result_4_reg_3720}}, {p_result_3_reg_3730}}, {p_result_2_reg_3740}}, {p_result_1_fu_1501_p2}}, {tmp_159_fu_1523_p3}};

assign tmp_161_fu_1391_p3 = ((tmp_150_fu_1183_p2[0:0] === 1'b1) ? tmp_154_fu_1341_p3 : tmp_142_fu_921_p4);

assign tmp_162_fu_751_p1 = p_v_fu_743_p3[15:0];

assign tmp_163_fu_771_p4 = {{Y0_fu_534_p3[53:37]}};

assign tmp_164_fu_1399_p4 = {{Y0_fu_534_p3[12:5]}};

assign tmp_165_fu_1409_p3 = ((sel_tmp11_fu_1203_p2[0:0] === 1'b1) ? tmp_164_fu_1399_p4 : tmp_161_fu_1391_p3);

assign tmp_166_fu_1417_p4 = {{Y0_fu_534_p3[44:37]}};

assign tmp_167_fu_1427_p3 = ((sel_tmp14_fu_1223_p2[0:0] === 1'b1) ? tmp_166_fu_1417_p4 : tmp_165_fu_1409_p3);

assign tmp_168_fu_1435_p3 = ((sel_tmp17_fu_1243_p2[0:0] === 1'b1) ? p_in2_fu_859_p3 : tmp_167_fu_1427_p3);

assign tmp_170_fu_1543_p1 = tmp_169_reg_3767;

assign tmp_171_fu_1584_p3 = ((p_result_1_1_fu_1562_p2[0:0] === 1'b1) ? tmp_196_fu_1568_p3 : tmp_211_fu_1576_p3);

assign tmp_172_fu_1592_p7 = {{{{{{p_result_5_1_reg_3715}, {p_result_4_1_reg_3725}}, {p_result_3_1_reg_3735}}, {p_result_2_1_reg_3746}}, {p_result_1_1_fu_1562_p2}}, {tmp_171_fu_1584_p3}};

assign tmp_173_fu_1631_p1 = $unsigned(shiftval_cast_fu_1627_p1);

assign tmp_174_fu_793_p1 = p_in_fu_785_p3[15:0];

assign tmp_175_fu_1145_p1 = newSel238_v_fu_1139_p2[3:0];

assign tmp_176_fu_1461_p2 = ((tmp_208_cast_fu_561_p4 == tmp_207_cast_fu_557_p1) ? 1'b1 : 1'b0);

assign tmp_177_fu_1643_p2 = (doRR_fu_1635_p3 ^ 1'd1);

assign tmp_178_fu_1654_p2 = (26'd0 - tmp_221_reg_3777);

assign tmp_179_fu_1677_p1 = absZ0_fu_1659_p3;

assign tmp_180_fu_1681_p1 = $unsigned(shiftval_fu_1621_p2);

assign tmp_181_fu_1155_p1 = p_in_fu_785_p3[7:0];

assign tmp_182_fu_1685_p2 = tmp_179_fu_1677_p1 << tmp_180_fu_1681_p1;

assign tmp_183_fu_1705_p3 = {{absZ0s_fu_1691_p1}, {1'd0}};

assign tmp_184_fu_1756_p4 = {{Z2o2_full_fu_1740_p2[53:28]}};

assign tmp_185_fu_1766_p1 = tmp_184_fu_1756_p4;

assign tmp_186_fu_1327_p1 = p_v_fu_743_p3[7:0];

assign tmp_187_fu_1779_p1 = Log1p_normal_fu_1770_p2;

assign tmp_188_fu_1888_p1 = tmp_254_reg_3846;

assign tmp_189_fu_1491_p4 = {{p_val8_1_fu_1485_p3[3:2]}};

assign tmp_190_fu_1938_p2 = (64'd17171480576 | LogF_normal_H_fu_1891_p2);

assign tmp_191_fu_1507_p3 = p_val8_1_fu_1485_p3[32'd1];

assign tmp_192_fu_1952_p2 = (LogF_normal_L_2_cast_fu_1901_p1 + absELog2_pad_L_cast_fu_1926_p1);

assign tmp_193_fu_1515_p3 = p_val8_1_fu_1485_p3[32'd3];

assign tmp_194_fu_1958_p2 = (absELog2_pad_L_cast_fu_1926_p1 - LogF_normal_L_2_cast_fu_1901_p1);

assign tmp_195_fu_1552_p4 = {{p_val8_3_fu_1546_p3[3:2]}};

assign tmp_196_fu_1568_p3 = p_val8_3_fu_1546_p3[32'd1];

assign tmp_197_fu_2024_p2 = (absELog2_pad_H_cast_fu_1983_p1 - tmp_354_cast_fu_2020_p1);

assign tmp_198_fu_2034_p2 = ($signed(tmp_355_cast_fu_2030_p1) - $signed(LogF_normal_H_2_reg_3873));

assign tmp_199_fu_2044_p2 = (tmp196_fu_2039_p2 + tmp_354_cast1_fu_2016_p1);

assign tmp_200_fu_2050_p4 = {{Log_normal_L_fu_1993_p3[59:28]}};

assign tmp_201_fu_2060_p3 = {{tmp_200_fu_2050_p4}, {28'd0}};

assign tmp_202_fu_2074_p4 = {{Log_normal_L_fu_1993_p3[61:12]}};

assign tmp_203_cast_fu_530_p1 = tmp_117_fu_522_p3;

assign tmp_203_fu_2084_p1 = $signed(tmp_202_fu_2074_p4);

assign tmp_204_fu_2088_p4 = {{Log_normal_L_fu_1993_p3[61:44]}};

assign tmp_205_fu_2098_p1 = $signed(tmp_204_fu_2088_p4);

assign tmp_206_fu_2124_p4 = {{{tmp_200_fu_2050_p4}, {12'd0}}, {tmp_296_fu_2114_p1}};

assign tmp_207_cast_fu_557_p1 = tmp_119_fu_549_p3;

assign tmp_207_fu_2134_p2 = ((tmp_206_fu_2124_p4 == 60'd0) ? 1'b1 : 1'b0);

assign tmp_208_cast_fu_561_p4 = {{fpX_fu_484_p1[62:52]}};

assign tmp_208_fu_2206_p2 = (tmp_299_fu_2202_p1 | tmp_298_fu_2192_p1);

assign tmp_209_fu_2212_p4 = {{p_in7_fu_2106_p3[15:8]}};

assign tmp_210_fu_2222_p3 = {{tmp_209_fu_2212_p4}, {tmp_208_fu_2206_p2}};

assign tmp_211_fu_1576_p3 = p_val8_3_fu_1546_p3[32'd3];

assign tmp_212_fu_2230_p2 = ((tmp_210_fu_2222_p3 == 16'd0) ? 1'b1 : 1'b0);

assign tmp_213_fu_2381_p4 = {{Log_normal_L_reg_3889[27:24]}};

assign tmp_214_fu_2390_p4 = {{Log_normal_L_reg_3889[43:40]}};

assign tmp_215_fu_2399_p4 = {{Log_normal_L_reg_3889[11:8]}};

assign tmp_216_fu_2408_p4 = {{Log_normal_L_reg_3889[51:48]}};

assign tmp_217_fu_2417_p4 = {{Log_normal_L_reg_3889[19:16]}};

assign tmp_218_fu_2240_p4 = {{Log_normal_L_fu_1993_p3[35:32]}};

assign tmp_219_fu_2250_p3 = ((p_result_5_2_fu_2068_p2[0:0] === 1'b1) ? tmp_302_fu_2236_p1 : tmp_218_fu_2240_p4);

assign tmp_220_fu_2258_p4 = {{Log_normal_L_fu_1993_p3[59:56]}};

assign tmp_221_fu_1467_p1 = Y0_fu_534_p3[25:0];

assign tmp_222_fu_2268_p3 = ((tmp_212_fu_2230_p2[0:0] === 1'b1) ? tmp_219_fu_2250_p3 : tmp_220_fu_2258_p4);

assign tmp_223_fu_2426_p3 = ((sel_tmp30_fu_2334_p2[0:0] === 1'b1) ? tmp_217_fu_2417_p4 : tmp_222_reg_3948);

assign tmp_224_fu_2433_p3 = ((sel_tmp31_fu_2339_p2[0:0] === 1'b1) ? tmp_216_fu_2408_p4 : tmp_223_fu_2426_p3);

assign tmp_225_cast_fu_1843_p1 = tmp_127_fu_1837_p2;

assign tmp_225_fu_2441_p3 = ((sel_tmp34_fu_2355_p2[0:0] === 1'b1) ? tmp_215_fu_2399_p4 : tmp_224_fu_2433_p3);

assign tmp_226_fu_2449_p3 = ((sel_tmp35_fu_2360_p2[0:0] === 1'b1) ? tmp_214_fu_2390_p4 : tmp_225_fu_2441_p3);

assign tmp_227_fu_2457_p3 = ((sel_tmp37_fu_2376_p2[0:0] === 1'b1) ? tmp_213_fu_2381_p4 : tmp_226_fu_2449_p3);

assign tmp_228_cast_fu_1858_p1 = tmp_129_fu_1850_p3;

assign tmp_228_fu_2276_p3 = {{tmp_302_fu_2236_p1}, {4'd0}};

assign tmp_229_fu_2284_p4 = {{Log_normal_L_fu_1993_p3[35:28]}};

assign tmp_230_fu_2294_p3 = ((p_result_5_2_fu_2068_p2[0:0] === 1'b1) ? tmp_228_fu_2276_p3 : tmp_229_fu_2284_p4);

assign tmp_231_cast_fu_1964_p1 = tmp_138_reg_3863;

assign tmp_231_fu_2302_p4 = {{Log_normal_L_fu_1993_p3[59:52]}};

assign tmp_232_fu_2312_p3 = ((tmp_212_fu_2230_p2[0:0] === 1'b1) ? tmp_230_fu_2294_p3 : tmp_231_fu_2302_p4);

assign tmp_233_fu_2471_p4 = {{Log_normal_L_reg_3889[19:12]}};

assign tmp_234_fu_2480_p3 = ((sel_tmp30_fu_2334_p2[0:0] === 1'b1) ? tmp_233_fu_2471_p4 : tmp_232_reg_3953);

assign tmp_235_fu_2487_p4 = {{Log_normal_L_reg_3889[51:44]}};

assign tmp_236_fu_2496_p3 = ((sel_tmp31_fu_2339_p2[0:0] === 1'b1) ? tmp_235_fu_2487_p4 : tmp_234_fu_2480_p3);

assign tmp_237_fu_2504_p4 = {{Log_normal_L_reg_3889[11:4]}};

assign tmp_238_fu_2513_p3 = ((sel_tmp34_fu_2355_p2[0:0] === 1'b1) ? tmp_237_fu_2504_p4 : tmp_236_fu_2496_p3);

assign tmp_239_fu_2521_p4 = {{Log_normal_L_reg_3889[43:36]}};

assign tmp_240_fu_2530_p3 = ((sel_tmp35_fu_2360_p2[0:0] === 1'b1) ? tmp_239_fu_2521_p4 : tmp_238_fu_2513_p3);

assign tmp_241_fu_2538_p4 = {{Log_normal_L_reg_3889[27:20]}};

assign tmp_242_fu_2555_p4 = {{p_val8_4_fu_2547_p3[7:4]}};

assign tmp_243_fu_2565_p1 = tmp_242_fu_2555_p4;

assign tmp_244_cast_fu_841_p3 = {{tmp_140_fu_831_p4}, {4'd0}};

assign tmp_244_fu_2609_p3 = ((p_result_1_2_fu_2587_p2[0:0] === 1'b1) ? tmp_313_fu_2593_p3 : tmp_317_fu_2601_p3);

assign tmp_245_cast_fu_849_p4 = {{Y0_fu_534_p3[36:29]}};

assign tmp_245_fu_2617_p7 = {{{{{{p_result_5_2_reg_3919}, {p_result_4_2_reg_3928}}, {p_result_3_2_reg_3940}}, {p_result_2_2_fu_2465_p2}}, {p_result_1_2_fu_2587_p2}}, {tmp_244_fu_2609_p3}};

assign tmp_246_cast_fu_867_p4 = {{MAN_IN_fu_681_p2[31:24]}};

assign tmp_246_fu_2640_p4 = {{Log_normal_H_fu_2320_p3[33:2]}};

assign tmp_247_fu_2650_p3 = {{tmp_246_fu_2640_p4}, {2'd0}};

assign tmp_248_cast_fu_877_p4 = {{MAN_IN_fu_681_p2[63:56]}};

assign tmp_248_fu_1725_p1 = grp_range_red_fu_446_ap_return_0[54:0];

assign tmp_249_fu_1729_p1 = grp_range_red_fu_446_ap_return_2[59:0];

assign tmp_250_fu_2670_p4 = {{Log_normal_H_fu_2320_p3[63:18]}};

assign tmp_251_fu_2680_p1 = tmp_250_fu_2670_p4;

assign tmp_252_fu_2702_p4 = {{Log_normal_H_fu_2320_p3[15:2]}};

assign tmp_253_fu_2712_p3 = {{tmp_252_fu_2702_p4}, {2'd0}};

assign tmp_255_fu_1733_p1 = grp_range_red_fu_446_ap_return_1[22:0];

assign tmp_256_cast_fu_991_p4 = {{Y0_fu_534_p3[28:25]}};

assign tmp_256_fu_2720_p2 = (tmp_324_fu_2692_p1 | tmp_253_fu_2712_p3);

assign tmp_257_fu_2726_p4 = {{Log_normal_H_fu_2320_p3[33:16]}};

assign tmp_258_fu_1914_p1 = tmp_127_fu_1837_p2[33:0];

assign tmp_259_fu_2736_p3 = {{tmp_257_fu_2726_p4}, {tmp_256_fu_2720_p2}};

assign tmp_260_fu_2744_p2 = ((tmp_259_fu_2736_p3 == 34'd0) ? 1'b1 : 1'b0);

assign tmp_261_fu_2772_p3 = {{tmp_326_fu_2768_p1}, {6'd0}};

assign tmp_262_cast_fu_1017_p4 = {{Y0_fu_534_p3[12:9]}};

assign tmp_262_fu_2780_p4 = {{Log_normal_H_fu_2320_p3[17:10]}};

assign tmp_263_cast_fu_1027_p4 = {{Y0_fu_534_p3[44:41]}};

assign tmp_263_fu_2790_p3 = ((sel_tmp40_fu_2762_p2[0:0] === 1'b1) ? tmp_261_fu_2772_p3 : tmp_262_fu_2780_p4);

assign tmp_264_fu_2804_p4 = {{Log_normal_H_fu_2320_p3[33:26]}};

assign tmp_265_fu_1930_p3 = LogF_normal_H_cast_fu_1896_p2[32'd22];

assign tmp_266_cast_fu_1037_p4 = {{Y0_fu_534_p3[36:33]}};

assign tmp_266_fu_2814_p3 = ((tmp_260_fu_2744_p2[0:0] === 1'b1) ? 8'd0 : tmp_264_fu_2804_p4);

assign tmp_267_cast_fu_1047_p4 = {{Y0_fu_534_p3[20:17]}};

assign tmp_267_fu_2822_p3 = ((or_cond2_fu_2798_p2[0:0] === 1'b1) ? tmp_263_fu_2790_p3 : tmp_266_fu_2814_p3);

assign tmp_268_fu_2850_p2 = (tmp_334_fu_2846_p1 | tmp_267_fu_2822_p3);

assign tmp_269_cast_fu_1057_p4 = {{Y0_fu_534_p3[52:49]}};

assign tmp_269_fu_2856_p4 = {{p_v1_fu_2684_p3[15:8]}};

assign tmp_270_fu_2866_p3 = {{tmp_269_fu_2856_p4}, {tmp_268_fu_2850_p2}};

assign tmp_271_fu_2874_p2 = (tmp_270_fu_2866_p3 | tmp_253_fu_2712_p3);

assign tmp_272_fu_2880_p3 = {{tmp_257_fu_2726_p4}, {tmp_271_fu_2874_p2}};

assign tmp_273_fu_2888_p2 = ((tmp_272_fu_2880_p3 == 34'd0) ? 1'b1 : 1'b0);

assign tmp_274_fu_2894_p2 = ((tmp_270_fu_2866_p3 == 16'd0) ? 1'b1 : 1'b0);

assign tmp_275_fu_2966_p3 = {{tmp_326_fu_2768_p1}, {2'd0}};

assign tmp_276_fu_2974_p4 = {{Log_normal_H_fu_2320_p3[17:14]}};

assign tmp_277_fu_2984_p3 = ((sel_tmp50_fu_2960_p2[0:0] === 1'b1) ? tmp_275_fu_2966_p3 : tmp_276_fu_2974_p4);

assign tmp_278_fu_3012_p4 = {{Log_normal_H_fu_2320_p3[33:30]}};

assign tmp_279_fu_3030_p4 = {{Log_normal_H_fu_2320_p3[25:22]}};

assign tmp_280_fu_2008_p3 = Log_normal_L_fu_1993_p3[32'd60];

assign tmp_281_fu_3040_p3 = ((sel_tmp47_fu_2936_p2[0:0] === 1'b1) ? 4'd0 : tmp_279_fu_3030_p4);

assign tmp_282_fu_3048_p3 = ((or_cond3_fu_2992_p2[0:0] === 1'b1) ? tmp_277_fu_2984_p3 : tmp_281_fu_3040_p3);

assign tmp_283_fu_3168_p3 = ((or_cond6_fu_3163_p2[0:0] === 1'b1) ? tmp_282_reg_3993 : newSel4_reg_3998);

assign tmp_284_fu_3064_p4 = {{Log_normal_H_fu_2320_p3[9:2]}};

assign tmp_285_fu_3074_p3 = ((p_result_5_3_fu_2658_p2[0:0] === 1'b1) ? 8'd0 : tmp_284_fu_3064_p4);

assign tmp_286_fu_3082_p3 = ((tmp_274_fu_2894_p2[0:0] === 1'b1) ? tmp_285_fu_3074_p3 : tmp_264_fu_2804_p4);

assign tmp_287_fu_3090_p3 = ((sel_tmp43_fu_2912_p2[0:0] === 1'b1) ? 8'd0 : tmp_286_fu_3082_p3);

assign tmp_288_fu_3098_p4 = {{Log_normal_H_fu_2320_p3[25:18]}};

assign tmp_289_fu_3108_p3 = ((sel_tmp44_fu_2918_p2[0:0] === 1'b1) ? tmp_288_fu_3098_p4 : tmp_287_fu_3090_p3);

assign tmp_290_fu_3116_p3 = ((sel_tmp47_fu_2936_p2[0:0] === 1'b1) ? 8'd0 : tmp_289_fu_3108_p3);

assign tmp_291_fu_3124_p3 = ((sel_tmp48_fu_2942_p2[0:0] === 1'b1) ? tmp_262_fu_2780_p4 : tmp_290_fu_3116_p3);

assign tmp_293_fu_3180_p1 = tmp_292_reg_4008;

assign tmp_294_fu_3222_p3 = ((p_result_1_3_fu_3200_p2[0:0] === 1'b1) ? tmp_345_fu_3206_p3 : tmp_346_fu_3214_p3);

assign tmp_295_fu_3230_p7 = {{{{{{p_result_5_3_reg_3963}, {p_result_4_3_reg_3968}}, {p_result_3_3_reg_3973}}, {p_result_2_3_fu_3174_p2}}, {p_result_1_3_fu_3200_p2}}, {tmp_294_fu_3222_p3}};

assign tmp_296_fu_2114_p1 = p_in7_fu_2106_p3[15:0];

assign tmp_297_fu_3253_p2 = ((E_normal_H_fu_3243_p2 > 6'd33) ? 1'b1 : 1'b0);

assign tmp_298_fu_2192_p1 = p_in1_fu_2186_p2[7:0];

assign tmp_299_fu_2202_p1 = p_in7_fu_2106_p3[7:0];

assign tmp_300_fu_3150_p2 = (7'd34 + E_normal_L_cast_fu_2636_p1);

assign tmp_301_fu_3266_p2 = ((E_normal_H_2_fu_3259_p3 < 7'd34) ? 1'b1 : 1'b0);

assign tmp_302_fu_2236_p1 = Log_normal_L_fu_1993_p3[3:0];

assign tmp_303_fu_2577_p4 = {{p_val8_5_fu_2569_p3[3:2]}};

assign tmp_304_fu_3272_p1 = E_normal_H_2_fu_3259_p3;

assign tmp_305_fu_3276_p2 = Log_normal_H_reg_3958 << tmp_304_fu_3272_p1;

assign tmp_306_fu_3281_p2 = (7'd60 - E_normal_H_2_fu_3259_p3);

assign tmp_307_fu_3295_p2 = Log_normal_L_1_reg_3903 >> tmp_471_cast_fu_3291_p1;

assign tmp_308_fu_3304_p3 = ((tmp_301_fu_3266_p2[0:0] === 1'b1) ? tmp_347_fu_3300_p1 : 33'd0);

assign tmp_309_fu_1801_p2 = ((shiftval_reg_3793 > 7'd58) ? 1'b1 : 1'b0);

assign tmp_310_fu_1809_p2 = Z2o2_cast_fu_1746_p4 >> tmp_480_cast_fu_1806_p1;

assign tmp_311_fu_3366_p2 = (Z_small_cast_fu_3362_p1 - Z2o2_small_cast_fu_3352_p1);

assign tmp_312_fu_3372_p4 = {{{absZ0s_reg_3815}, {2'd0}}, {Z2o2_small_reg_3852}};

assign tmp_313_fu_2593_p3 = p_val8_5_fu_2569_p3[32'd1];

assign tmp_314_fu_3391_p4 = {{Log_small_fu_3384_p3[58:3]}};

assign tmp_315_fu_3421_p3 = Log_small_1_cast_fu_3409_p1[32'd57];

assign tmp_316_fu_3451_p3 = {{8'd255}, {E0_sub_1_fu_3443_p3}};

assign tmp_317_fu_2601_p3 = p_val8_5_fu_2569_p3[32'd3];

assign tmp_318_fu_3477_p2 = ($signed(11'd1033) - $signed(tmp_469_cast_fu_3349_p1));

assign tmp_319_fu_3487_p4 = {{Log_small_fu_3384_p3[56:3]}};

assign tmp_320_fu_3497_p3 = {{tmp_319_fu_3487_p4}, {2'd0}};

assign tmp_321_fu_2664_p2 = Log_normal_H_fu_2320_p3 << 64'd14;

assign tmp_322_fu_3505_p3 = ((tmp_350_fu_3469_p3[0:0] === 1'b1) ? tmp_320_fu_3497_p3 : tmp_351_fu_3483_p1);

assign tmp_323_fu_3513_p4 = {{Log_small_fu_3384_p3[57:3]}};

assign tmp_324_fu_2692_p1 = p_v1_fu_2684_p3[15:0];

assign tmp_325_fu_3523_p3 = {{tmp_323_fu_3513_p4}, {1'd0}};

assign tmp_326_fu_2768_p1 = Log_normal_H_fu_2320_p3[1:0];

assign tmp_327_fu_3531_p3 = ((tmp_348_fu_3413_p3[0:0] === 1'b1) ? tmp_325_fu_3523_p3 : tmp_322_fu_3505_p3);

assign tmp_328_fu_3539_p3 = {{tmp_327_fu_3531_p3}, {1'd0}};

assign tmp_329_fu_3322_p2 = (tmp_352_fu_3318_p1 | tmp_308_fu_3304_p3);

assign tmp_330_fu_3338_p3 = {{tmp_329_fu_3322_p2}, {tmp_503_cast_fu_3328_p4}};

assign tmp_331_fu_3571_p4 = {{Log_g_fu_3547_p3[56:5]}};

assign tmp_332_fu_3589_p2 = (tmp_355_fu_3581_p3 | sticky_fu_3557_p2);

assign tmp_333_fu_3595_p2 = (tmp_354_fu_3563_p3 & tmp_332_fu_3589_p2);

assign tmp_334_fu_2846_p1 = p_v1_fu_2684_p3[7:0];

assign tmp_335_fu_3605_p3 = ((small_reg_3799[0:0] === 1'b1) ? E_small_fu_3463_p2 : tmp_318_fu_3477_p2);

assign tmp_336_cast_fu_1695_p4 = {{grp_range_red_fu_446_ap_return_0[54:28]}};

assign tmp_336_fu_3612_p3 = {{tmp_335_fu_3605_p3}, {tmp_331_fu_3571_p4}};

assign tmp_337_fu_3630_p3 = {{sR_reg_3671}, {63'd0}};

assign tmp_338_fu_3190_p4 = {{p_val8_7_fu_3183_p3[3:2]}};

assign tmp_339_cast_fu_1713_p1 = tmp_183_fu_1705_p3;

assign tmp_339_fu_3643_p1 = res_fp_fu_3637_p2;

assign tmp_342_cast_fu_1885_p1 = tmp_254_reg_3846;

assign tmp_345_fu_3206_p3 = p_val8_7_fu_3183_p3[32'd1];

assign tmp_346_fu_3214_p3 = p_val8_7_fu_3183_p3[32'd3];

assign tmp_347_fu_3300_p1 = tmp_305_fu_3276_p2[32:0];

assign tmp_348_fu_3413_p3 = Log_small_fu_3384_p3[32'd58];

assign tmp_349_fu_3437_p2 = (tmp_348_fu_3413_p3 | tmp_315_fu_3421_p3);

assign tmp_350_fu_3469_p3 = Log_small_fu_3384_p3[32'd57];

assign tmp_351_cast_fu_1987_p1 = tmp_192_reg_3879;

assign tmp_351_fu_3483_p1 = Log_small_fu_3384_p3[55:0];

assign tmp_352_cast_fu_1990_p1 = $signed(tmp_194_reg_3884);

assign tmp_352_fu_3318_p1 = tmp_307_fu_3295_p2[32:0];

assign tmp_353_fu_3553_p1 = Log_g_fu_3547_p3[3:0];

assign tmp_354_cast1_fu_2016_p1 = tmp_280_fu_2008_p3;

assign tmp_354_cast_fu_2020_p1 = tmp_280_fu_2008_p3;

assign tmp_354_fu_3563_p3 = Log_g_fu_3547_p3[32'd4];

assign tmp_355_cast_fu_2030_p1 = $signed(tmp_197_fu_2024_p2);

assign tmp_355_fu_3581_p3 = Log_g_fu_3547_p3[32'd5];

assign tmp_425_cast_fu_2836_p4 = {{Log_normal_H_fu_2320_p3[9:6]}};

assign tmp_469_cast_fu_3349_p1 = E_normal_H_2_reg_4018;

assign tmp_470_cast_fu_3287_p1 = $signed(tmp_306_fu_3281_p2);

assign tmp_471_cast_fu_3291_p1 = $unsigned(tmp_470_cast_fu_3287_p1);

assign tmp_480_cast_fu_1806_p1 = $unsigned(shiftval_reg_3793);

assign tmp_485_cast_fu_3380_p1 = tmp_312_fu_3372_p4;

assign tmp_490_cast_fu_3459_p1 = tmp_316_fu_3451_p3;

assign tmp_503_cast_fu_3328_p4 = {{Log_normal_normd_L_fu_3312_p2[59:36]}};

assign tmp_512_cast_fu_3601_p1 = tmp_333_fu_3595_p2;

assign tmp_515_cast_fu_3620_p1 = tmp_336_fu_3612_p3;

assign tmp_fu_488_p1 = fpX_fu_484_p1[62:0];

assign tmp_s_fu_512_p4 = {{{{1'd1}, {tmp_128_fu_492_p1}}}, {1'd0}};

always @ (posedge ap_clk) begin
    Z2o2_small_reg_3852[2:0] <= 3'b000;
end

endmodule //logd
